:ProductName: Windup
:ProductShortName: Windup
:ProductDocRulesGuideURL: http://windup.github.io/windup/docs/latest/html/WindupRulesDevelopmentGuide.html


[[About-Rules]]
=== About {ProductShortName} Rules

{ProductShortName} is a rule-based migration tool that analyzes the APIs, technologies, and architectures used by the applications you plan to migrate. In fact, the {ProductShortName} tool executes its own core set of rules through all phases of the migration process. It uses rules to extract files from archives, decompile files, scan and classify file types, analyze XML and other file content, analyze the application code, and build the reports. 

{ProductShortName} builds a data model based on the rule execution results and stores component data and relationships in a graph database, which can then be queried and updated as needed by the migration rules and for reporting purposes.

{ProductShortName} rules use the following familiar rule pattern:

    when(condition)
        perform(action)
    otherwise(action)

{ProductShortName} provides a comprehensive set of standard migration rules out-of-the-box. Because applications may contain custom libraries or components, {ProductShortName} allows you to write your own rules to identify use of components or software that may not be covered by the existing ruleset. If you plan to write your own custom rules, see the {ProductDocRulesGuideURL}[
{ProductName} Rules Development Guide] for detailed instructions.
