:ProductName: Windup
:ProductShortName: Windup

=== Customer Portal Tags

_This is a work in progress, so please feel free to update this page with new tag suggestions!_

==== Tags Needed For Most Articles

The following is a list and description of tags that currently exist on the Customer Portal that we should use when writing {ProductName} migration articles for the Customer Portal. 

windup:: All {ProductShortName} articles should use this tag so we can quickly find all the {ProductShortName} articles.

migration:: All {ProductShortName} articles should use this tag so a search includes the articles.

jboss-eap:: Migration material for JBoss EAP platforms.

weblogic:: Migration material related to WebLogic.

websphere:: Migration material related to WebLogic.

java:: Java related issues

==== Additional Tags That are Available

api::
archive::
authentication::
classloading::
configuration::
database::
deployment::
ejb::
jboss_cache::
jboss_clustering::
jboss_security::
jboss_remoting::
jboss_transactions::
jbossweb::
jca::
jms::
jndi::
jpa::
jsf::
ldap::
load_balancing::
mbean::
messaging::
webservices::
ws-security:: Web Service security


==== Questions

. What other tags do we need?
. Do we need version specific tags? For example, 'jboss-eap-5', 'jboss-eap-6', 'websphere-8', 'weblogic-10'. 
.. If so, do we go into point releases like 'jboss-eap-6.2', 'websphere-8.5' or 'weblogic-12cR2'?
.. Would it be better just to add a bunch of release numbers like '6', '6.1', '6.2', '8', etc. and use them with a product tag to create more flexibility?


