:ProductName: Windup
:ProductShortName: Windup

=== XML Rule Construction

This section describes the basic construction of {ProductShortName} XML rules. All XML rules are defined as elements within rulesets. 

==== Rulesets

A  ruleset is a group of one or more rules that targets a specific area of migration. This is the basic structure of the `<ruleset>` element.

[source,xml,options="nowrap"]
----
<ruleset id="UNIQUE_RULESET_ID"> <!--Defines a ruleset with a unique ruleset ID.-->
  <metadata> <!-- The ruleset metadata. -->
    <description/> <!-- The ruleset description. -->
    <dependencies/> <!-- The rule add-ons required by this ruleset. -->
    <sourceTechnology/> <!-- The source technology. -->
    <targetTechnology/> <!-- The target technology. -->
    <overrideRules/> <!-- Indicates rule overriding. --> <1>
  <rules> <!-- Contains one or more individual rules. -->
    <rule id="UNIQUE_RULE_ID"> <!-- Defines a rule with a unique ID. --> <2>
      <when/> <!-- The conditions to match on. --> <3>
      <perform/> <!-- The action to perform when the condition is matched. --> <4>
      <otherwise/> <!-- The action to perform when the condition is not matched. --> <5>
      <where/> <!-- Matches on a string pattern. --> 
    <file-mapping/> <!-- Maps an extension to a graph type. -->
    <package-mapping/> <!-- Maps a package pattern to a organization name. -->
  </rules>
</ruleset>
----
<1> Indicates that rules in this ruleset override rules with the same ID from the core ruleset distributed with Windup. Both the ruleset id and the rule id must match a rule within the core ruleset or the rule will be ignored. This is "false" by default. See xref:Rules-Overriding-Rules[Overriding Rules] for more details.
<2> It is recommended to include the ruleset ID as part of the rule ID, for example, `UNIQUE_RULESET_ID_UNIQUE_RULE_ID`.
<3> See the syntax of the xref:Rules-XML-Rule-When-Condition-Syntax[`<when>`] element.
<4> See the syntax of the xref:Rules-XML-Rule-Perform-Action-Syntax[`<perform>`] element.
<5> This element uses the same syntax as the xref:Rules-XML-Rule-Perform-Action-Syntax[`<perform>`] element.