= Windup Documentation Contributing Guide

== Wiki Asciidoc Syntax Guidelines

The following guidelines make the transition from the Windup Wiki pages to the Windup documentation GitHub smoother.

* Name wiki pages using only letters, numbers and dashes. Do not include spaces, colons, or other special characters in page names.

* Be sure to add a level 3 page heading at the top of each page. When compiled in a book, the Guide name is the top level, chapters are level 2, and the page is level  3.

+
----
=== Build Windup from Source
----

* At the beginning of each new Wiki page, add an anchor with the exact page name, including the dashes. This generates the correct anchors that are needed when the pages are combined into a book.
+
----
[[Dev-Build-Windup-from-Source]]
=== Build Windup from Source
----

* Wiki generates anchors using dashes for spaces. AsciiDoctor generates a leading underscore and underscores for spaces. When referring to another section within the same page, do not use the `<<section-title-anchor>>` syntax. Instead, create an anchor and use the 'xref:' syntax to provide the link. The following is an example of how to create the anchor at the top of a section using double brackets to force the generation of dashes instead of underscores:
+
----
[[windup-command-examples]]
==== Windup Command Examples
----

* Then use the `xref` to create the link.
+
----
See xref:windup-command-examples[Windup Command Examples] for more information.
----

== Build the Windup Guides

* If you have not yet done so, install Ascidoctor
+
----
gem install sciidoctor
----
      
* A script is provided that updates the documentation with the latest Wiki updates, automatically replaces internal links, and builds the guides. To run it, navigate to the root of the windup-documentation directory and type:
+
----
scripts/windupDocUpdate.sh
----
+
The script does the following:
    
** Copies the guides from the Wiki and leaves the `.asciidoc` extension. Compare this page to the Guide template in the windup-documentation to see if any pages were added to the guide.
+
----  
[cols="2*"] 
|===
| **Wiki Guide Name** | **Windup Documentation Guide Name**

| User-Guide.asciidoc | Windup-User-Guide.adoc 

| Rules-Development-Guide.asciidoc | Windup-Rules-Development-Guide.adoc 

| Core-Development-Guide.asciidoc | Windup-Core-Development-Guide.adoc 

| Migration-Planning-Guide.asciidoc | Windup-Migration-Planning-Guide.adoc 
|===
----

** Copies the pages from the Windup Wiki and replaces the `.asciidoc` extension with `.adoc`, for example:
+
----
cp ../windup.wiki/What-is-Windup.asciidoc docs/What-is-Windup.adoc
----
            
** Finds and displays internal links so the anchors can be verified.
+
----
grep 'xref:[a-z]' `find . -name '*.adoc'`
----

** Finds and lists pages containing `link:` macros to other pages. These pages must be added to the book.
      
** Replaces the `link:` macros with a `xref:` macros.
+
----
asciidoctor -dbook -a toc -o html/WindupUserGuide.html docs/Windup-User-Guide.adoc
----

== Push the Windup Guides to the Windup GitHub

* The first time, you must fork and clone the windup GitHub repository. After that, just fetch the latest upstream.

+
----
git clone https://github.com/windup/windup.git
git fetch upstream
----

* The first time, you must fork and clone the windup-documentation GitHub repository. After that, just fetch the latest upstream.

+
----
git clone https://github.com/windup/windup-documentation.git
git fetch upstream
----

* Navigate to the local windup directory.

+
----
cd windup
----

* Checkout the gh-pages from the windup repository

+
----
git checkout -b gh-pages windup 
----

* If the directory does not yet exist, create a docs/WINDUP-RELEASE/html/ directory.

+
----
mkdir -p docs/2.0.0.Beta6/html
----

* Copy any new images, stylesheets, and html files from windup-documentation:

+
----
cp ../windup-documentation/*.html ../windup-documentation/*.css ../windup-documentation/images/* docs/2.0.0.Beta6/html/
----

* Add the updated files to GitHub.

+
----
git add docs
----

* Commit the changes.

+
----
git commit -m "HTML docs"
----

* Push the changes to GitHub.

+
----
git push upstream gh-pages
----

* View the documentation at <http://windup.github.io/windup/docs/2.0.0.Beta6/html/>

