=  Windup 2.0 Product Documentation

== Overview

Windup project documentation is created collaboratively on the Windup project Wiki site located here: <https://github.com/windup/windup/wiki>. 
This `windup-documentation` repository takes documentation from that site, makes minor modifications, and publishes the pages in single HTML page book format. 
This repository will contain the source for the official documentation when the Windup 2.0 ships.

== Procedure to Copy and Modify the Wiki Documentation

Run the scripts/windupDocUpdate.sh script to copy and modify the files. 

. Copies the `.asciidoc` files to the `docs/` directory and renames them with the `.adoc` extension.
. Replaces the `xref:` macros to other pages with `xref:` macros.
. Uses AsciiDoctor to create the guides in the `html/` directory.

== Procedure to Publish the Guides

* The first time, you must fork and clone the windup GitHub repository. After that, just fetch the latest upstream.
+
----
git clone https://github.com/windup/windup.git
git fetch upstream
----
    
* The first time, you must fork and clone the windup-documentation GitHub repository. After that, just fetch the latest upstream.
+
----
git clone https://github.com/windup/windup-documentation.git
git fetch upstream
----
    
* Navigate to the local windup directory.
+
----
cd windup
----
    
* Checkout the gh-pages from the windup repository
+
----
git checkout -b gh-pages windup
----

* If the directory does not yet exist, create a docs/WINDUP-RELEASE-html/ directory.
+
----
mkdir -p docs/2.0.0.Beta6/html (if it doesn't exist!)
----
    
* Copy any new images, stylesheets, and html files from windup-documentation:
+
----
cp ../windup-documentation/html/*.html ../windup-documentation/*.css ../windup-documentation/images/* docs/2.0.0.Beta6/html
----
 
* Add the updated files to GitHub.
+
----
git add docs
----
    
* Commit the changes.
+
----
git commit -m "Update message..."
----

* Push the changes to GitHub.
+
----
git push upstream gh-pages
----

== Access the Guides

View the documentation at the following URLs.

[cols="2*"]
|===
| **Guide** | **URL**
| Windup User Guide | http://windup.github.io/windup/docs/2.0.0.Beta6/html/WindupUserGuide.html
| Windup Rules Development Guide | http://windup.github.io/windup/docs/2.0.0.Beta6/html/WindupRulesDevelopmentGuide.html
| Windup Core Development Guide | http://windup.github.io/windup/docs/2.0.0.Beta6/html/WindupCoreDevelopmentGuide.html
| Windup Migration Planning Guide | TBD
|===




