= Welcome to Windup 2.0


_NOTE: The Windup 2.0 project is currently under development. If you
want to contribute or participate in developer discussions, join us on
the irc.freenode.net #windup channel or subscribe to the windup-dev
mailing list at https://lists.jboss.org/mailman/listinfo/windup-dev._

== About Windup

Windup 2.0 is a tool used to simplify Java application migrations. It is the 
sequel to the original Windup 0.7.x, which has moved to the 
https://github.com/windup/windup-legacy[windup-legacy] GitHub repository.

* link:What-is-Windup.adoc[What is Windup?]
* link:Features-of-Windup-2.0.adoc[Features of Windup 2.0]
* link:Get-Involved.adoc[Get Involved] - We need your feedback!
* link:Report-an-Issue-with-Windup.adoc[Report Issues] - If you run into any problems executing Windup or understanding the instructions, please report it so we can make it better.

IMPORTANT:: There is currently a bug in the parser that does not resolve the tilde (~) in a path name correctly. For now, you must fully spell out the complete path name when it is passed as an argument in the Windup command line. For example, use `/home/username/path-to-file` rather than `~/path-to-file`. For details, see https://issues.jboss.org/browse/WINDUP-305.

== Windup Guides

Windup documentation is organized into guides that target specific
audiences.

* link:./User-Guide.adoc[Windup User Guide]:
This guide is for engineers, consultants, or others who plan to use
Windup to migrate applications or other components.
* link:./Rules-Development-Guide[Windup Rules Development Guide]: 
This guide provides details for developers, consultants, and others 
who plan to create custom rule add-ons for the Windup 2.0 project.
* link:./Core-Development-Guide[Windup Core Development Guide]: 
This guide provides information for developers who plan to contribute 
source code updates or core rule add-ons to the Windup 2.0 project.
* link:./Migration-Planning-Guide[Migration Planning Guide]: 
This guide is for developers, Project Managers, or IT managers who must 
interpret the Windup reports and develop a project plan.
