[[Rules-Rule-Story-Points]]
=== Rule Story Points

==== What are Story Points?

Story points are an abstract metric used in Scrum methodology to estimate the level of effort for various tasks. They are based on a http://scrummethodology.com/scrum-effort-estimation-and-story-points/[modified Fibonacci sequence]. In a similar manner, Windup uses story points to express the level of effort needed to migrate particular application constructs, and in a sum, the application as a whole.

==== How to Estimate Story Points in a Rule

TODO: TBD.

This could contain relative examples like: 

* Pure copy'n'paste - when we know for sure it will need no migration: 0
* When we don't know if it will need a migration: Could depend on number of unknown imports, size
of the file, ...
* Changing parameter name, or value units: 2.
* Porting one web page (or similar concept) from one web framework to
the other: Could depend on complexity, e.g. number of components. E.g.
20 per component.
* Porting MyBatis to JPA: 20 per query.