[[Rules-Create-a-Basic-XML-Rule]]
=== Create a Basic XML Rule

You can create a rule addon using Java or a rule using XML or Groovy. This topic describes how to create a rule using XML.

==== Prerequisites

* You should have already xref:Install-Windup[installed Windup]. 
* Before you begin, you may also want to be familiar with the following documentation:
** Windup rules are based on the ocpsoft *rewrite* project. You can find more information about ocpsoft *rewrite* here: http://ocpsoft.org/rewrite/
** The JavaDoc for the Windup API is located here: http://windup.github.io/windup/docs/javadoc/latest/

NOTE:  Working examples of XML-based rules can be found in the Windup quickstarts GitHub repository located here: https://github.com/windup/windup-quickstarts

==== Create a Rule

The following is an example of an XML rule.

        <?xml version="1.0"?>
        <ruleset xmlns="http://windup.jboss.org/v1/xml"
          id="customruleprovider">
          <!-- This defaults to MIGRATION_RULES -->
          <phase>
            DISCOVERY
          </phase>
          <rules>
            <rule>
              <when>
                <javaclass references="javax.servlet.http.HttpServletRequest">
                  <location>METHOD_PARAMETER</location>
                </javaclass>
              </when>
              <perform>
                <hint>
        	  <message>Message from XML Rule</message>
                  <link href="http://example.com" description="Description from XML Hint Link" />
                </hint>
                <log message="test log message"/>
              </perform>
              <otherwise>
                <!--  -->
              </otherwise>
            </rule>
            <rule>
              <when>
                <xmlfile xpath="/w:web-app/w:resource-ref/w:res-auth[text() = 'Container']">
                  <namespace prefix="w" uri="http://java.sun.com/xml/ns/javaee"/>
                </xmlfile>
              </when>
              <perform>
                <hint>
        	  <message>Container Auth</message>
                </hint>
                <xslt description="Example XSLT Conversion" extension="-converted-example.xml" 
                         xsltFile="/exampleconversion.xsl"/>
                <log message="test log message"/>
              </perform>
              <otherwise>
                <!--  -->
              </otherwise>
            </rule>
          </rules>
        </ruleset>

===== Create the XML Rule

**Note:** Windup only analyzes XML files with names ending in `.windup.xml`. Be sure to name XML-based rules using this naming convention!

The XML rule consists of the following level elements:

* **<ruleset>**: This element defines this as a Windup rule.
* **<phase>**: This element specifies when the ruleset should execute. See xref:Rules-Rules-Execution-Lifecycle#rule-phases[Rule Phases in the Rule Execution Lifecyle] for more information.
* **<rules>**: element contains the individual rules.
** **<rule>**: This element is a child of the **rules** element. One or more rules can be defined for a ruleset. Each `rule` contains the following elements.
*** **<when>**: This element defines the condition to match on.
**** **<javaclass references="CLASS_NAME">**
***** **<location>**: The location where the reference was found in a Java source file. See the http://windup.github.io/windup/docs/javadoc/latest/org/jboss/windup/rules/apps/java/scan/ast/TypeReferenceLocation.html[Enum TypeReferenceLocation] Javadoc for valid values.
*** **<perform>**: This element is invoked when the condition is met.
**** **<hint>**: This child element of **perform** is used to create a `hint`
***** **<message>**: 
***** **<link>**:
**** **<xslt>**: This specifies how to transform the the specified XML file
**** **<log>**: This child element of **perform** is used to log a message. It takes the attribute **message** to define the text message.
*** The **<otherwise>** element is invoked when the condition is not met.

==== Add the Rule to Windup

A Windup rule is installed simply by copying the rule to the appropriate Windup folder. Windup scans for rules in the following locations:


WINDUP_HOME/rules/:: This is the Windup folder where you run the Windup executable. See xref:About-the-WINDUP_HOME-Variable[About the WINDUP_HOME Variable] for details.

${user.home}/.windup/rules/:: This folder is created by Windup the first time you execute Windup.
+
--------
For Linux or Mac:   ~/.windup/rules/
For Windows: "\Documents and Settings\USER_NAME\.windup\rules\"  -or-  "\Users\USER_NAME\.windup\rules\"
--------

==== Test the XML Rule

NOTE: If you have not started Windup, follow the instructions to xref:Execute-Windup[Execute Windup].

Test the XML rule against your application file by running the `windup-migrate-app` command in the Windup console prompt. 

The command uses this syntax:

--------
windup-migrate-app [--sourceMode true] --input INPUT_ARCHIVE_OR_FOLDER --output OUTPUT_REPORT_DIRECTORY --packages PACKAGE_1 PACKAGE_2 PACKAGE_N
--------

You should see the following result:

--------
***SUCCESS*** Windup report created: QUICKSTART_HOME/windup-reports-java/index.html
--------
For more information and examples of how to run Windup, see: xref:-Execute-Windup[Execute Windup] 

 
