:ProductName: Windup
:ProductShortName: Windup

[[Dev-Rule-Documentation-Tracker]]
=== Rule Documentation Tracker

==== Rule Tracker Spreadsheet

* This page tracks the existing rules. It also tracks JBoss Migration Documentation and Windup KBase article that need rules to point to them.

* https://docs.google.com/spreadsheets/d/1hJCTf5U4XNnN795MuQXgFGHK0aj3ZG6daGpydPq6DdU/edit#gid=0
+
_NOTE: (OBSOLETE) The content for the page has been moved to the above spreadsheet and is now obsolete:https://docs.google.com/spreadsheets/d/1XJ1LNqhtT8ijZTFROx5OjezOii8TBDI4Us7M9q1rQLo/edit#gid=0_

==== Documentation You Can Refer To

* JBoss Migration Guide: https://access.redhat.com/documentation/en-US/JBoss_Enterprise_Application_Platform/6.4/html-single/Migration_Guide/index.html

The following links provide a list of available Kbase articles is located here: 

* https://access.redhat.com/taxonomy/tags/windup
* (Alternate link): https://access.redhat.com/search/#/?q=tag:%28%22windup%22%29&p=2&srch=any&language=en&documentKind=


==== KBase Articles - Needed

The following guides are NOT published and the topics are in the process of being converted to the KBase articles. JIRAs need to be created for the ones not yet converted.

* WebLogic Migration Guide: http://docbuilder.usersys.redhat.com/13710/
* WebSphere Migration Guide: http://docbuilder.usersys.redhat.com/22175/

The following is a link to the JIRAs (Project: Windup, Component: Documentation) for Kbase articles that need to be written:

https://issues.jboss.org/issues?jql=project%20%3D%20WINDUP%20AND%20status%20in%20%28Open%2C%20Reopened%29%20AND%20component%20%3D%20Documentation%20AND%20labels%20%3D%20kbase
