topics/templates/document-attributes.adoc[]

//:ProductName: Windup
//:ProductShortName: Windup
//:ProductVersion: 2.5.0-Final
//:ProductDistribution: windup-distribution-2.5.0-Final
//:ProductHomeVar: WINDUP_HOME 


[[About-the-HOME-Variable]]
=== About the {ProductHomeVar} Variable

This documentation uses the *{ProductHomeVar}* _replaceable_ value to denote the path to the {ProductName} distribution. When you encounter this value in the documentation, be sure to replace it with the actual path to your {ProductShortName} installation.

* If you download and install the latest distribution of {ProductShortName} from the JBoss Nexus repository, {ProductHomeVar} refers to the {ProductDistribution} folder extracted from the downloaded ZIP file.
* If you build {ProductShortName} from GitHub source, {ProductHomeVar} refers to the {ProductDistribution} folder extracted from the windup-distribution/target/{ProductDistribution}.zip file.


[NOTE]
====
You may see the following error when you run the command:
[source,options="nowrap"]
----
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.5.5:single (distribution-offline) on project windup-distribution: Failed to create assembly: Error creating assembly archive offline: Problem creating zip: Execution exception: Java heap space -> [Help 1]
----

If you see this error, run the following command to increase the HEAP.
[source,bash,options="nowrap"]
----
Linux: export MAVEN_OPTS="-Xmx1024m -XX:MaxPermSize=128m"
Windows: set MAVEN_OPTS="-Xmx1024m -XX:MaxPermSize=128m"
----
