:toc:
:toclevels: 3
:numbered:

include::topics/templates/document-attributes.adoc[]

:imagesdir: topics/images
:windup-rules-development-guide:

= {ProductName} Rules Development Guide

== Introduction 

This guide is for engineers, consultants, and others who plan to create custom XML-based rules for {ProductName}. 

If you are new to {ProductName}, it is recommended that you start with the {ProductDocUserGuideURL}[{ProductName} User Guide]. It provides detailed information about system requirements and detailed instructions on how to install and execute {ProductShortName}. It also contains tips to {ProductDocUserGuideURL}#Optimize-Performance[optimize performance] and provides links to other sources of information about {ProductShortName}.

If you would like to contribute to the {ProductName} source code base or provide Java-based rule add-ons, see the https://github.com/windup/windup/wiki[{ProductName} Wiki].

== Getting Started

include::topics/Rules-Create-Your-First-Rule.adoc[leveloffset=+2]

== Creating XML Rules

include::topics/Rules-XML-Rule-Construction.adoc[leveloffset=+2]

include::topics/Rules-Create-a-Basic-XML-Rule.adoc[leveloffset=+2]

=== XML Rule Syntax

include::topics/Rules-XML-Rule-When-Condition-Syntax.adoc[leveloffset=+3]

include::topics/Rules-XML-Rule-Perform-Action-Syntax.adoc[leveloffset=+3]

include::topics/Rules-Test-a-Basic-XML-Rule.adoc[leveloffset=+1]

include::topics/Rules-Override-Rules.adoc[leveloffset=+1]

== Additional Resources

include::topics/Rules-Review-the-Existing-XML-Rules.adoc[leveloffset=+2]

include::topics/Rules-Important-Links.adoc[leveloffset=+2]

[appendix]
== Reference Material

include::topics/Rules-Rule-Story-Points.adoc[leveloffset=+2]

include::topics/About-the-HOME-Variable.adoc[leveloffset=+2]




