[[execute]]
= Run the {MavenNameTitle}

The {MavenName} is executed by including a reference to the plugin inside your application's `pom.xml`. When the application is built, the {MavenName} is executed and generates the reports for analysis. 

To run the {MavenName} perform the following steps.

. Include the following plugin inside your application's `pom.xml`:
+
[source,xml,options="nowrap",subs="+quotes,+attributes"]
----
[...]
<plugin>
    <groupId>org.jboss.windup.plugin</groupId>
    <artifactId>windup-maven-plugin</artifactId>
    <version>{MavenProductVersion}</version>
    <executions>
        <execution>
            <id>run-windup</id>
            <phase>package</phase>
            <goals>
                <goal>windup</goal>
            </goals>
        </execution>
    </executions>
    <configuration>
        <offlineMode>true</offlineMode>
    </configuration>
</plugin>
[...]
----
+
* `offlineMode`: Indicates to run in offline mode, disabling network features to improve performance.
+
The above example demonstrates the minimum required arguments. See xref:maven_arguments[{ProductShortName} Maven Arguments] for a detailed description of all available arguments.

. If using Java 11, then `--add-modules=java.se` must be added to the `MAVEN_OPTS` environment variable. When using older versions of Java this is not necessary, and you can proceed to the next step.
+
[source,options="nowrap"]
----
export MAVEN_OPTS=--add-modules=java.se
----
+
[IMPORTANT]
====
Using the {MavenName} on Java 11 is provided as Technology Preview only. Technology Preview features are not supported with Red Hat production service level agreements (SLAs), might not be functionally complete, and Red Hat does not recommend to use them for production. These features provide early access to upcoming product features, enabling customers to test functionality and provide feedback during the development process.

See link:{KBArticleTechnologyPreview}[Technology Preview Features Support Scope] on the Red&nbsp;Hat Customer Portal for information about the support scope for Technology Preview features.
====

. Build the project.
+
[source,options="nowrap"]
----
$ mvn clean install
----

. xref:access_report[Access the generated reports].
