[id='goals_assessing_migration_{context}']
= Goals of Assessing a Migration

Many organizations are faced with the challenges of keeping their existing business operations running, while also trying to innovate. There are typically increased expectations to deliver new functionality faster and to reduce cost.

When assessing a migration or modernization effort, it is important to address the challenges that are specific to your organization. Common challenges that organizations face are limited budgets, lack of in-house skills, perceived risks, no known predictable process, and accurate effort estimation in a timely manner.

In general, the goals when assessing a large-scale middleware migration or modernization effort are to:

* Predict the level of effort and cost.
* Schedule the application migrations and handle conflicts.
* Identify all potential risks at a code, infrastructure, process, or knowledge level.
* Predict the return on investment to make the business case.
* Identify and mitigate risks to the business.
* Minimize disruption to existing business operations.

Red Hat has developed a strategy to minimize risk and make application migration and modernizations more efficient. 
