// Module included in the following assemblies:
// * docs/plugin-guide_5/master.adoc
[id='install_plugin_{context}']
= Installing the {PluginNameTitle}

Review the supported configurations to make sure that you are using a development environment that is compatible with the {PluginName}.

If you do not already have an existing installation, download link:http://www.eclipse.org/downloads/[Eclipse] or link:https://developers.redhat.com/products/codeready-studio/download/[Red Hat CodeReady Studio] and install it.

[NOTE]
--
This guide uses _IDE_ to refer to an installation of Eclipse or Red Hat CodeReady Studio.

There is an {ProductShortName} extension for Visual Studio Code and Eclipse Che.
The extension is only available as a Minimum Viable Product and will be fully documented and supported in a future Release of {ProductShortName}.
For more information about link:https://marketplace.visualstudio.com/items?itemName=redhat.mta-vscode-extension[the extension], visit the Visual Studio Marketplace.
--

.Prerequisites

* If you are using Eclipse, and not Red Hat CodeReady Studio, you must install JBoss Tools before installing the {PluginNameTitle}.

* {PluginName} on macOS has the following prerequisite:

** Set the `maxproc` value to `2048` or greater

.Installing the plugin

. Launch Eclipse.
. From the menu bar, select *Help* -> *Install New Software*.
. Add the {ProductShortName} update site:

.. Next to the *Work with* field, click *Add*.
.. In the *Name* field, enter `{ProductShortName}`.
.. In the *Location* field, enter `\http://download.jboss.org/jbosstools/photon/stable/updates/mta/` and click *OK*.
.. Select all of the check boxes under *JBoss Tools - MTA* and click *Next*.

. Review the installation details and click *Next*.
. Accept the terms of the license agreement and click *Finish* to install the plugin.
. Restart your IDE for the changes to take effect.

.Installing the plugin for an offline environment

. Download the link:{ProductDownloadURL}{IDEPluginFilename}-{ProductVersion}.zip[IDE Plugin Repository].
. Launch your IDE.
. From the menu bar, select *Help* -> *Install New Software*.
. Add the {ProductShortName} update site:

.. Next to the *Work with* field, click *Add*.
.. In the *Name* field, enter `{ProductShortName} - Offline`.
.. Next to the *Location* field, click *Archive*.
.. Select the file downloaded in the first step and click *OK*.
.. Select all of the checkboxes under *JBoss Tools - MTA* and click *Next*.

. Review the installation details and click *Next*.
. Accept the terms of the license agreement and click *Finish* to install the plugin.
. Restart your IDE for the changes to take effect.
