// Module included in the following assemblies:
// * docs/rules-development-guide_5/master.adoc
[id='validation_report_understanding_{context}']
= Understanding the Validation Report

The validation report is split into sections that organize any test failures into the packages and tests executed. This report contains the following sections:

* Summary
* Package List
* Test Cases

[discrete]
[id='validation_report_summary_{context}']
== Summary

The summary contains the overall number of tests executed and reports the number of errors and failures encountered. It also provides an overall success rate, and the time taken, in seconds, for the report to be generated.

[discrete]
[id='validation_report_package_list_{context}']
== Package List

The package list contains the number of tests executed per package, and reports the number of errors and failures encountered. It also provides a success rate, and the time taken, in seconds, for each package to be analyzed.

It is expected to see a single package, `org.jboss.windup.rules.tests`, unless additional test cases have been defined.

[discrete]
[id='validation_report_test_cases_{context}']
== Test Cases

This section details each executed test. Each failure includes an optional *Details* section that can be expanded to show the stack trace for the assertion, including a line indicating the human readable source of the error.
