// Module included in the following assemblies:
// * docs/web-console-guide_5/master.adoc
[id='troubleshoot_web_console_openshift_install_{context}']
= Troubleshooting

The following steps discuss common techniques for troubleshooting the {WebName} in an OpenShift environment. These instructions are focused on issues specific to the {WebName}.

== Obtaining the latest image

The first step in troubleshooting in an OpenShift environment is to ensure that the latest image is in use.

NOTE: If you have deployed the {WebName} by pasting in a JSON template, no image stream is created and the following steps are not applicable.

.Procedure

. Open the OpenShift console.
. Click *Builds* -> *Images*.
. Ensure that the column under *Tags* indicates that each image is on the `latest` stream.
. If the latest image is not in use, follow the steps for the OpenShift installation to redeploy the latest image of the {WebName}.

[id='examine_logs_{context}']
== Examining and collecting {WebName} logs

Each Pod is configured to provide detailed logging that assists with narrowing down the precise cause of an issue. The following steps discuss viewing and obtaining these logs.

.OpenShift console

You can download a Pod's log with the OpenShift Container Platform console.

.Procedure

. Open the OpenShift console and navigate to *Applications* -> *Pods*.
. Click the name of the Pod that you wish to examine. To examine the current {WebName} Pod, select the `mta-web-console-<POD_NAME>` that is in a `Running` state.
. Click *Logs*.
. Click *Download* to download and save a log.

.CLI

You can download a Pod's log with the CLI.

.Procedure

. Obtain the Pod names:
+
----
$ oc get pods
----
+
The output resembles the following:
+
----
NAME                       READY     STATUS      RESTARTS   AGE
eap-builder-1-build        0/1       Completed   0          1d
mta-postgresql-1-hfbdn     1/1       Running     0          1d
mta-sso-1-build            0/1       Completed   0          1d
mta-web-console-1-build    0/1       Completed   0          1d
mta-web-console-1-vt7s5    1/1       Running     1          1d
sso-1-wjl2n                1/1       Running     1          1d
----

. Use `oc logs` to examine the Pod's log.
+
----
$ oc logs <POD_NAME>
----

. The output may be redirected to obtain a copy of the current log:
+
----
$ oc logs <POD_NAME> > ./mta-openshift-<POD_NAME>.log
----

== Common issues

.Executor Pod throws `NoRouteToHostException`

When accessing the executor Pod's logs the following error is seen.

----
13:44:03,501 SEVERE [org.jboss.windup.web.messaging.executor.ExecutorBootstrap] (main) Could not start messaging listener due to: Failed to connect to any server. Servers tried: [http-remoting://192.0.2.4:8080 (java.net.NoRouteToHostException: No route to host)]: javax.naming.CommunicationException: Failed to connect to any server. Servers tried: [http-remoting://192.0.2.4:8080 (java.net.NoRouteToHostException: No route to host)]
[...]
----

*What it means:*

A `NoRouteToHostException` indicates that this Pod isn't able to connect to the {WebName} Pod.

*How to resolve it:*

In a new deployment this is expected, as the executor starts before the {WebName}. Otherwise, examine the {WebName} Pod and resolve any errors seen here. Once the {WebName} is running successfully this error should be resolved.

.Pod reports insufficient resources

After attempting to deploy {WebNameTitle} on OpenShift, the Pod is unable to start, and the following error is seen in the `Events` tab.

[source,options="nowrap"]
----
0/9 nodes are available: 4 Insufficient cpu, 4 MatchNodeSelector, 9 Insufficient memory.
----

*What it means:*

The resource quota for the OpenShift project has been met, and the Pod is unable to obtain the requested resources.

*How to resolve it:*

Perform either of the following:

* Increase the quota for the OpenShift project. For additional information on OpenShift quotas, see link:{OpenShiftDevGuideURL}/compute_resources.html[Quotas and Limit Ranges] and link:{OpenShiftAdminGuideURL}/limits.html[Setting Limit Ranges].
* Reduce the requested resources for the {WebName} OpenShift project. It is recommended to have at least 2 CPUs and 4 GB of memory for the project.

Once the request is within the available quota, attempt the deployment once again.

.Pod takes longer than 600 seconds to become available

After attempting a deployment, the `-deploy` Pods timeout and report the following error.

[source,options="nowrap",subs="+quotes"]
----
error: update acceptor rejected mta-web-console-executor-1: Pods for rc 'mta/<POD_NAME>' took longer than 600 seconds to become available
----

These errors appear after the Pods timeout and are placed into an error state.

*What it means:*

The deployment Pods are unable to successfully launch the Pods.

This error can be caused by a number of sources, with the following being the most common:

* The OpenShift instance is currently out of resources to deploy the Pod in a timely manner.
* The images were unable to be successfully pulled from the registry.

*How to resolve it:*

Attempt the deployment again, and view the logs and events of the non deployment Pods while they are being created. These messages will provide context to the underlying errors resulting in the deployment Pod timeouts.

* To address the first issue reported, where the OpenShift instance is out of resources, follow the instructions in link:{OpenShiftAdminGuideURL}/cluster_capacity.html[Analyzing Cluster Capacity] from the _Cluster Administration_ guide in the OpenShift documentation to determine the cluster capacity. Once the capacity has increased, or there are fewer jobs executing, attempt the deployment once again.

* To address the second issue reported, where the images are unable to be pulled from the registry, link:{OpenShiftInstallConfigGuideURL}/registry/accessing_registry.html[access the registry] to ensure the images are present. This link also includes instructions on examining the logs for the Docker registry, and can be used to troubleshoot the issue further.

== Reporting issues

{ProductName} uses JIRA as its issue tracking system. If you encounter any issues while using the {WebName}, please file a JIRA Issue by following the below instructions.

NOTE: If you do not have one already, you must sign up for a JIRA account in order to create a JIRA issue.

. Open a browser and navigate to the JIRA link:https://issues.jboss.org/secure/CreateIssue!default.jspa[Create Issue] page.
+
If you have not yet logged in, click the *Log In* link at the top right side of the page and enter your credentials.

. Choose the following options and click the *Next* button.

* *Project*: Choose `{ProductName} (WINDUP)`
* *Issue Type*: `Bug`

. On the next screen complete the following fields.

* *Summary*: Enter a brief description of the problem or issue.
* *Environment*: Indicate that this is an OpenShift installation of the {WebName}, and include any environment variables in use with the image.
* *Description*: Provide a detailed description of the issue. Be sure to include any errors encountered and exception traces.
* *Attachment*: Include the logs. At a minimum this should include the logs from each Pod.
+
If the application or archive causing the issue does not contain sensitive information and you are comfortable sharing it with the {ProductShortName} development team, attach it to the issue using the *browse* button.

. Click the *Create* button to create the JIRA issue.
