// Module included in the following assemblies:
// * docs/web-console-guide_5/master.adoc
[id='using_web_console_analyze_apps_{context}']
= Analyzing applications with the {WebName}

You can use the {WebName} to analyze how easily you can migrate applications to your OpenShift environment. To do this, you must create or more projects. Each project is a way to group applications for analysis and specifies the settings to use during the analysis of its applications. The analysis process generates reports that provide information about the difficulty of a migration and any changes that you need to make to your clusters before you migrate them.

Follow these steps to use the {WebName} to analyze your applications and review the results:

. Add a project.
. Add applications to the project.
. Configure the analysis.
. Execute the analysis.
. View the results of the analysis.

[NOTE]
====
Click *Projects* at the top of the {WebName} navigation bar to return to the project list at any time. Visit the help menu for an *About* page and a link to the {ProductShortName} documentation.
====
