// Module included in the following assemblies:
// * docs/web-console-guide_5/master.adoc
[[remove_default_user]]
= Remove the Default {WebNameTitle} User

A default {WebName} user is provided with the {WebName} with the username `mta` and password `password`. When you xref:enable_auth[enable authentication] for the {WebName}, you should remove this user so that the {WebName} can only be accessed by authorized users.

Follow these steps to remove the default {WebName} user.

. Make sure that the {WebName} is xref:starting_console[running].
. Open the Red Hat Single Sign-On administration console.
* For a ZIP installation:
.. Navigate to `\http://localhost:8080/auth/` in a browser.
.. Select *Administration Console* to access the Red Hat Single Sign-On administration console.
* For an OpenShift installation:
.. Navigate to `__OPENSHIFT_URL__/console/project/mta/overview` in a browser.
+
NOTE: If you renamed the OpenShift project when xref:deploy_mta_app_openshift[deploying], replace `mta` with the name of your project.
.. Click the link in the *SSO HTTPS* application and add "/auth" to the end of the URL.
.. Select *Administration Console* to access the Red Hat Single Sign-On administration console.
. Log in with an administrative user's credentials. The default credentials are `admin` and `password`.
. In the upper left corner, select the *mta* realm from the drop down.
. From the left-side navigation menu, select *Users* and then click *View all users*.
. From the *mta* user's row, click *Delete* and confirm.
