// Module included in the following assemblies:
// * docs/web-console-guide_5/master.adoc
[[using_web_console_analyze_apps]]
= Using the {WebNameTitle} to Analyze Applications

In order to use the {WebName} to analyze applications, you must create a project. Each project is a way to group applications for analysis and specifies the settings to use during the analysis of its applications. The analysis process generates reports that provide information about the changes necessary for a migration or modernization effort.

Follow these steps to use the {WebName} to analyze your applications and review the results.

. xref:add_project[Add a project.]
. xref:add_applications[Add applications to the project.]
. xref:analysis_configuration[Specify the analysis configuration.]
. xref:execute[Execute the analysis.]
. xref:view_results[View the results of the analysis.]

// TODO andrea: find a better location for this information? Consider a screenshot of the project list eventually.
[NOTE]
====
Click the *Projects* link at the top of the {WebName} to return to the project list at any time. Visit the help menu for an *About* page and a link to the {ProductShortName} documentation.
====
