[[about_mta]]
= About {ProductName}

[discrete]
== What is {ProductName}?

{ProductName} ({ProductShortName}) is an extensible and customizable rule-based tool that helps simplify migration of Java applications.

{ProductShortName} examines application artifacts, including project source directories and application archives, then produces an HTML report that highlights areas needing changes. {ProductShortName} can be used to migrate Java applications from previous versions of _Red Hat JBoss Enterprise Application Platform_ or from other containers, such as _Oracle(R) WebLogic Server_ or _IBM(R) WebSphere(R) Application Server_.

[discrete]
== How Does {ProductName} Simplify Migration?

{ProductName} looks for common resources and highlights technologies and known trouble spots when migrating applications. The goal is to provide a high-level view into the technologies used by the application and provide a detailed report organizations can use to estimate, document, and migrate enterprise applications to Java EE and Red Hat JBoss Enterprise Application Platform.

ifndef::getting-started-guide[]
[discrete]
== How Do I Learn More?

See the link:{ProductDocGettingStartedGuideURL}[_{GettingStartedBookName}_] to learn more about the features, supported configurations, system requirements, and available tools in the {ProductName}.
endif::getting-started-guide[]
