:toc:
:toclevels: 4
:numbered:

include::topics_5/templates/document-attributes.adoc[]

:imagesdir: topics_5/images
:context: release-notes
:release-notes:

= {ReleaseNotesName}

== Introduction

These release notes describe the new features and changes implemented for the {ProductName} ({ProductShortName}) {ProductVersion} release.

== New Features

=== Rebranding as Migration Toolkit for Applications

In this release, the Red Hat Application Migration Toolkit has been rebranded as the Migration Toolkit for Applications.

=== New migration path for migrating to Apache Camel 3

This release contains a new migration path to support the migration from Apache Camel 2 to Apache Camel 3. The Camel 3 rulesets contain 147 new rules.

== Known {ProductShortName} Issues

You can review known issues for {ProductShortName} here: link:[Open {ProductShortName} issues].

include::topics_5/known_issues.adoc[leveloffset=+2]

== Resolved Issues

At the time of the release the following resolved issues have been identified as important issues worth highlighting. For a full list of all issues resolved in this release, see the link:[{ProductVersion} resolved issues JIRA filter].

include::topics_5/resolved_issues.adoc[leveloffset=+2]
