


[[Dev-Development-Guidelines-and-Conventions]]
=== Development Guidelines and Conventions

* xref:project-source-code-formatting[Project Source Code Formatting]
* xref:source-code-naming-conventions[Source Code Naming Conventions]
* xref:maven-project-naming-conventions[Maven Project Naming Conventions]

[[project-source-code-formatting]]
==== Project Source Code Formatting

All project source code contributed to {ProductShortName} should be formatted using the settings defined in the `Eclipse_Code_Format_Profile.xml` file located in the `ide-config` directory of the {ProductShortName} project.

===== Eclipse IDE

. In Eclipse, choose Windows -> Preferences.
. Expand Java -> Code Style -> Formatter
. Click Import
. Browse to the `Eclipse_Code_Format_Profile.xml` located in the `ide-config` directory of the {ProductShortName} project, then click 'OK'.

===== Netbeans IDE

Use this file to format {ProductShortName} source code: 

http://plugins.netbeans.org/plugin/50877/eclipse-code-formatter-for-java[http://plugins.netbeans.org/plugin/50877/eclipse-code-formatter-for-java] 

===== IntelliJ IDEA

Use this file to format {ProductShortName} source code: 

http://plugins.jetbrains.com/plugin/?id=6546[http://plugins.jetbrains.com/plugin/?id=6546]

[[source-code-naming-conventions]]
==== Source Code Naming Conventions

===== Class Interface and Implementation Names

* Do not name interfaces using the prefix 'I' for interface names. Instead, use a descriptive term for the interface, like `Module.java`.
* The implementation class name should begin with a descriptive name, followed by the interface name, for example, for example `JavaHandlerModule.java`

===== Standard Prefixes and Suffixes

* Append all RuleProvider class names with `RuleProvider`.
* Append all XML rule file names with `.windup.xml`
* Append all Model class names with `Model`.
* All test names should be prefixed with 'Test'.
* Property constants: TBD 

[[maven-project-naming-conventions]]
==== Maven Project Naming Conventions

===== Maven Module Names

The following are not really accurate at this time. This is still TBD! 

* Lowercase with dashes. Start with `windup-`.
* Ruleset add-ons start with `windup-rules-`.

