

[[Rules-Rule-Execution-Lifecycle]]
=== Rule Execution Lifecycle

Rule phases provide a way for rule authors to control the rule lifecycle by specifying the phase in which the rule should execute. {ProductName} executes rules sequentially within rule phases, however, you can also provide more fine-grained control over the order of rule execution within a phase. A rule may specify that one or more rules must be executed before it this rule is run. All named rules will be fired in the order specified before executing the the current rule. A rule may also specify that one or more rules must be executed after it is run. In this case, all named rules will be fired in the order specified after executing the the current rule.

The rule phase and execution order is stored in the associated rule's http://windup.github.io/windup/docs/latest/javadoc/org/jboss/windup/config/metadata/RuleMetadata.html[RuleMetadata].

For a detailed description of {ProductName} rule phases and the order of their execution, see: xref:Rule-Phases[Rule Phases]

==== Set the Rule Execution Phase 

You can set the phase in which the rule executes in one of the following ways. 

* Add the `@RuleMetadata(phase = RulePhase)` annotation to the rule.
* Code the `setPhase(RulePhase)` method in the constructor of the rule.

==== Control the Execution Order Within the Rule Phase

You can also provide more fine-grained control over the order of rule execution within a phase. A rule may specify that one or more rules must be executed before it this rule is run. All named rules will be fired in the order specified before executing the the current rule. A rule may also specify that one or more rules must be executed after it is run. In this case, all named rules will be fired in the order specified after executing the the current rule.

This is done in one of the following ways.

* Add the `@RuleMetadata(after = PreviousRuleProvider, before = NextRuleProvider)` annotation to the rule.
* Use the `addExecuteAfter(NextRuleProvider)` or `addExecuteBefore(PreviousRuleProvider)` methods in the constructor, specifying the rules that should precede or follow this rule.

==== Code Example Using the Annotation Method

The following is an example of a rule that overrides the rule phase and sets the ordering using the `@RuleMetaData` annotation.

[source,java]
----
@RuleMetadata(id = "MyCustomRuleProvider",
            phase = DependentPhase.class,
            after = { MyFirstRuleProvider.class, MySecondRuleProvider.class },
            before = { MyFinalRuleProvider1.class })
public class MyCustomRuleProvider extends AbstractRuleProvider
{
----

==== Code Example Using the Constructor Method


The following example provides the same results using constructor methods.

[source,java]
----
public MyCustomRuleProvider extends AbstractRuleProvider
{
    super(MetadataBuilder.forProvider(MyCustomRuleProvider.class)
                .setPhase(DiscoveryPhase.class)
                .addExecuteAfter({ MyFirstRuleProvider.class, MySecondRuleProvider.class }),
                .addExecuteBefore({MyLastRuleProvider.class}));
}
----

==== Additional Information

For more information about what can be specified in the `@RuleMetadata` annotation, see the http://windup.github.io/windup/docs/latest/javadoc/org/jboss/windup/config/metadata/RuleMetadata.html[RuleMetadata] JavaDoc.

For more information about RuleProvider constructor MetadataBuilder methods, see the http://windup.github.io/windup/docs/latest/javadoc/org/jboss/windup/config/metadata/MetadataBuilder.html[MetadataBuilder] JavaDoc.

For a graphical overview of rule processing, see https://docs.google.com/drawings/d/1IMnds3Qu8Wwcf7_mr7NJ9a3YgtcGJ7dejl09EhWl7Vc/edit[this
diagram].
