


[[Rules-Java-based-Rule-Structure]]
=== Java-based Rule Structure

==== RuleProvider 

{ProductName} rules are based on http://ocpsoft.org/rewrite/[OCPsoft Rewrite], an open source routing and URL rewriting solution for Servlets, Java Web Frameworks, and Java EE. The *rewrite* framework allows you to create rule providers and rules in an easy to read format. 

{ProductShortName} rule add-ons can implement the http://windup.github.io/windup/docs/latest/javadoc/org/jboss/windup/config/RuleProvider.html[RuleProvider] interface or they can extend the http://windup.github.io/windup/docs/latest/javadoc/org/jboss/windup/config/AbstractRuleProvider.html[AbstractRuleProvider] class, the http://windup.github.io/windup/docs/latest/javadoc/org/jboss/windup/config/SingleRuleProvider.html[SingleRuleProvider] class, or the http://windup.github.io/windup/docs/latest/javadoc/org/jboss/windup/config/IteratingRuleProvider.html[IteratingRuleProvider] class. 

* If the rule should run in a phase other than the default http://windup.github.io/windup/docs/latest/javadoc/org/jboss/windup/config/RulePhase.html#MIGRATION_PHASE[MIGRATION_PHASE], you must implement the http://windup.github.io/windup/docs/latest/javadoc/org/jboss/windup/config/RuleProvider.html#getPhase%28%29[getPhase()] method and specify in which {ProductShortName} lifecycle phase the rule should be executed. For more information about rule phases, see xref:Rules-Rule-Execution-Lifecycle[Rule Execution Lifecycle].

* Rules are added in the http://windup.github.io/windup/docs/latest/javadoc/org/jboss/windup/config/RuleProvider.html[getConfiguration(GraphContext context)] method. This method is inherited from the http://ocpsoft.org/rewrite/[OCPsoft Rewrite] interface org.ocpsoft.rewrite.config.ConfigurationProvider. Rules are discussed in more detail below under xref:add-rule-code-structure[Add Rule Code Structure]

* If other rules must execute after or before the rules in this provider, you must provide the list of RuleProvider classes using the http://windup.github.io/windup/docs/latest/javadoc/org/jboss/windup/config/RuleProvider.html#getExecuteBefore%28%29[getExecuteBefore()] or http://windup.github.io/windup/docs/latest/javadoc/org/jboss/windup/config/RuleProvider.html#getExecuteAfter%28%29getExecuteAfter()* methods. 

The following is an example of a simple Java-based rule add-on.

[source,java]
----
public class ExampleRuleProvider extends AbstractRuleProvider
{
    @Override public RulePhase getPhase(){
        return RulePhase.DISCOVERY;
    }

    // @formatter:off
    @Override
    public Configuration getConfiguration(GraphContext context)
    {
        return ConfigurationBuilder.begin()
        .addRule()
        .when(
            // Some implementation of GraphCondition.
            Query.find(...)....
        )
       .perform(
            ...
       );
    }
    // @formatter:on
    // (@formatter:off/on prevents Eclipse from formatting the rules.)
}
----

[[add-rule-code-structure]]
==== Add Rule Code Structure

As mentioned above, individual rules are added to a ruleset in the http://windup.github.io/windup/docs/latest/javadoc/org/jboss/windup/config/RuleProvider.html[getConfiguration(GraphContext context)] method using the http://ocpsoft.org/rewrite/[OCPsoft Rewrite] ConfigurationBuilder class.

Like most rule-based frameworks, {ProductShortName} rules consist of the following:

* Condition: This is the *when(condition)* that determines if the rule should execute.
* Operation: This defines what to *perform()* if the condition is met.
* Otherwise: The *when(condition)* is not met
* Operation: This defines what to *perform()* if the condition is not met.

Rules must define the condition, or _when_, and an operation, or _perform_. However, the otherwise and remainder are optional.

===== when()

[source,java]
----
.when(Query.fromType(XmlMetaFacetModel.class))
----

The `.when()` clause of a rule typically queries the graph using the http://windup.github.io/windup/docs/latest/javadoc/org/jboss/windup/config/query/Query.html[Query] API. Results of the query are put on variables stack (`Variables`), many times indirectly through the querying API.

The `.when()` clause can also subclass http://windup.github.io/windup/docs/latest/javadoc/org/jboss/windup/config/condition/GraphCondition.html[GraphCondition]. The http://windup.github.io/windup/docs/latest/javadoc/org/jboss/windup/config/query/Query.html[Query] class extends http://windup.github.io/windup/docs/latest/javadoc/org/jboss/windup/config/condition/GraphCondition.html[GraphCondition] and is  a convenient way to create a condition. You can also use multiple conditions within one when() call using and().

Example: 
[source,java]
----
.when(Query.fromType(XmlMetaFacetModel.class).and(Query...))
----

One last but important feature is the ability to use https://github.com/tinkerpop/gremlin/wiki[Gremlin] queries. See the http://gremlindocs.com/[Gremlin Documentation] reference manual for more information.


===== perform()

[source,java]
----
.perform(
   new AbstractIterationOperation<XmlMetaFacetModel>(XmlMetaFacetModel.class, "xml")
   {
      public void perform(GraphRewrite event, EvaluationContext context, XmlMetaFacetModel model)
      {
         // for each model, do something
      }
   }
)
----

The `.perform()` clause of the rule typically iterates over the items of interest, such as Java and XML files and querying services, processes them, and writes the findings into the graph.

For that, various operations are available, which are subclasses of http://windup.github.io/windup/docs/latest/javadoc/org/jboss/windup/config/operation/GraphOperation.html[GraphOperation]. You can also implement your own operations. 


There are several convenient implementations for constructs like iteration (`Iteration`).

====== Iteration

[source,java]
----
.perform(
    Iteration.over(XmlMetaFacetModel.class, "xmlModels").as("xml")
    .when(...)
    .perform(
        new AbstractIterationOperation<XmlMetaFacetModel>(XmlMetaFacetModel.class, "xml"){
            public void perform(GraphRewrite event, EvaluationContext context, XmlMetaFacetModel xmlFacetModel)
            {
            }
        })
    .otherwise(
        new AbstractIterationOperation<XmlMetaFacetModel>(XmlMetaFacetModel.class, "xml"){
            public void perform(GraphRewrite event, EvaluationContext context, XmlMetaFacetModel payload)
                { ... }
        })
    .endIteration()
----

====== Nested iterations

An iteration is also an operation, so anywhere an operation is expected, you can use the Iteration. If the Iteration is placed within the perform method of another Iteration, it is called nested iteration.

The following is an example of a nested iteration. 
[source,java]
----
.addRule()
     .when(...)
     .perform(
     Iteration.over("list_variable").as("single_var")
       .perform(
         Iteration.over("single_var") //second iteration
           .perform(...).endIteration()
     )
     .endIteration()
);
----

====== otherwise

As previously mentioned, {ProductShortName} rules are based on http://ocpsoft.org/rewrite/[OCPsoft Rewrite]. The `.otherwise()` clause allows you to perform something if the condition specified in `.when()` clause is not matched. For more information, see http://ocpsoft.org/rewrite/[OCP Rewrite web].

The following is an example of an otherwise operation.
[source,java]
----
.otherwise(
   new AbstractIterationOperation<XmlMetaFacetModel>(XmlMetaFacetModel.class, "xml")
   {
      public void perform(GraphRewrite event, EvaluationContext context, XmlMetaFacetModel model)
      {
         // for each model, do something altenate
      }
   }
)
----

===== Where

The `where()` clause is used to provide information about used parameters within the rule. So for example if you have used a parameter in some condition like for example `JavaClass.references("{myMatch}")`, you may use the where clause to specify what the `myMatch` is like `.where("myMatch").matches("java.lang.String.toString\(.*\)")`. 

The following is an example 
[source,java]
----
.when(JavaClass.references("{myMatch}").at(TypeReferenceLocation.METHOD))
.perform(...)
.where("myMatch").matches("java.lang.String.toString\(.*\)")
----

+
Please note that within the where clause the regex is used in contrast to JavaClass.references() where a windup specific syntax is expected.

===== Metadata

Rules can specify metadata. Currently, the only appearing in some rules,
and not actually used, is `RuleMetadata.CATEGORY`.

[source,java]
----
.withMetadata(RuleMetadata.CATEGORY, "Basic")
----

`.withMetadata()` is basically putting key/value to a
`Map<Object, Object>`.

==== Available utilities

For a list of what key services and constructs can be used in the rule,
see xref:Rules-Available-Rules-Utilities[Available Rules Utilities].

===== Variable stack
The communication between the conditions and operations is done using the variable stack that is filled with the output of the condition/s and then given to the Iteration to be processed. 
Within conditions, you can specify the name of the result iterable that is saved in the stack using `as()` method, the iteration can specify the iterable to iterate over using the `over()` method and even specify the name of for each processed single model of the result being processed.
Example: 

[source,java]
----
.addRule()
     .when(Query...as("result_list"))
     .perform(
     Iteration.over("result_list").as("single_var")
          ...
     )
);
----

The varstack may be accesed even from the second condition in order to narrow the result of the previous one. After that the iteration may choose which result it wants to iterate over (it is even possible to have multiple iterations listed in the perform, each of which may access different result saved in the variable stack).

[source,java]
----
.addRule()
     .when(Query...as("result_list").and(Query.from("result_list")....as("second_result_list")))
     .perform(
     Iteration.over("second_result_list")
          ...
     )
);
----
