[[rule_story_points]]
= Rule Story Points

== What are Story Points?

_Story points_ are an abstract metric commonly used in Agile software development to estimate the _level of effort_ needed to implement a feature or change.

{ProductName} uses story points to express the level of effort needed to migrate particular application constructs, and the application as a whole. It does not necessarily translate to man-hours, but the value should be consistent across tasks.

== How Story Points are Estimated in Rules

Estimating the level of effort for the story points for a rule can be tricky. The following are the general guidelines {ProductShortName} uses when estimating the level of effort required for a rule.

[cols="25%,15%,60%", options="header"]
|====
|Level of Effort
|Story Points
|Description

|Information
|0
|An informational warning with very low or no priority for migration.

|Trivial
|1
|The migration is a trivial change or a simple library swap with no or minimal API changes.

|Complex
| 3
|The changes required for the migration task are complex, but have a documented solution.

|Redesign
|5
|The migration task requires a redesign or a complete library change, with significant API changes.

|Rearchitecture
|7
|The migration requires a complete rearchitecture of the component or subsystem.

|Unknown
|13
|The migration solution is not known and may need a complete rewrite.
|====

== Task Severity

In addition to the level of effort, you can categorize migration tasks to indicate the severity of the task. The following categories are used to indicate whether a task must be completed or can be postponed.

Mandatory:: The task must be completed for a successful migration. If the changes are not made, the resulting application will not build or run successfully. Examples include replacement of proprietary APIs that are not supported in the target platform.

Optional:: If the migration task is not completed, the application should work, but the results may not be the optimal. If the change is not made at the time of migration, it is recommended to put it on the schedule soon after migration is completed. An example of this would be the upgrade of EJB 2.x code to EJB 3.

ifdef::rules-development-guide[]
For more information on categorizing tasks, see xref:rule_categories[Using Custom Rule Categories].
endif::rules-development-guide[]

ifndef::rules-development-guide[]
For more information on categorizing tasks, see link:{ProductDocRulesGuideURL}#rule_categories[Using Custom Rule Categories] in the _{RulesDevBookName}_.
endif::rules-development-guide[]
