[[about_the_plugin]]
= About the {PluginNameTitle}

The {PluginName} for {ProductName} provides assistance directly in Eclipse and Red Hat CodeReady Studio for developers making changes for a migration or modernization effort. It analyzes your projects using {ProductShortName}, marks migration issues in the source code, provides guidance to fix the issues, and offers automatic code replacement when possible.


A {ProductShortName} extension for Visual Studio Code and Eclipse Che is available in this release.
// Future commitments to releasing unfinished components should not be included in the documentation. The inclusion of the following statement has been explicitly requested by PM, and is therefore included anyway:
The extension is available as a Minimum Viable Product and will be fully documented and supported in a future Release of {ProductShortName}.
For more information, about link:https://marketplace.visualstudio.com/items?itemName=redhat.rhamt-vscode-extension[the extension] visit the Visual Studio Markteplace.

ifndef::plugin-guide[]
For more information on using the {PluginName}, see the {ProductShortName} link:{ProductDocPluginGuideURL}[_{PluginBookName}_].
endif::plugin-guide[]
