// Module included in the following assemblies:
//
// * docs/rules-development-guide/master.adoc
// * docs/getting-started-guide/master.adoc

:_content-type: CONCEPT
[id="about-rules_{context}"]
= About {ProductShortName} rules

The {ProductName} ({ProductShortName}) contains rule-based migration tools (analyzers) that analyze the APIs, technologies, and architectures used by the applications you plan to migrate. {ProductShortName} uses analyzer rules internally to extract files from archives, decompile files, scan and classify file types, analyze XML and other file content, analyze the application code, and build the reports.

{ProductShortName} builds a data model based on the rule execution results and stores component data and relationships in a graph database, which can then be queried and updated as needed by the migration rules and for reporting purposes.

{ProductShortName} rules use the following rule pattern:

----
when(condition)
 message(message)
 tag(tags)
----

Although {ProductShortName} provides a comprehensive set of standard migration rules out-of-the-box, you can create your own analyzer rules as well. You can use custom rules to identify use of custom libraries or other components that might not be covered by the provided out-of-the-box ruleset.

ifndef::rules-development-guide[]
If you plan to write your own custom rules, see the {ProductDocRulesGuideURL}[_{RulesDevBookName}_] for detailed instructions.
endif::rules-development-guide[]
