// Module included in the following assemblies:
//
// * docs/rules-development-guide/master.adoc
// * docs/getting-started-guide/master.adoc

:_content-type: CONCEPT
[id="about-rules_{context}"]
= The {ProductShortName} rules

The {ProductFullName} contains rule-based migration tools (analyzers) that you can use to analyze the application user interfaces (APIs), technologies, and architectures used by the applications you plan to migrate. {ProductShortName} analyzer rules use the following rule pattern:

----
when(condition)
 message(message)
 tag(tags)
----


You can use the {ProductShortName} rules internally to perform the following tasks:

* Extract files from archives.
* Decompile files.
* Scan and classify file types.
* Analyze XML and other file content.
* Analyze the application code.
* Build the reports.

{ProductShortName} builds a data model based on the rule execution results and stores component data and relationships in a graph database. This database can then be queried and updated as required by the migration rules and for reporting purposes.


[NOTE]
====
You can create your own custom analyzer rules. You can use custom rules to identify the use of custom libraries or other components that might not be covered by the provided standard migration rules.

ifndef::rules-development-guide[]
For instructions on how to write custom rules, see [_{RulesDevBookName}_].
endif::rules-development-guide[]
====

_content-type: PROCEDURE
[id="open-yaml-rule_{context}"]
= Using existing YAML rules

You can open and edit existing {ProductShortName} YAML-based rule. This assumes that you have already installed {ProductShortName}. See link:{ProductDocUserGuideURL}/index#installing_and_running_the_cli[Installing and running the CLI] in the _{UserCLIBookName}_ for installation instructions.

To access the repository of YAML rule files, you must fork and clone an existing rule from the Red Hat Konveyor rules repository.

[id="yaml-rules-repository_{context}"]
== Replicate YAML rules library

You can fork and clone the {ProductShortName} YAML rule files on your local machine.

The YAML-based rules are located on GitHub at the following location: link:https://github.com/konveyor/rulesets/tree/main/default/generated[https://github.com/konveyor/rulesets/tree/main/default/generated].

The rules are numbered and grouped according to target platform. When you create a new rule, it is helpful to find a rule that is similar to the one you need and use it as a starting template. 

New YAML rules are continuously added, so it is a good idea to check back frequently to review the updates.
