// Module included in the following assemblies:
//
// * docs/rules-development-guide/master.adoc

:_content-type: REFERENCE
[id="analyzer-rules_{context}"]
= Analyzer rules

== YAML rule structure

A YAML rule consists of metadata, conditions and actions.

=== Metadata

General information

Needs example

==== Labels

key=val pairs
Subdomain-prefixed
Empty values
Reserved labels
`--label-selector` option - filter in/filter out
Dependency labels

=== Actions

`message` actions
Message examples

`tag` actions
Tag examples

=== `when` block

One condition; may have nested conditions within

==== Provider conditions

Instructs to invoke a provider and to use its 'capabilities'

===== Builtin provider
Capabilities:

`file` - enables the provider to find files in the source code that match a given pattern

`filecontent` - enables the provider to search for content that matches a given pattern

`xml` - enables the provider to query XPath expressions on a list of provided XML files; takes 2 input parameters

`json` - enables the provider to query XPath expressions on a list of provided JSON files; takes xpath as input

hasTags - enables the provider to query application tags

===== Java provider

Capabilities:

`referenced` - enables the provider to find references in the source code; takes two input parameters, `pattern` and `location`

list of supported locations

`dependency`

//Needs info

===== Go provider

Works with Golang source code

Capabilities:

`referenced` - enables the provider to find references in the source code

`dependency` - enables the provider to find dependencies for an application

=== Logical conditions

==== And

Logical 'and' operation
Nested conditions

Example

==== Or

Logical 'or' operation

== Rulesets

Each in its own directory; a `ruleset.yaml` file at the directory root

Ruleset labels inherited by all its rules


== Creating YAML rules

=== Steps of creating a YAML rule

//Needs info

=== Directory structure for YAML rules

//Same as for XML? Needs info

=== Installing rules

//Same as for XML - place into the appropriate directory? Needs info

== Predefined rules

//Will there be ready-made rules? Needs info

== Testing rules

//Needs info

== Viewing reports

//Needs info

