// Module included in the following assemblies:
//
// * docs/cli-guide/master.adoc

:_content-type: PROCEDURE
[id="cli-run_{context}"]
= Running the {CLINameTitle}

You can run {ProductShortName} against your application.

.Procedure

. Open a terminal and navigate to the `<{ProductShortName}_HOME>/bin/` directory.
. Execute the `windup-cli` script, or `windup-cli.bat` for Windows, and specify the appropriate arguments:
+
[source,terminal,subs="attributes+"]
----
$ ./{LC_PSN}-cli --input /path/to/jee-example-app-1.0.0.ear \
    --output /path/to/output --source weblogic --target eap:6 \
    --packages com.acme org.apache
----
+
* `--input`: The application to be evaluated.
* `--output`: The output directory for the generated reports.
* `--source`: The source technology for the application migration.
* `--target`: The target technology for the application migration.
* `--packages`: The packages to be evaluated. This argument is highly recommended to improve performance.

. Access the report.

[id="command-examples_{context}"]
== {ProductShortName} command examples

[discrete]
=== Running {ProductShortName} on an application archive

The following command analyzes the `com.acme` and `org.apache` packages of the link:https://github.com/windup/windup/blob/master/test-files/jee-example-app-1.0.0.ear[jee-example-app-1.0.0.ear] example EAR archive for migrating from JBoss EAP 5 to JBoss EAP 7:

[source,terminal,subs="attributes+"]
----
$ <{ProductShortName}_HOME>/bin/windup-cli \
    --input /path/to/jee-example-app-1.0.0.ear \
    --output /path/to/report-output/ --source eap:5 --target eap:7 \
    --packages com.acme org.apache
----

[discrete]
=== Running {ProductShortName} on source code

The following command analyzes the `org.jboss.seam` packages of the link:https://github.com/windup/windup/tree/master/test-files/seam-booking-5.2[seam-booking-5.2] example source code for migrating to JBoss EAP 6.

[source,terminal,subs="attributes+"]
----
$ <{ProductShortName}_HOME>/bin/windup-cli --sourceMode --input /path/to/seam-booking-5.2/ \
    --output /path/to/report-output/ --target eap:6 --packages org.jboss.seam
----

[discrete]
=== Running cloud-readiness rules

The following command analyzes the `com.acme` and `org.apache` packages of the link:https://github.com/windup/windup/blob/master/test-files/jee-example-app-1.0.0.ear[jee-example-app-1.0.0.ear] example EAR archive for migrating to JBoss EAP 7. It also evaluates for cloud readiness:

[source,terminal,subs="attributes+"]
----
$ <{ProductShortName}_HOME>/bin/windup-cli --input /path/to/jee-example-app-1.0.0.ear \
    --output /path/to/report-output/ \
    --target eap:7 --target cloud-readiness --packages com.acme org.apache
----

[discrete]
=== Overriding {ProductShortName} properties

To override the default _Fernflower_ decompiler, pass the `-Dwindup.decompiler` argument on the command line. For example, to use the _Procyon_ decompiler, use the following syntax:

[source,terminal,subs="attributes+"]
----
$ <{ProductShortName}_HOME>/bin/windup-cli -Dwindup.decompiler=procyon \
    --input <INPUT_ARCHIVE_OR_DIRECTORY> --output <OUTPUT_REPORT_DIRECTORY> \
    --target <TARGET_TECHNOLOGY> --packages <PACKAGE_1> <PACKAGE_2>
----

[id="cli-bash-completion_{context}"]
== {ProductShortName} {CLINameTitle} Bash completion

The {ProductShortName} {CLIName} provides an option to enable Bash completion for Linux systems, allowing the {ProductShortName} command-line arguments to be auto completed by pressing the Tab key when entering the commands. For instance, when Bash completion is enabled, entering the following displays a list of available arguments.

[source,terminal,subs="attributes+"]
----
$ <{ProductShortName}_HOME>/bin/{LC_PSN}-cli [TAB]
----

[discrete]
[id="bash-completion-temporary_{context}"]
=== Enabling Bash completion

To enable Bash completion for the current shell, execute the following command:

[source,terminal,subs="attributes+"]
----
$ source <{ProductShortName}_HOME>/bash-completion/windup-cli
----

[discrete]
[id="bash-completion-persistent_{context}"]
=== Enabling persistent Bash completion

The following commands allow Bash completion to persist across restarts:

* To enable Bash completion for a specific user across system restarts, include the following line in that user's `~/.bashrc` file.
+
[source,terminal,subs="attributes+"]
----
source <{ProductShortName}_HOME>/bash-completion/windup-cli
----

* To enable Bash completion for all users across system restarts, copy the {ProductName} {CLIName} Bash completion file to the `/etc/bash_completion.d/` directory as the root user.
+
[source,terminal,subs="attributes+"]
----
# cp <{ProductShortName}_HOME>/bash-completion/windup-cli /etc/bash_completion.d/
----

[id="accessing-help_{context}"]
== Accessing {ProductShortName} help

To see the complete list of available arguments for the `windup-cli` command, open a terminal, navigate to the `<{ProductShortName}_HOME>` directory, and execute the following command:

[source,terminal,subs="attributes+"]]
----
$ <{ProductShortName}_HOME>/bin/windup-cli --help
----
