// Module included in the following assemblies:
//
// * docs/web-console-guide/master.adoc

:_content-type: PROCEDURE
[id="configuring-web-console-authentication-for-linux-windows-macos_{context}"]
= Configuring authentication for the {WebName} on Linux, Windows, or macOS

You can configure the {WebName} to require authentication for access. To  enable authentication, you have to install Red Hat Single Sign-On (SSO).

[discrete]
[id="enabling-authentication_{context}"]
== Enabling authentication

.Procedure

. Adjust the port number that the Red Hat SSO server opens to avoid conflicts with the port that the {WebName} uses by entering the following:
+
** For Linux and macOS:
+
----
$ ./standalone.sh -Djboss.socket.binding.port-offset=<offset_value>
----
** For Windows:
+
----
> ...\bin\standalone.bat -Djboss.socket.binding.port-offset=<offset_value>
----

. Open the Red Hat SSO administration console from `\http://localhost:8180`:
* Username: `admin`
* Password: `admin`
. Add a realm named *{LC_PSN}*.
. In the realm, create a client named *{LC_PSN}-web*.
. Check that *Access Type* is set to `public`.
. Set *Valid Redirect URIs* to `\http://localhost:8080/windup-ui/*`.
. Set *Web Origins* to `+*+` and click *Save*.
. Create a role named *user*.
. Create a user with any name.
. Set the credentials of the user, disable *Temporary*, and assign the role "user" to the user.
. Switch the {WebName} to *Authentication required* mode by doing the following:
.. Export the following ENV variables:
** For Linux and macOS:
+
----
export SSO_AUTH_SERVER_URL=http://localhost:8180/auth
export SSO_REALM=windup
export SSO_SSL_REQUIRED=EXTERNAL
export SSO_CLIENT_ID=windup-web
----
** For Windows:
+
----
set SSO_AUTH_SERVER_URL=http://localhost:8180/auth
set SSO_REALM=windup
set SSO_SSL_REQUIRED=EXTERNAL
set SSO_CLIENT_ID=windup-web
----
+
[NOTE]
====
Environment variables that are set by the `set` command in CMD are local, available to the current CMD session only. Use the Windows Control Panel to permanently set the environment variables.
====

.. Run the following script:
** For Linux and macOS:
+
----
$ <MTR_HOME>/switch_to_authentication_required.sh
----
** For Windows:
+
----
C:\<MTR_HOME>\switch_to_authentication_required.bat
----
. Start the {WebName} by entering the following:
** For Linux and macOS:
+
----
$ <MTR_HOME>/run_windup.sh
----
** For Windows:
+
----
C:\<MTR_HOME>\run_windup.bat
----
. Open the browser at `\http://localhost:8080/windup-ui`.

[discrete]
[id="disabling-authentication_{context}"]
== Disabling authentication

.Procedure
. Run the following script:
** For Linux and macOS:
+
----
$ <MTR_HOME>/switch_to_automatic_authentication.sh
----
** For Windows:
+
----
C:\<MTR_HOME>\switch_to_automatic_authentication.bat
----
