// Module included in the following assemblies:
//
// * docs/rules-development-guide/master.adoc

:_content-type: PROCEDURE
[id="create-first-yaml-rule_{context}"]
= Creating your first YAML rule

This section guides you through the process of creating and testing your first {ProductShortName} YAML-based rule. This assumes that you have already installed {ProductShortName}. See link:{ProductDocUserGuideURL}/index#installing_and_running_the_cli[Installing and running the CLI] in the _{UserCLIBookName}_ for installation instructions.

In this example, you will write a rule to discover instances where an application defines a jboss-web.xml file containing a `<class-loading>` element and to provide a link to the documentation that describes how to migrate the code.

[id="creating-directory-structure-for-the-rule_{context}"]
== Creating a directory structure for the rule

Create a directory structure to contain your first rule and the data file to use for testing.

[options="nowrap",subs="attributes+"]
----
$ mkdir /home/<USER>/rules/
$ mkdir /home/<USER>/data/
----

[id="mta-creating-data-to-test-the-rule_{context}"]
== Creating data to test the rule

. Create data to test the rule:
+
[options="nowrap",subs="attributes+"]
----
touch /home/<USER>/data/jboss-web.xml
----

. Copy in the following content in the jboss-web.xml file we created:
+
[options="nowrap",subs="attributes+"]
----
<!DOCTYPE jboss-web PUBLIC "-//JBoss//DTD Web Application 4.2//EN" "http://www.jboss.org/j2ee/dtd/jboss-web_4_2.dtd">
<jboss-web>
    <class-loading java2ClassLoadingCompliance="false">
        <loader-repository>
            seam.jboss.org:loader=@projectName@
            <loader-repository-config>java2ParentDelegation=false</loader-repository-config>
        </loader-repository>
    </class-loading>
</jboss-web>
----

[id="mta-creating-the-rule_{context}"]
== Creating the rule

MTA YAML-based rules use the following rule pattern:

[options="nowrap",subs="attributes+"]
----
when(condition)
  perform(action)
----

.Procedure

. Create a YAML file in the directory you created with the following contents:
+
[options="nowrap",subs="attributes+"]
----
- ruleID: <UNIQUE_RULE_ID> <1>
  description: <DESCRIPTION> <2>
  when:
    <CONDITION(S)> <3>
  message: <MESSAGE> <4>
  labels: <LABELS> <5>
  effort: <EFFORT> <6>
  links:
  - <LINKS> <7>
----
+
<1> Unique ID for your rule, for instance, `jboss5-web-class-loading`
<2> Text description that describes the rule
<3> Complete the `when` block specifying one or more conditions:
.. Use the `builtin` provider’s XML capability because this rule checks for a match in an XML file.
.. To match on the `class-loading` element that is a child of `jboss-web`, use the XPath expression `jboss-web/web-loading` as an XML query. In this case, you need just one condition:
+
[options="nowrap",subs="attributes+"]
----
when:
  builtin.xml:
    xpath: jboss-web/class-loading
----
<4> Helpful message explaining the migration issue. The message is generated in the report when the rule matches. For example:
+
[options="nowrap",subs="attributes+"]
----
message: The class-loading element is no longer valid in the jboss-web.xml file.
----
<5> List of string labels for the rule
<6> Number of expected story points to fix this issue
<7> One or more hyperlinks pointing to documentation around the migration issues that you find
+
[options="nowrap",subs="attributes+"]
----
links:
- url: https://access.redhat.com/documentation/en-US/JBoss_Enterprise_Application_Platform/6.4/html-single/Migration_Guide/index.html#Create_or_Modify_Files_That_Control_Class_Loading_in_JBoss_Enterprise_Application_Platform_6
  title: Create or Modify Files That Control Class Loading in JBoss EAP 6
----
+
The rule is now complete and looks similar to the following:
+
[options="nowrap",subs="attributes+"]
----
- ruleID: jboss5-web-class-loading
  description: Find class loading element in JBoss XML file.
  when:
    builtin.xml:
      xpath: jboss-web/class-loading
  message: The class-loading element is no longer valid in the jboss-web.xml file.
  effort: 3
  links:
  - url: https://access.redhat.com/documentation/en-US/JBoss_Enterprise_Application_Platform/6.4/html-single/Migration_Guide/index.html#Create_or_Modify_Files_That_Control_Class_Loading_in_JBoss_Enterprise_Application_Platform_6
    title: Create or Modify Files That Control Class Loading in JBoss EAP 6
----

[id="mta-installing-the-rule_{context}"]
== Installing the rule

.Procedure
. Copy the rule file into the rules directory.
. Point the CLI to the rules directory:
+
[options="nowrap",subs="attributes+"]
----
–rules /home/<USER>/rules/
----

[id="mta-testing-the-rule_{context}"]
== Testing the rule

.Procedure
To test the rule, point the input to test data you created and pass the rule using the rules option in MTA CLI:
+
[options="nowrap",subs="attributes+"]
----
mta-cli analyze --input /home/<USER>/data/ --output /home/<USER>/output/ --rules /home/<USER>/rules/
----

[id="mta-reviewing-the-report_{context}"]
== Reviewing the report

Review the report to be sure that it provides the expected results.

.Procedure

. Open `/home/<USER_NAME>/output/static-report/index.html` in a web browser.
. Verify that the rule is executed. See that the issue is generated for rule ID `jboss5-web-class-loading`.









