// Module included in the following assemblies:
//
// * docs/rules-development-guide/master.adoc

:_content-type: PROCEDURE
[id="create-basic-yaml-rule_{context}"]
= Creating a basic XML rule

This section describes how to create an {ProductShortName} YAML rule. This assumes that you already have {ProductShortName} installed. See the {ProductShortName} {ProductDocUserGuideURL}[_{UserCLIBookName}_] for installation instructions.

[id="create-basic-yaml-rule-template_{context}"]
== Creating a basic YAML rule template

{ProductShortName} YAML-based rules have the following basic structure:

[source,terminal]
----
when(condition)
 message(message)
 tag(tags)
----
.Procedure

Create a file containing the basic syntax for YAML rules as follows:

[source,terminal]
----
- category: mandatory
  description: |
   <DESCRIPTION TITLE>
   <DECRIPTION TEXT>
  effort: <EFFORT>
  labels:
  - konveyor.io/source=<SOURCE_TECH>
  - konveyor.io/target=<TARGET_TECH>
  links:
 - url: <HYPERLINK>
   title: <HYPERLINK_TITLE>
  message: <MESSAGE>
  ruleID: <RULE_ID>
  when:
----

[id="create-basic-yaml-ruleset-template_{context}"]
== Creating a basic YAML ruleset template

{ProductShortName} does not require every rule file to belong to a ruleset. However, if you want to group multiple similar rules, you can create a ruleset for them by placing their files in a directory and creating a `ruleset.yaml` file at the directory's root. When you pass this directory as input to the {ProductShortName} {CLIName} using the `--rules` option, {ProductShortName} treats all the files in the directory as belonging to the ruleset defined in the `ruleset.yaml` file.

.Procedure

Create a template for ruleset.yaml files if you do wish to pass the entire directory via `--rules` option:

[source,terminal]
----
name: "Name of the ruleset" <1>
description: "Description of the ruleset"
labels: <2>
  - key=val
----
<1> The name must be unique within the provided rulesets.

<2> Ruleset labels are inherited by all rules that belong to the ruleset.

[id="create-yaml-rule_{context}"]
== Creating a basic YAML rule

Each rule file contains one or more YAML rules. Every rule comprises metadata, conditions and actions.

=== Creating a `when` condition

The `when` condition of a YAML rule can be `provider`, `and` or `or`.

==== Creating a `provider` condition
A provider condition is used to invoke a certain capability of a language provider (See provider condition for background information). In general, it has the format - <provider_name>.<capability>. The condition also has inner fields to specify details about a search. Depending on the provider used, and the capability invoked, the condition and its inner fields can be constructed differently.

|===
|Provider Name |Capabilities |Description

.2+.^|`java`
|`referenced`
|Finds references of a pattern with an optional code location for detailed searches

|`dependency`
|Checks whether the application has a given dependency

.5+.^|`builtin`
|`xml`
|Searches XML files using XPath queries

|`json`
|Searches JSON files using jsonpath queries
|`filecontent`
|Searches content in regular files using RegEx patterns
|`file`
|Finds files with names matching a given pattern
|`hasTags`
|Checks whether a tag is created for the application through a tagging rule

.2+.^|go
|`referenced`
|Finds references of a pattern
|`dependency`
|Checks whether app has a given dependenc
|===








