

 

:imagesdir: images

[[Dev-Create-Your-First-Java-based-Rule-Add-on]]
=== Create Your First Java-based Rule Add-on

==== Overview 

This topic guides you through the process of creating and testing your first {ProductShortName} Java rule-addon using Red Hat JBoss Developer Studio.

As you create your first rule, refer to the http://windup.github.io/windup/docs/latest/javadoc[{ProductShortName} JavaDoc] for valid syntax. 

Java-based rule construction is covered in more detail here: xref:Rules-Create-a-Basic-Java-based-Rule-Add-on[Create a Basic Java-based Rule Add-on].

==== Rule Example Description

In this example, you write a ruleset to discover instances where an application Java file uses the proprietary servlet annotations. The ruleset adds the following rules.

* Find Java classes that reference the `@ProprietaryServlet` annotation and provide a hint to replace it with the standard Java EE @WebServlet annotation.
* Find Java classes that reference the `@ProprietaryInitParam`annotation and provide a hint to replace it with the standard Java EE @WebServlet annotation.

You will also provide a data file to test the rule.

==== Create the Maven Project

. Choose `File` --> `New` --> `Maven Project`.
. Check `Create a simple project (skip archetype selection) and leave `Use the default Workspace location` checked, then click `Next`.
. In the `New Maven Project` dialog, enter the following values:
+
[options="nowrap"]
----
Group Id: org.jboss.windup.rules.examples
Artifact Id: proprietary-annotation-example
Version: 1.0.0-SNAPSHOT
Packaging: jar
Name: Proprietary Annotation Example
Description: Rule that finds a proprietary annotation and provides recommendations
----

==== Configure the Maven POM for {ProductShortName} 

. In JBoss Developer Studio, open the project `pom.xml` file and click on the `pom.xml` tab view.
. The XML below contains the properties, dependencies, and plug-ins needed to build a Java-based rule add-on. Copy it into the `pom.xml` file after the `<description>` and before the final closing `</project>' element.
+
[source,xml,options="nowrap"]
----
<properties>
    <windup.scm.connection>scm:git:https://github.com/windup/windup-rulesets.git</windup.scm.connection>
    <windup.developer.connection>scm:git:git@github.com:windup/windup-rulesets.git</windup.developer.connection>
    <windup.scm.url>http://github.com/windup/windup-rulesets</windup.scm.url>

    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.source>1.7</maven.compiler.source>
    <maven.compiler.target>1.7</maven.compiler.target>
    <version.windup>2.5.0-SNAPSHOT</version.windup>
</properties>

<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>org.jboss.windup</groupId>
            <artifactId>windup-bom</artifactId>
            <version>${version.windup}</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
    </dependencies>
</dependencyManagement>

<dependencies>
    <!-- Windup deps -->
    <dependency>
        <groupId>org.jboss.windup.graph</groupId>
        <artifactId>windup-graph</artifactId>
        <classifier>forge-addon</classifier>
        <scope>provided</scope>
    </dependency>
    <dependency>
        <groupId>org.jboss.windup.config</groupId>
        <artifactId>windup-config</artifactId>
        <classifier>forge-addon</classifier>
        <scope>provided</scope>
    </dependency>
    <dependency>
        <groupId>org.jboss.windup.config</groupId>
        <artifactId>windup-config-xml</artifactId>
        <classifier>forge-addon</classifier>
        <scope>provided</scope>
    </dependency>
    <dependency>
        <groupId>org.jboss.windup.utils</groupId>
        <artifactId>windup-utils</artifactId>
        <classifier>forge-addon</classifier>
        <scope>provided</scope>
    </dependency>
    <dependency>
        <groupId>org.jboss.windup.reporting</groupId>
        <artifactId>windup-reporting</artifactId>
        <classifier>forge-addon</classifier>
        <scope>provided</scope>
    </dependency>

    <!-- Windup Rules Base -->
    <dependency>
        <groupId>org.jboss.windup.rules.apps</groupId>
        <artifactId>windup-rules-base</artifactId>
        <classifier>forge-addon</classifier>
    </dependency>

    <!-- Other rulesets. -->
    <dependency>
        <groupId>org.jboss.windup.rules.apps</groupId>
        <artifactId>windup-rules-java</artifactId>
        <classifier>forge-addon</classifier>
        <scope>provided</scope>
    </dependency>
    <dependency>
        <groupId>org.jboss.windup.rules.apps</groupId>
        <artifactId>windup-rules-java-ee</artifactId>
        <classifier>forge-addon</classifier>
        <scope>provided</scope>
    </dependency>
    <dependency>
        <groupId>org.jboss.windup.rules.apps</groupId>
        <artifactId>windup-rules-java-project</artifactId>
        <classifier>forge-addon</classifier>
        <scope>provided</scope>
    </dependency>

    <dependency>
        <groupId>org.jboss.forge.furnace.container</groupId>
        <artifactId>cdi-api</artifactId>
        <scope>provided</scope>
    </dependency>
    <dependency>
        <groupId>org.jboss.forge.furnace.container</groupId>
        <artifactId>cdi</artifactId>
        <classifier>forge-addon</classifier>
        <scope>provided</scope>
    </dependency>

    <!-- Test dependencies -->
    <dependency>
        <groupId>org.jboss.forge.furnace.test</groupId>
        <artifactId>furnace-test-harness</artifactId>
        <scope>test</scope>
    </dependency>
    <dependency>
        <groupId>org.jboss.forge.furnace.test</groupId>
        <artifactId>arquillian-furnace-classpath</artifactId>
        <scope>test</scope>
    </dependency>

    <dependency>
        <groupId>junit</groupId>
        <artifactId>junit</artifactId>
        <version>4.11</version>
        <scope>test</scope>
    </dependency>

    <dependency>
        <groupId>org.jboss.windup.exec</groupId>
        <artifactId>windup-exec</artifactId>
        <classifier>forge-addon</classifier>
        <scope>test</scope>
    </dependency>
</dependencies>

<build>
    <plugins>
        <!-- This plugin makes this artifact a Forge addon. -->
        <plugin>
            <artifactId>maven-jar-plugin</artifactId>
            <version>2.5</version>
            <executions>
                <execution>
                    <id>create-forge-addon</id>
                    <phase>package</phase>
                    <goals>
                        <goal>jar</goal>
                    </goals>
                    <configuration>
                        <classifier>forge-addon</classifier>
                    </configuration>
                </execution>
            </executions>
        </plugin>
    </plugins>
</build>
----

==== Create the Rule Provider Class

. In JBoss Developer Studio, select the `src/main/java` directory, right-click, and choose `New` --> `Class`.

. In the `New Java Class` dialog, enter the following values, and then click `Finish`.
+
[options="nowrap"]
----
Package: com.proprietary.example
Name: ProprietaryServletAnnotationRuleProvider
Superclass: org.jboss.windup.config.AbstractRuleProvider
----
+
This generates the following contents in the `ProprietaryServletAnnotationRuleProvider.java` file.
+
[source,java,options="nowrap"]
----
package com.proprietary.example;

import org.jboss.windup.config.AbstractRuleProvider;
import org.jboss.windup.graph.GraphContext;
import org.ocpsoft.rewrite.config.Configuration;

public class ProprietaryServletAnnotationRuleProvider extends AbstractRuleProvider {

    public Configuration getConfiguration(GraphContext arg0) {
        // TODO Auto-generated method stub
        return null;
    }

}
----

. Add the following rule metadata annotation after the imports and before the class declaration.
+
[source,java,options="nowrap"]
----
@RuleMetadata(tags = "Java",after = {})
----
+
Click on `x` to the left of the newly added line of code and choose "Import 'RuleMetaData'(org.jboss.windup.config.metadata.RuleMetadata)" to resolve the import error. Or if you prefer, manually add the import of `org.jboss.windup.config.metadata.RuleMetadata`.

. Replace the `return null;` within the getConfiguration() method with the following Java code.
+
[source,java,options="nowrap"]
----
return ConfigurationBuilder.begin()
    .addRule()
    .when(
        JavaClass.references("com.example.proprietary.ProprietaryServlet").at(TypeReferenceLocation.ANNOTATION)
    )
    .perform(
        Classification.as("Proprietary @ProprietaryServlet")
            .with(Link.to("Java EE 6 @WebServlet", "http://docs.oracle.com/javaee/6/api/javax/servlet/annotation/package-summary.html"))
            .withEffort(0)
            .and(Hint.withText("Replace the proprietary @ProprietaryServlet annotation with the Java EE 6 standard @WebServlet annotation.").withEffort(1)))
    .addRule()
    .when(
        JavaClass.references("com.example.proprietary.ProprietaryInitParam").at(TypeReferenceLocation.ANNOTATION)
    )
    .perform(
        Classification.as("Proprietary @ProprietaryInitParam")
            .with(Link.to("Java EE 6 @WebInitParam", "http://docs.oracle.com/javaee/6/api/javax/servlet/annotation/package-summary.html"))
            .withEffort(0)
            .and(Hint.withText("Replace the proprietary @ProprietaryInitParam annotation with the Java EE 6 standard @WebInitParam annotation.").withEffort(2))

    );
----
. Add the following imports to resolve the reference errors.
+
[source,java,options="nowrap"]
----
import org.jboss.windup.ast.java.data.TypeReferenceLocation;
import org.jboss.windup.reporting.config.classification.Classification;
import org.jboss.windup.reporting.config.Hint;
import org.jboss.windup.reporting.config.Link;
import org.jboss.windup.rules.apps.java.condition.JavaClass;
import org.ocpsoft.rewrite.config.ConfigurationBuilder;
----
 
==== Create Data to Test the Rule

.In JBoss Developer Studio, select the `src/test/resources` directory, right-click, and choose `New` --> `Class`.
. In the `New Java Class` dialog, enter the following values, and then click `Finish`.
+
[options="nowrap"]
----
Package: com.proprietary.example
Name: MyProprietaryAnnotatonClass
Superclass: javax.servlet.http.HttpServlet
----
+
This generates the following `MyProprietaryAnnotationClass.java` file.
+
[source,java,options="nowrap"]
----
package com.proprietary.example;

import javax.servlet.http.HttpServlet;

public class MyProprietaryAnnotationClass extends HttpServlet {

}
----
. Add the proprietary annotations to the test class after the imports and before the class declaration.
+

[source,java,options="nowrap"]
----
@ProprietaryServlet (
​    name = "catalog",
​    runAs = "SuperEditor"
​    initParams = { 
​        @ProprietaryInitParam (name="catalog", value="spring"),
​        @ProprietaryInitParam (name="language", value="English")
​     },
​     mapping = {"/catalog/*"}
​)
----

==== Compile and Install the Rule in the Local Maven Repository

. In JBoss Developer Studio, select the `proprietary-annotation-example` project, right-click, and choose `Run As` --> `Maven install`.
. You should see the following result, meaning the rule was successfully installed in your local Maven repository.
+
[options="nowrap"]
----
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
----

==== Add the Rule to {ProductShortName}

{ProductShortName} uses the Maven GAV (groupId, artifactId, and version) that is specified in the project POM file to locate the installed rule in the local Maven repository. The command to add the rule to {ProductShortName} is executed in a terminal from the WINDUP_HOME directory and uses the following syntax.

[options="nowrap"]
----
bin/windup --install GROUP_ID:ARTIFACT_ID[,VERSION]
----

. Open a command prompt and navigate to the `WINDUP_HOME` directory.
. Type the following command.
+
----
bin/windup --install org.jboss.windup.rules.examples:proprietary-annotation-example,1.0.0-SNAPSHOT
----

. At the following prompt, choose `Y`.
+
----
Confirm installation [Y/n]? Y
----

. You should see the following result.
+
----
Installation completed successfully.
----
. Type `exit` to exit the Windup console.


==== Test the Rule

. Open a terminal and navigate to the {ProductHomeVar} directory.

. Type the following command to test the rule, passing the test file as an input argument and a directory for the output report.
+
[options="nowrap"]
----
For Linux:    bin/windup --sourceMode --input WORKSPACE_PATH/proprietary-annotation-example/src/test/ --output WORKSPACE_PATH/proprietary-annotation-example/windup-reports --target eap --packages com.proprietary

For Windows:  bin\windup.bat --sourceMode --input WORKSPACE_PATH\proprietary-annotation-example\src\test\ --output WORKSPACE_PATH\proprietary-annotation-example\windup-reports --target eap --packages com.proprietary
----

. You should see this result.
+
[options="nowrap"]
----
***SUCCESS*** Windup report created: WORKSPACE_PATH/proprietary-annotation-example/windup-reports/index.html
              Access it at this URL: file:///WORKSPACE_PATH/proprietary-annotation-example/windup-reports/index.html
----
. Access the report at URL provided and drill down to review the results.
