


[[Dev-Create-the-JavaDoc]]
=== Create {ProductName} JavaDoc

The most recent {ProductName} JavaDoc build is located here: http://windup.github.io/windup/docs/latest/javadoc/index.html

If you want to build an updated version, use the following procedure to create JavaDoc for {ProductShortName}.

. For each of the 3 {ProductShortName} projects, check out a branch containing the specific release of the {ProductShortName} you want to build. 

* {ProductShortName} core code base (windup): https://github.com/windup/windup
* {ProductShortName} XML-based rulesets (windup-rulesets): https://github.com/windup/windup-rulesets
* {ProductShortName} distribution (windup-distribution): https://github.com/windup/windup-distribution

. Build each of the projects as described here: xref:Dev-Build-from-Source[Build {ProductName} from Source] 
. In `windup` core project root directory, type the following Maven command:
+
[options="nowrap"]
----
mvn validate -PjavadocDist
----
. The JavaDoc is created in the {ProductShortName} `target/apidocs` subdirectory.
. If you want to add the JavaDoc to the latest published release, copy this folder to a backup location and then see xref:Dev-Documentation-Process[Documentation Process] for instructions.

NOTE: To cross-link with 3rd-party libraries, see https://issues.jboss.org/browse/WINDUP-422[WINDUP-422} and http://stackoverflow.com/questions/27392535/javadoc-how-to-make-it-link-the-dependencies-maven-project.
