[[execute]]
= Run the {CLINameTitle}

Use the following steps to run {ProductShortName} against your application.

. Open a terminal and navigate to the `RHAMT_HOME/bin/` directory.
. Execute the `rhamt-cli` script, or `rhamt-cli.bat` for Windows, and specify the appropriate arguments.
+
[source,options="nowrap"]
----
$ ./rhamt-cli --input /path/to/jee-example-app-1.0.0.ear --output /path/to/output --source weblogic --target eap:6 --packages com.acme org.apache
----
+
* `--input`: The application to be evaluated. See the xref:input_argument[`--input`] argument description.
* `--output`: The output directory for the generated reports. See the xref:output_argument[`--output`] argument description.
* `--source`: The source technology for the application migration. See the xref:source_argument[`--source`] argument description.
* `--target`: The target technology for the application migration. See the xref:target_argument[`--target`] argument description.
* `--packages`: The packages to be evaluated. This argument is highly recommended to improve performance. See the xref:packages_argument[`--packages`] argument description.

+
See xref:command_line_arguments[{ProductShortName} Command-line Arguments] for a detailed description of all available command-line arguments.

. xref:access_report[Access the report].

See xref:command-examples[{ProductShortName} Command Examples] below for concrete examples of commands that use source code directories and archives located in the Windup GitHub repository.

[discrete]
[[command-examples]]
== {ProductShortName} Command Examples

[discrete]
=== Running {ProductShortName} on Source Code

The following command runs against the {ProductShortName} https://github.com/windup/windup/tree/master/test-files/seam-booking-5.2[seam-booking-5.2] test application source code. It evaluates all `org.jboss.seam` packages and creates a directory named 'seam-booking-report' in the `/home/username/rhamt-cli-reports/` directory to contain the reporting output.

[source,options="nowrap"]
----
$ RHAMT_HOME/bin/rhamt-cli --sourceMode --input /home/username/rhamt-cli-source/test-files/seam-booking-5.2/ --output /home/username/rhamt-cli-reports/seam-booking-report --target eap:6 --packages org.jboss.seam
----

[discrete]
=== Running {ProductShortName} on an Application Archive

The following command runs against the {ProductShortName} https://github.com/windup/windup/blob/master/test-files/jee-example-app-1.0.0.ear[jee-example-app-1.0.0.ear] test EAR archive. It evaluates all `com.acme` and `org.apache` packages and creates a directory named 'jee-example-app-1.0.0.ear-report' in the `/home/username/rhamt-cli-reports/` directory to contain the reporting output.

[source,options="nowrap"]
----
$ RHAMT_HOME/bin/rhamt-cli  --input /home/username/rhamt-cli-source/test-files/jee-example-app-1.0.0.ear --output /home/username/rhamt-cli-reports/jee-example-app-1.0.0.ear-report --target eap:6 --packages com.acme org.apache
----

[discrete]
=== Override {ProductShortName} Properties

To override the default _Fernflower_ decompiler, pass the `-Dwindup.decompiler` argument on the command line. For example, to use the _Procyon_ decompiler, use the following syntax:

[source,options="nowrap"]
----
$ RHAMT_HOME/bin/rhamt-cli -Dwindup.decompiler=procyon --input INPUT_ARCHIVE_OR_DIRECTORY --output OUTPUT_REPORT_DIRECTORY --target TARGET_TECHNOLOGY --packages PACKAGE_1 PACKAGE_2
----

[discrete]
== {ProductShortName} Help

To see the complete list of available arguments for the `rhamt-cli` command, open a terminal, navigate to the `RHAMT_HOME` directory, and execute the following command:

[source, options="nowrap"]
----
$ RHAMT_HOME/bin/rhamt-cli --help
----
