[[execute]]
= Run the {CLINameTitle}

Use the following steps to run {ProductShortName} against your application.

. Open a terminal and navigate to the `__RHAMT_HOME__/bin/` directory.
. Execute the `rhamt-cli` script, or `rhamt-cli.bat` for Windows, and specify the appropriate arguments.
+
[source,options="nowrap"]
----
$ ./rhamt-cli --input /path/to/jee-example-app-1.0.0.ear --output /path/to/output --source weblogic --target eap:6 --packages com.acme org.apache
----
+
* `--input`: The application to be evaluated. See the xref:input_argument[`--input`] argument description.
* `--output`: The output directory for the generated reports. See the xref:output_argument[`--output`] argument description.
* `--source`: The source technology for the application migration. See the xref:source_argument[`--source`] argument description.
* `--target`: The target technology for the application migration. See the xref:target_argument[`--target`] argument description.
* `--packages`: The packages to be evaluated. This argument is highly recommended to improve performance. See the xref:packages_argument[`--packages`] argument description.

+
See xref:command_line_arguments[{ProductShortName} Command-line Arguments] for a detailed description of all available command-line arguments.

. xref:access_report[Access the report].

See xref:command-examples[{ProductShortName} Command Examples] below for examples of commands that use source code directories and archives located in the {ProductShortName} GitHub repository.

[discrete]
[[command-examples]]
== {ProductShortName} Command Examples

[discrete]
=== Running {ProductShortName} on an Application Archive

The following command analyzes the `com.acme` and `org.apache` packages of the https://github.com/windup/windup/blob/master/test-files/jee-example-app-1.0.0.ear[jee-example-app-1.0.0.ear] example EAR archive for migrating from JBoss EAP 5 to JBoss EAP 7.

[source,options="nowrap",subs="+quotes"]
----
$ __RHAMT_HOME__/bin/rhamt-cli --input /path/to/jee-example-app-1.0.0.ear --output /path/to/report-output/ --source eap:5 --target eap:7 --packages com.acme org.apache
----

[discrete]
=== Running {ProductShortName} on Source Code

The following command analyzes the `org.jboss.seam` packages of the https://github.com/windup/windup/tree/master/test-files/seam-booking-5.2[seam-booking-5.2] example source code for migrating to JBoss EAP 6.

[source,options="nowrap",subs="+quotes"]
----
$ __RHAMT_HOME__/bin/rhamt-cli --sourceMode --input /path/to/seam-booking-5.2/ --output /path/to/report-output/ --target eap:6 --packages org.jboss.seam
----

[discrete]
=== Running Cloud-readiness Rules

The following command analyzes the `com.acme` and `org.apache` packages of the https://github.com/windup/windup/blob/master/test-files/jee-example-app-1.0.0.ear[jee-example-app-1.0.0.ear] example EAR archive for migrating to JBoss EAP 7. It also evaluates for cloud readiness.

[source,options="nowrap",subs="+quotes"]
----
$ __RHAMT_HOME__/bin/rhamt-cli --input /path/to/jee-example-app-1.0.0.ear --output /path/to/report-output/ --target eap:7 --target cloud-readiness --packages com.acme org.apache
----

[discrete]
=== Override {ProductShortName} Properties

To override the default _Fernflower_ decompiler, pass the `-Dwindup.decompiler` argument on the command line. For example, to use the _Procyon_ decompiler, use the following syntax:

[source,options="nowrap",subs="+quotes"]
----
$ __RHAMT_HOME__/bin/rhamt-cli -Dwindup.decompiler=procyon --input __INPUT_ARCHIVE_OR_DIRECTORY__ --output __OUTPUT_REPORT_DIRECTORY__ --target __TARGET_TECHNOLOGY__ --packages __PACKAGE_1__ __PACKAGE_2__
----

[discrete]
== {ProductShortName} Help

To see the complete list of available arguments for the `rhamt-cli` command, open a terminal, navigate to the `__RHAMT_HOME__` directory, and execute the following command:

[source, options="nowrap",subs="+quotes"]
----
$ __RHAMT_HOME__/bin/rhamt-cli --help
----
