[[features]]
= {ProductShortName} Features

{ProductShortName} provides a number of capabilities to assist with planning and executing migration projects.

Planning and work estimation::
{ProductShortName} assists project managers by detailing the type of work and estimation of effort to complete the tasks. Level of effort is represented in {ProductShortName} reports as xref:rule_story_points[story points]. Actual level of effort will be based on the skills required and the classification of migration work needed.

Resources to complete migration tasks::
{ProductShortName} provides suggested code changes and additional resources to help engineers resolve the migration issues identified.

Detailed reporting::
{ProductShortName} produces numerous xref:review_reports[reports] to give both high-level views of the migration effort and details of specific migrations tasks. At a glance, you can see a summary of all migration issues, reports of technologies used in the application, and dependencies on other applications and services. You can also examine source files to see the line of code where an issue occurs.

Built-in rules and migration paths::
{ProductShortName} comes with a core set of rules to identify common migration issues, such as hard-coded IP addresses and JNDI lookups, and provide specific assistance for several xref:migration_paths[migration paths].

Rule extensibility and customization::
{ProductShortName} provides the ability to create powerful and complex rules. You can expand upon the core set of rules provided by {ProductShortName} and create rules to identify additional issues that are important for your migration project. You can also override core rules and create custom rule categories. See the link:{ProductDocRulesGuideURL}[_{RulesDevBookName}_] for more information on customizing {ProductShortName} rules.

// TODO: Worthwhile, or remove?
Ability to analyze source code or application archives::
{ProductShortName} can evaluate application archives or source code, and can evaluate multiple applications together. It can identify archives that are shared across multiple applications, which can help with accurate effort estimation.
