// Module included in the following assemblies:
//
// * docs/getting-started-guide/master.adoc

[id="features_{context}"]
= {ProductShortName} features

Plan and perform your migration and modernization projects more efficiently by using {ProductName} ({ProductShortName}) features.

Planning and work estimation::
Plan work efforts by using the story point estimates that appear in {ProductShortName} reports.

Identifying issues and providing solutions::
Identify specific lines of code that might cause migration or modernization issues. {ProductShortName} suggests code changes and provides additional resources to help you resolve problems.

Detailed reporting::
View reports that give a high-level view of the efforts needed to complete your project as well as the ability to drill down to specifics such as the dependencies of your applications on other applications and services.
+
For more information on the available {ProductShortName} reports, see the link:{ProductDocUserGuideURL}[_{UserCLIBookName}_] .

Built-in rules and migration paths::
Use the rulesets supplied with {ProductShortName} to identify the use of proprietary functionality from other application servers or from deprecated versions of JBoss EAP and other targets.

Rule extensibility and customization::
Create powerful and complex rules to identify issues beyond those addressed by the rulesets included in {ProductShortName} and then add these rules to your {ProductShortName} configuration to analyze your projects.
+
For more information on customizing {ProductShortName} rules, see the link:{ProductDocRulesGuideURL}[_{RulesDevBookName}_].

Ability to analyze source code or application archives::
Evaluate source code or application archives, including those shared across multiple applications using {ProductShortName}.
