[[Features]]
= Features of {ProductName}

Shared Data Model:: {ProductShortName} creates a shared data model graph that provides the following benefits.

* It enables complex rule interaction, allowing rules to pass findings to other rules.
* It enables third-party plugins to interact with other plugins, rules, and reports.
* The findings in the data graph model can be searched and queried during rule execution and used for reporting purposes.

Enhanced Rule Capabilities::

{ProductShortName} provides the ability to create powerful and complex rules. 

* XML-based rules are simple to write and and easy to implement.
* Java-based rule add-ons provide greater flexibility and power when creating rules.
* Rules can be nested to handle more complex situations. This means you can nest simple statements rather than use complex XPATH or REGEX expressions.
* Rules can be linked using and/or statements.

Extensibility::

{ProductName} can be extended by developers, users, and third-party software.

* It provides a plug-in API to inject other applications into {ProductShortName}.
* It enables third-parties to create simple plugins that can interact with the data graph.
* It allows users with domain knowledge to implement their own rules.

Targeted Reporting::

{ProductShortName} reports are targeted for specific audiences.

* Project Management: Reports detail the type of work and estimation of effort to complete the tasks.
* Developers: Reports provide hints and suggested code changes by class or file.

Work Estimation:: 

Estimates for the _level of effort_ are based on the skills required and the classification of migration work needed. Level of effort is represented as _story points_ in the {ProductShortName} reports.

