// Module included in the following assemblies:
//
// * docs/cli-guide/master.adoc
// * docs/maven-guide/master.adoc

:_content-type: CONCEPT
[id="get-involved_{context}"]
= Contributing to the project

To help the {ProductName} cover most application constructs and server configurations, including yours, you can help with any of the following items:

* Send an email to jboss-migration-feedback@redhat.com and let us know what {ProductShortName} migration rules must cover.
* Provide example applications to test migration rules.
* Identify application components and problem areas that might be difficult to migrate:
** Write a short description of the problem migration areas.
** Write a brief overview describing how to solve the problem in migration areas.
* Try {ProductName} on your application. Make sure to report any issues you meet.
* Contribute to the {ProductName} rules repository:
** Write a {ProductName} rule to identify or automate a migration process.
** Create a test for the new rule.

+
For more information, see link:{ProductDocRulesGuideURL}[_{RulesDevBookName}_].
* Contribute to the project source code:
** Create a core rule.
** Improve {ProductShortName} performance or efficiency.

Any level of involvement is greatly appreciated!
