

:ProductDocRulesGuideURL: https://access.redhat.com/documentation/en/red-hat-jboss-migration-toolkit/version-2.5/windup-rules-development-guide


[[Glossary]]
=== Glossary of Terms Used in {ProductShortName}

==== Rules Terms

Rule:: A piece of code that performs a single unit of work during the migration process. The following is an example of am XML-based rule that finds and reports on instances of `weblogic-ejb-jar` XML files and provides a link to a article on the Red Hat Customer Portal that describes how to migrate the file.

+
[source,xml,options="nowrap"]
----
<rule id="weblogic-xml-descriptor-04000">
    <when>
        <xmlfile matches="/weblogic-ejb-jar" />
    </when>
    <perform>
        <classification title="WebLogic EJB XML" severity="mandatory" effort="3">
            <link href="https://access.redhat.com/articles/1326823" title="Map weblogic-ejb-jar.xml Elements to the jboss-ejb3.xml Descriptor" />
            <tag>ejb</tag>
        </classification>
    </perform>
</rule>
----

RuleProvider::  An implementation of OCPSoft ConfigurationProvider class specifically for {ProductShortName}. It provides Rule instances and the relevant RuleProviderMetadata for those Java-based and XML-based Rule instances. 

Ruleset:: A ruleset is a group of one or more RuleProviders that targets a specific area of migration, for example, `Spring -> Java EE 6` or `WebLogic -> JBoss EAP`. A ruleset is packaged as a JAR and contains additional information needed for the migration, such as operations, conditions, report templates, static files, metadata,  and relationships to other rulesets. The following {ProductShortName} projects are rulesets.

* rules-java-ee
* rules-xml

Rules Metadata:: Information about whether a particular ruleset applies to a given situation. The metadata can include the source and target platform and frameworks.

Rules Pipeline:: A collection of rules that feed information into the knowledge graph.

==== Reporting Terms

Level of effort:: The effort required to complete the migration task. _Level of effort_ is represented as _story points_ in the {ProductShortName} reports.

Story Point:: A term commonly used in Scrum Agile software development methodology to estimate the _level of effort_ needed to implement a feature or change. It does not necessarily translate to man-hours, but the value should be consistent across tasks. Story points are covered in more detail in the {ProductDocRulesGuideURL}[{ProductName} Rules Development Guide].
