// Module included in the following assemblies:
//
// * docs/cli-guide/master.adoc

:_content-type: PROCEDURE

[id="installing-cli-tool_{context}"]
= Installing the {CLINameTitle}

You can install the {ProductShortName} {CLINameTitle} on Linux, Windows, or macOS operating systems.

.Prerequisites

* Red Hat Container Registry Authentication for `registry.redhat.io`. Red Hat distributes container images from registry.redhat.io, which requires authentication. For more details, see link:https://access.redhat.com/RegistryAuthentication[Red Hat Container Registry Authentication].
* Podman must be installed

+
[NOTE]
.Podman
====
Podman is a daemonless, open source, Linux native tool designed to make it easy to find, run, build, share and deploy applications using Open Containers Initiative (OCI) Containers and Container Images.
Podman provides a command line interface (CLI) familiar to anyone who has used the Docker Container Engine.
For more information on installing and using Podman, see link:https://podman.io/docs/installation[Podman installation instructions].
====

Installation options

This section offers two options to install {ProductShortName} {CLINameTitle}:

* Downloading a `.zip` file and installing it using a command line
* Running Podman on your computer and installing using Podman commands

+
[WARNING]
====
Although installation using Podman is possible, downloading and installing the `.zip` file is the preferred installation.
====


[id="installing-downloadable-cli-zip_{context}"]
== Installing the {CLINameTitle} `.zip` file

.Procedure

To install using the downloadable `.zip` file:

. Navigate to the link:https://developers.redhat.com/products/mta/download[{ProductShortName} Download page] and download the OS-specific {ProductShortName} CLI file or the `mta-{ProductVersion}-cli-src` file:
+
* Migration Toolkit {CLINameTitle} -{CLINameTitle} for Linux x86_64
* Migration Toolkit {CLINameTitle} -{CLINameTitle} for Linux aarch64
* Migration Toolkit {CLINameTitle} -{CLINameTitle} for macOS x86_64
* Migration Toolkit {CLINameTitle} -{CLINameTitle} for macOS aarch64
* Migration Toolkit {CLINameTitle} -{CLINameTitle} for Windows x86_64
* Migration Toolkit {CLINameTitle} -{CLINameTitle} for Windows aarch64
* Migration Toolkit {CLINameTitle} -{CLINameTitle} for {ProductShortName} source Code

+
[NOTE]
====
Do not download and install the {ProductShortName} source code file if your computer runs one of the above operating systems.
====

. Extract the `.zip` file to a directory of your choice. The `.zip` file extracts a single binary, called *mta-cli*.
+
When you encounter `<{ProductShortName}_HOME>` in this guide, replace it with the actual path to your {ProductShortName} installation.

. Copy or save the `mta-cli` binary, or `mta-cli.exe` in Windows, to a known directory.
+
Continue to xref:cli-run_cli-guide[Running the CLI] to run the CLI command.


[id="installing-using-podman_{context}"]
== Installing the {CLINameTitle} using Podman

.Prerequisites

* Red Hat Container Registry Authentication for `registry.redhat.io`. Red Hat distributes container images from registry.redhat.io, which requires authentication. For more details, see link:https://access.redhat.com/RegistryAuthentication[Red Hat Container Registry Authentication].


.Procedure

To install using `podman pull`:

. To use Podman to authenticate to registry.redhat.io:
+
[source,terminal]
----
podman login registry.redhat.io
----

. Enter your `Username` and `Password`.
+
[source,terminal]
---- 
Username: <username>
Password: <***********>
----
+
If your `Usernam` and `Password` are correct, the terminal line should show `Login Succeeded!`.

. Copy the binary `PATH` for system-wide use.
+
[source,terminal]
----
podman cp $(podman create registry.redhat.com/mta-toolkit/mta-mta-cli-rhel9:{ProductVersion}):/usr/local/bin/mta-cli ./
----
+
This command will copy the binary `PATH` for system-wide use.


