// Module included in the following assemblies:
//
// * docs/web-console-guide-mtr/master.adoc

:_content-type: PROCEDURE
[id="installing-web-console-on-openshift_{context}"]
= Installing the {WebName} on {ocp-short} 4.11 and later

You can install the {WebName} on {ocp-short} 4.11 and later versions with the {ProductName} Operator.

.Prerequisites

* 6 vCPUs, 8 GB RAM, and 40 GB persistent storage.
* One or more projects in which you can install the {WebName}.
+
[IMPORTANT]
====
Do not install the {WebName} in a default project.
====

* `cluster-admin` privileges to install the {DocInfoProductName} Operator.
* `project-admin-user` privileges to install the {WebName} application in a project.

.Configuring Red Hat Single Sign-on (SSO)

You must decide at installation time whether the {WebName} requires authentication. If it does, you must first install and configure Red Hat SSO and input some RH SSO settings when instantiating the MTR Operator.

[NOTE]
====
Authentication can not be added or removed after installation.
====

. Open the Red Hat SSO administration console.
. Add a realm named *windup*.
. In the realm, create a client named *windup-web*.
. Check that *Access Type* is set to `public`. Set *Valid Redirect URIs* and *Web Origins* to `\*`. Click *Save*.
+
Note that after the {ProductShortName} operator has been instantiated, the *Valid Redirect URIs* and *Web Origins* fields have to be set to the secure-mtr-web-console route.
. Create a role named *user*.
. Create a user with any name.
. Set the credentials of the user, disable *Temporary*, and assign the role "user" to the user.

.Installing the {ProductShortName} Operator

. Log in to the OpenShift web console as a user with `cluster-admin` privileges.
. Click *Operators* -> *OperatorHub*.
. Use the *Search by keyword* field to locate the *{DocInfoProductName}* Operator.
. Click *Install*.
. Select a project from the *Installed Namespace* list and click *Install*.
. Click *Operators* -> *Installed Operators* to verify that the Operator is installed.

.Installing the {WebName} application

. Log in to the OpenShift web console as a user with `project-admin-user` privileges.
. Switch to the *Migration* perspective and click *+Add*.
. In the *Add* view, click *Operator Backed*.
. Click the *{DocInfoProductName}* Operator.
. Click *Create*.
. Review the application settings. If the {WebName} requires authentication, input the RH SSO settings and click *Create*.
. In the *Topology* view, click the `mtr-web-console` application and then click the *Resources* tab.
. If authentication is required, set the RH SSO *Valid Redirect URIs* and *Web Origins* fields to the secure-mtr-web-console route.
. Click the `secure-mtr-web-console` route to open the {WebName} in a new browser window.
