// Module included in the following assemblies:
//
// * docs/maven-guide/master.adoc

:_content-type: PROCEDURE
[id="maven-run_{context}"]
= Running the {MavenNameTitle}

The {MavenName} is run by including a reference to the plugin inside your application's `pom.xml` file. When the application is built, the {MavenName} is run and generates the reports for analysis.

.Prerequisites
include::snippet_jdk-hardware-mac-prerequisites.adoc[]

.Procedure

. Add the following `<plugin>` to your application's `pom.xml` file:
+
[source,xml,options="nowrap",subs="+quotes,+attributes"]
----
[...]
<plugin>
    <groupId>org.jboss.windup.plugin</groupId>
    <artifactId>windup-maven-plugin</artifactId>
    <version>{MavenProductVersion}</version>
    <executions>
        <execution>
            <id>run-windup</id>
            <phase>package</phase>
            <goals>
                <goal>windup</goal>
            </goals>
        </execution>
    </executions>
    <configuration>
        <offlineMode>true</offlineMode> <1>
    </configuration>
</plugin>
[...]
----
<1> `offlineMode` runs the {MavenName} in offline mode, disabling network features to improve performance.

. If using Java 11, then `--add-modules=java.se` must be added to the `MAVEN_OPTS` environment variable. When using older versions of Java this is not necessary, and you can proceed to the next step.
+
[source,options="nowrap"]
----
export MAVEN_OPTS=--add-modules=java.se
----
+
[IMPORTANT]
====
Using the {MavenName} on Java 11 is provided as Technology Preview only. Technology Preview features are not supported with Red Hat production service level agreements (SLAs), might not be functionally complete, and Red Hat does not recommend to use them for production. These features provide early access to upcoming product features, enabling customers to test functionality and provide feedback during the development process.

See link:{KBArticleTechnologyPreview}[Technology Preview Features support scope] on the Red&nbsp;Hat Customer Portal for information about the support scope for Technology Preview features.
====

. Build the project:
+
[source,options="nowrap"]
----
$ mvn clean install
----
+
You can access the generated reports.
