[[migration_paths]]
= Supported Migration Paths

{ProductShortName} supports application migration from several platforms to Red Hat JBoss Enterprise Application Platform (JBoss EAP). See the below table for which JBoss EAP version is currently supported by Windup for direct migration from your source platform.

[cols="40%,30%,30%",options="header"]
|====
| Source Platform |Migration to JBoss&nbsp;EAP&nbsp;6 | Migration to JBoss&nbsp;EAP&nbsp;7
| Oracle® WebLogic Server | {icon-check} | {icon-check}
| IBM® WebSphere® Application Server | {icon-check} | {icon-check}
| JBoss EAP 4 | {icon-check} | {icon-x} footnoteref:[note1,Although Windup does not currently provide rules for this migration path, Red Hat Consulting can assist with migration from any source platform.]
| JBoss EAP 5 | {icon-check} | {icon-check}
| JBoss EAP 6 | N/A | {icon-check}
|====

You will specify the source and target technologies by passing the xref:source_argument[`--source`] and xref:target_argument[`--target`] arguments to the {ProductShortName} command.

.Example {ProductShortName} Command: WebLogic to JBoss EAP 6
[source,options="nowrap"]
----
$ WINDUP_HOME/bin/windup --source weblogic --target eap:6 --input /path/to/application.war
----

.Example {ProductShortName} Command: JBoss EAP 6 to JBoss EAP 7
[source,options="nowrap"]
----
$ WINDUP_HOME/bin/windup --source eap:6 --target eap:7 --input /path/to/application.war
----

See xref:execute[Run {ProductName}] for more information on running {ProductShortName}.
