// Module included in the following assemblies:
//
// * docs/web-console-guide/master.adoc

:_content-type: PROCEDURE
[id="mta-web-config-jira-credentials_{context}"]
= Configuring Jira credentials

To define a Jira instance in {ProductShortName} and establish a connection to that instance, you must first create an {ProductShortName} credential to authenticate to the Jira instance's API.

Two types of credentials are available:

* *Basic auth* - for Jira Cloud and a private Jira server or data center
* *Bearer Token* - for a private Jira server or data center

To create an {ProductShortName} credential, follow the procedure below.

.Procedure

. In *Administration* view, click *Credentials*.
+
The *Credentials* page opens.
. Click *Create new*.
. Enter the following information:
    * *Name*
    * *Description* (optional)
. In the *Type* list, select *Basic Auth (Jira)* or *Bearer Token (Jira)*:
+
* If you selected *Basic Auth (Jira)*, proceed as follows:

.. In the *Email* field, enter your email.
.. In the *Token* field, depending on the specific Jira configuration, enter either your token generated on the Jira site or your Jira login password.
+
[NOTE]
====
To obtain a Jira token, you need to log in to the Jira site.
====
+
.. Click *Save*.
+
The new credential appears on the *Credentials* page.

* If you selected *Bearer Token (Jira)*, proceed as follows:

.. In the *Token* field, enter your token generated on the Jira site.
.. Click *Save*.
+
The new credential appears on the *Credentials* page.

You can edit a credential by clicking *Edit*.

To delete a credential, click *Delete*.

[NOTE]
====
You cannot delete a credential that has already been assigned to a Jira connection instance.
====