// Module included in the following assemblies:
//
// * docs/web-console-guide/master.adoc

:_content-type: PROCEDURE
[id="mta-web-reviewing-an-analysis-report_{context}"]
= Reviewing an analysis report

An {ProductShortName} analysis report contains a variety of sections, including a listing of the technologies used by the application, the dependencies of the application, and the lines of code that must be changed to successfully migrate or modernize the application.

For more information on the contents of an {ProductShortName} analysis report, see the link:{ProductDocUserGuideURL}#review-reports_cli-guide[Reviewing the reports].

.Procedure

. In *Migration* view, click *Reports*.
. In the *Current landscape* pane, select *All questionnaires* or a single questionnaire from the drop-down list to see an overview of the risk distribution (High, Medium, Low, Unassessed/Unknown).
. In the *Identified risks* pane, filter the report results by selecting a component from the drop-down list (Questionnaire, Section, Question, Answer,  Risk), and select an item from the resulting filter drop down list.
. You can also sort the results by clicking a column heading (Questionnaire, Section, Question, Answer, Risk).
