// Module included in the following assemblies:
//
// * docs/getting-started-guide/master.adoc
// * docs/cli-guide/master.adoc
// * docs/maven-guide/master.adoc
// * docs/eclipse-code-ready-studio-guide/master.adoc
// * docs/vs-code-extension-guide/master.adoc
// * docs/web-console-guide/master.adoc

[[about_mta]]
:_content-type: CONCEPT
[id="mta-what-is-the-toolkit_{context}"]
= About the {ProductName}

[discrete]
== What is the {ProductName}

{ProductName} ({ProductShortName}) accelerates large-scale application modernization efforts across hybrid cloud environments on {ocp-full} ({ocp-first}). This solution provides insight throughout the adoption process, at both the portfolio and application levels: inventory, assess, analyze, and manage applications for faster migration to OpenShift using the user interface or command line interface.

{ProductShortName} uses an extensive default questionnaire as the basis for assessing your applications for difficulty, time, and other resources needed to prepare an application for containerization. You can also create your own custom questionnaires. 

The {ProductShortName} analysis reports assess the resources required to containerize an application. It separates the assessed applications according to 3 tiers:
* Applications that are good candidates for containerization
* Applications that require significant work before being modernized
* Applications that are not suitable for containerization

{ProductShortName} analyzes applications by applying one or more rulesets to each application considered. The rulesets determine the specific lines of that application require modification before it can be migrated or modernized.

{ProductShortName} examines application artifacts, including project source directories and application archives, and then produces an HTML report highlighting areas that need changes.


[discrete]
== How the {ProductName} simplifies migration

The {ProductName} analyzes the application by looking for common resources and known trouble spots when migrating applications. It provides a high-level view of the technologies used by the application.

After analyzing the application, {ProductShortName} generates a detailed report evaluating a migration or modernization path. This report can help you estimate the effort required for large-scale projects and reduce the work involved.
