// Module included in the following assemblies:
//
// * docs/release_notes-7.0/master.adoc

:_content-type: REFERENCE
[id="mta-rn-resolved-issues-7-0-3_{context}"]
= Resolved issues

This section provides issues that have been resolved in {ProductFullName} version 7.0.3.

.Returned the `Multi select filter` option in the `All issues` page

The `Multi select filter` option has been returned to select several names from a drop-down list of applications in the `All issues` page. link:https://issues.redhat.com/browse/MTA-2560[(MTA-2560)]

.Fixed failed analysis on DC clusters

Failed upload and analysis on a disconnected cluster has been fixed. The failed analysis returned the `Error: exit status 128` error. link:https://issues.redhat.com/browse/MTA-2513[(MTA-2513)]

.Fixed incorrect assessment status when running an assessment on two questionnaires 

In {ProductShortName} 7.0.2, running two questionnaires showed the `Assessment` status as `Not started` instead of `In progress`. This has been fixed in {ProductShortName} 7.0.3, and now the Assessment status shows `In progress` after one questionnaire or Archetype is started. list:https://issues.redhat.com/browse/MTA-2409[(MTA-2409)] list:[(MTA-2410,] list:https://issues.redhat.com/browse/MTA-2410[MTA-2410)]

.Analysis fails on MacOS
// Copied from Known issues.

Running the `analyze` command on a MacOS machine does not work when Podman does not have enough memory. The analysis failed with timeout, without returning an error. 

Workaround: Set Podman memory to at least 4GB. Podman on MacOS sets default memory to 2GB, which is not enough to run {ProductShortName}. link:https://issues.redhat.com/browse/MTA-2518[(MTA-2518)]

.Tests do not fail when the `output.yaml` file is saved to a different directory than the default
// Copied from Known issues.

When running a CLI command to analyze an application, the analysis requires saving the `output.yaml` file only in the default directory. Previously, when you set the analysis to save `output.yaml` to a different directory, the analysis failed with an error. With this update, the issue has been fixed. As a result, tests do not fail when the `output.yaml` file is saved to a different directory than the default. list:https://issues.redhat.com/browse/MTA-2654[(MTA-2654)] 

For a complete list of all issues resolved in this release, see the list of link:https://issues.redhat.com/issues/?filter=12434260[Resolved Issues in Jira].
