// Module included in the following assemblies:
//
// * docs/web-console-guide/master.adoc

:_content-type: PROCEDURE
[id="mta-web-creating-custom-migration-targets_{context}"]
= Creating custom migration targets

The purpose of this feature is to enable architects or users with `admin` permissions to create and maintain custom rulesets (migration targets). Architects can upload custom rule files and assign them to various custom migration targets. The custom migration targets are then available for selecting in the analysis configuration wizard.

Using ready-made custom migration targets makes the cumbersome task of configuring custom rules for each analysis run unnecessary. This simplifies analysis configuration and execution for non-admin users or third-party developers and makes using the {ProductShortName} tool easier and more straightforward.

.Prerequisites

* You must be logged in as a user with `admin` permissions.

.Procedure

. In *Administration* view, click *Custom migration targets*.
. Click *Create new*.
. Fill in the name and description of the target.
. In the *Image* section, upload an image file for the target's icon. The file can be in either PNG or JPEG format, up to 1 MB. If you do not upload any file, a default icon is used.
. In the *Custom rules* section, select either *Upload manually* or *Retrieve from a repository*.
** If you have selected *Upload manually*, upload or drag and drop the required rule files from your local drive.
** If you have selected *Retrieve from a repository*, proceed as follows:
... Choose *Git* or *Subversion*.
... Fill in *Source repository*, *Branch* and *Root path*.
... If the repository requires credentials, enter them in the *Associated credentials* field.
. Click *Create*.
+
The new migration target appears on the *Custom migration targets* page. It can now be used by non-admin users in *Migration* view.
