// Module included in the following assemblies:
//
// * docs/web-console-guide/master.adoc
// * topics/mta-assessment-module.adoc

:_content-type: REFERENCE
[id="mta-web-assessment-module_{context}"]
= Assessment Module

The assessment process for applications that are to be migrated in {ProductFullName} has been separated from other features.

In the {ProductShortName} user interface, the Assessment Module appears in a separate menu item. Selecting the item shows the currently saved applications.

The {ProductShortName} assesses applications that are to be migrated, according to a set of questions relevant to the application, such as dependencies.


[id="mta-assessment-new-app_{context}"]
== Creating a new application

You can create a new application in {ProductShortName}.

.Prerequisites

* Be logged on to an {ProductShortName} server.

.Procedure

. In the {ProductShortName} user interface, select the *Migration* working mode.
. Click *Application Inventory* in the left menu bar.
. Click *Create new*. The *New application* dialog appears.
. In the form, supply the following information:
.. *Name*: unique name for the new application
.. *Description*: short description of the application (optional)
.. *Business service*: purpose of the application (optional)
.. *Tags*: software tags that characterize the application
.. *Owner*: registered software owner from drop-down list (optional)
.. *Contributors*: contributors from drop-down list (optional)
.. *Comments*: relevant comments on the migrated application
. Click *Source code* and enter the following fields.
.. *Repository type*: *Git* or *Subversion*
.. *Source Repository*: URL of the repository where the software code is saved
.. *Branch*: application code branch in the repository
.. *Root path*: [get info] (optional/mandatory)
. Click *Binary* and enter the following fields.
.. *Group*: [get info] (optional/mandatory)
.. *Artifact*: [get info] (optional/mandatory)
.. *Version*: software version of the application
.. *Packaging*: [get info] (optional/mandatory)
. Click *Create*. The dialog closes and the new application appears in the list of defined applications.

[id="mta-assessment-open-app_{context}"]
== Opening an existing application

This procedure describes how to open and edit an application that has already been defined in {ProductShortName}.

.Prerequisites

* Be logged on to an {ProductShortName} server.

.Procedure

. In the {ProductShortName} user interface, select the *Migration* working mode.
. Click *Application Inventory* in the left menu bar. A list of all the available applications appears in the main pane.
. Click `edit` {edit} to open the application settings, and review the application settings. See procedure above for a list of application settings.

////
:_content-type: PROCEDURE
[id="mta-assessment-run_{context}"]
== Running an assessment on an application

.Prerequisites

* Be logged on to an {ProductShortName} server.

.Procedure

. In the {ProductShortName} user interface, select the *Migration* working mode.
. Click *Application Inventory* in the left menu bar. A list of all the available applications appears in the main pane.
. Select an application from the list that appears in the main pane, click the Options menu {kebab} at the end of the row, and select *Assess* from the drop-down menu.
. *Assessment Action* appears in the main pane. Select one of the questionnaires and click *Take*.
. *Application assessment*
////
