// Module included in the following assemblies:
//
// * docs/cli-guide/master.adoc

:_content-type: REFERENCE
[id="cli-args_{context}"]
= About {ProductShortName} command-line arguments

The following is a detailed description of the available {ProductShortName} command line arguments.

[NOTE]
====
To run the {ProductShortName} command, for example when executing from a script, you must use the following arguments:

* `--overwrite`
* `--input`
* `--target`
====


.{ProductShortName} CLI arguments
[cols="40%,60%a",options="header",]
|====
|Argument |Description
|--analyze-known-libraries | Flag to analyze known software artifacts embedded within your application. By default, {ProductShortName} only analyzes application code.

[NOTE]
====
This option may result in a longer execution time and a large number of migration issues being reported.
====

|--help |Display the {ProductShortName} help message.
|--input |A space-delimited list of the path to the file or directory containing one or more applications to be analyzed. This argument is required.
| --list-sources
| list rules for available migration sources
|--list-sources | Flag to list all available source technologies.
|--list-targets| Flag to list all available target technologies.
|--output |Specify the path to the directory to output the report information generated by {ProductShortName}.

[IMPORTANT]
====
Do not overwrite a report output directory that contains important information.
====
| --rules stringArray | Filename or directory containing rule files
| --source |A space-delimited list of one or more source technologies, servers, platforms, or frameworks to migrate from. This argument, in conjunction with the `--target` argument, helps to determine which rulesets are used. Use the `--listSourceTechnologies` argument to list all available sources.
|--target |A space-delimited list of one or more target technologies, servers, platforms, or frameworks to migrate to. This argument, in conjunction with the `--source` argument, helps to determine which rulesets are used. Use the `--list-targets` argument to list all available targets.
|====

[id="cli-input-argument_{context}"]
== Specifying the input

A space-delimited list of the path to the file or directory containing one or more applications to be analyzed. This argument is required.

.Usage
[source,options="nowrap",subs="attributes+"]
----
--input <INPUT_ARCHIVE_OR_DIRECTORY> [...]
----

[id="cli-input-file-type-arguments_{context}"]
== Analyze application source code

Usage: `{mta-cli} analyze [flags]`

The following flags are available:

.{ProductShortName} Analyze application
[cols="40%,60%a",options="header",]
|====
|Flag |Description

| --analyze-known-libraries
|  analyze known open-source libraries

| -h, --help
| help for analyze

| -i, --input string
|  path to application source code or a binary

| --json-output
| create analysis and dependency output as json

| --list-sources
| list rules for available migration sources

| --list-targets
| list rules for available migration targets

| -l, --label-selector string
| run rules based on specified label selector expression

| --maven-settings string
| path to a custom maven settings file to use

| --overwrite
| overwrite output directory

| --skip-static-report
|  do not generate static report

| -m, --mode string
| analysis mode" `full` (default) or `source-only`

| -o, --output string | path to the directory for analysis output

| --rules stringArray | filename or directory containing rule files

| --skip-static-report
| do not generate static report

| -s, --source string
| source technology to consider for analysis. To specify multiple sources, repeat the parameter: --source <source_1> --source <source_2> etc.

| -t, --target string
| target technology to consider for analysis. To specify multiple targets, repeat the parameter: --target <target_1> --target <target_2> etc.
|====

[id="cli-input-file-type-arguments-global-flags_{context}"]
=== Global flags

.{ProductShortName} Analyze application
[cols="40%,60%a",options="header",]
|====

|Flag
|Description

| --log-level uint32
| log level (default 4)

| --no-cleanup
| do not cleanup temporary resources
|====



[id="cli-output-argument_{context}"]
== Specifying the output directory

Specify the path to the directory to output the report information generated by {ProductShortName}.

.Usage
[source,options="nowrap",subs="attributes+"]
----
--output <OUTPUT_REPORT_DIRECTORY>
----

* The `--output` argument is mandatory. If omitted, an error is returned:
+
[source,options="nowrap",subs="attributes+"]
----
Error: required flag(s) "output" not set 
----

However, if you specify the `--overwrite` argument, {ProductShortName} will proceed to delete and recreate the directory. See the description of this argument for more information.

[id="cli-source-argument_{context}"]
== Setting the source technology

A space-delimited list of one or more source technologies, servers, platforms, or frameworks to migrate from. This argument, in conjunction with the `--target` argument, helps to determine which rulesets are used. Use the `--list-sources` argument to list all available sources.

.Usage
[source,options="nowrap",subs="attributes+"]
----
--source <SOURCE_1> <SOURCE_2>
----

The `--source` argument now provides version support, which follows the link:http://maven.apache.org/enforcer/enforcer-rules/versionRanges.html[Maven version range syntax]. This instructs {ProductShortName} to only run the rulesets matching the specified versions. For example, `--source eap5`.

[WARNING]
====
When migrating to JBoss EAP, be sure to specify the version, for example, `eap6`. Specifying only `eap` will run rulesets for all versions of JBoss EAP, including those not relevant to your migration path.

See link:{ProductDocIntroToMTAGuideURL}/index#migration_paths_getting-started-guide[Supported migration paths] in _{IntroToMTABookName}_ for the appropriate JBoss EAP version.
====

[id="cli-target-argument_{context}"]
== Setting the target technology

A space-delimited list of one or more target technologies, servers, platforms, or frameworks to migrate to. This argument, in conjunction with the `--source` argument, helps to determine which rulesets are used. If you do not provide a target, mta-cli analyzes the input based on the source and discovery rules. Use the `--list-targets` argument to list all available targets.

.Usage
[source,options="nowrap",subs="attributes+"]
----
--target <TARGET_1> <TARGET_2>
----


The `--target` argument now provides version support, which follows the link:http://maven.apache.org/enforcer/enforcer-rules/versionRanges.html[Maven version range syntax]. This instructs {ProductShortName} to only run the rulesets matching the specified versions. For example, `--target eap7`.

[WARNING]
====
When migrating to JBoss EAP, be sure to specify the version in the target, for example, `eap6`. Specifying only `eap` will run rulesets for all versions of JBoss EAP, including those not relevant to your migration path.

See link:{ProductDocIntroToMTAGuideURL}/index#migration_paths_getting-started-guide[Supported migration paths] in _{IntroToMTABookName}_ for the appropriate JBoss EAP version.
====

////
[id="cli-packages-argument_{context}"]
== Selecting packages

A space-delimited list of the packages to be evaluated by {ProductShortName}. It is highly recommended to use this argument.

.Usage
[source,options="nowrap",subs="attributes+"]
----
----

* In most cases, you are interested only in evaluating custom application class packages and not standard Java EE or third party packages. The `<PACKAGE_N>` argument is a package prefix; all subpackages will be scanned. For example, to scan the packages `com.mycustomapp` and `com.myotherapp`, use `--packages com.mycustomapp com.myotherapp` argument on the command line.
* While you can provide package names for standard Java EE third party software like `org.apache`, it is usually best not to include them as they should not impact the migration effort.

////
