// Module included in the following assemblies:
//
// * docs/web-console-guide/master.adoc

:_content-type: PROCEDURE
[id="mta-web-tagging-an-application_{context}"]
= Tagging an application

You can attach various tags to the application that you going to analyze. You can do this either automatically or manually.

[id="automating-tagging-an-application_{context}"]
== Automatic tagging

Automatic tagging of application is enabled by default. You can disable it by unselecting the *Enable automated tagging* checkbox in the Advanced section of the Analysis configuration wizard. To tag an application automatically, make sure that the *Enable automated tagging* checkbox is selected _before_ you run the analysis of the application.

[NOTE]
====
To tag an application automatically, make sure to enable automatic tagging _before_ you run the analysis of the application.
====

.Procedure

. In *Migration* view, click *Application inventory*.
. Click the *Analysis* tab.
. Select the applications you want to analyze.


. In *Migration* view, click *Application inventory*.
. Click the *Analysis* tab.
. Select the applications you want to analyze.
+




Tagging

You can filter the tags by source or category. The source can be either *Analysis* or *Manual*. The categories are displayed in a drop-down list, for example, *HTTP*, *MVC*, *Web*, *Observability*, *Persistence*, *Application Type*, *Data Center*.

To attach tags manually, click the pen icon. In the Update application window, select the appropriate tags from the Select a tag(s) drop-down list.
The selected tags appear on the application's page in the Tags tab.

To attach tags automatically, select the Enable automated tagging checkbox. Note that this checkbox is selected by default.
The attached tags appear on the application's page in the Tags tab after you run the analysis.
