// Module included in the following assemblies:
//
// * docs/web-console-guide/master.adoc


:_content-type: REFERENCE
[id="mta-custom-questionnaire_{context}"]
= The custom assessment questionnaire

You can use the {ProductFullName} to import a custom assessment questionnaire by using a custom YAML syntax to define the questionnaire. The YAML syntax supports the following features:

Conditional questions::
The YAML syntax supports excluding or including questions based on tags existing on the application or archetype, for example:
+
[source,yaml]
----
...
  questions:
    - order: 1
      text: What is the main JAVA framework used in your application?
      explanation: Identify the primary JAVA framework used in your application.
      includeFor:
        - category: Language
          tag: Java
...
----


Automated answers based on tags present on the assessed application or archetype::
Automated answers are selected based on the tags existing on the application or archetype. For example, if an application or archetype has the `Runtime/Quarkus` tag, the `Quarkus` answer is automatically selected, and if an application or archetype has the `Runtime/Spring Boot` tag, the `Spring Boot` answer is automatically selected:
+
[source,yaml]
----
...
  text: What is the main technology in your application?
    explanation: Identify the main framework or technology used in your application.
      answers:
        - order: 1
          text: Quarkus
          risk: green
          autoAnswerFor:
            - category: Runtime
              tag: Quarkus
        - order: 2
          text: Spring Boot
          risk: green
          autoAnswerFor:
            - category: Runtime
              tag: Spring Boot
...
----


Autotagging of applications based on answers::
With this feature, tags are automatically applied to the assessed application or archetype based on the answer if this answer is selected. The tags are transitive. Each tag is defined by the following elements:
+
--
* *category*: Category of the target tag (`String`).
* *tag*: Definition for the target tag as (`String`).
--
+
For example, if the selected answer is `Quarkus`, the `Runtime/Quarkus` tag is applied to the assessed application or archetype. If the selected answer is `Spring Boot`, the `Runtime/Spring Boot` tag is applied to the assessed application or archetype:
+
[source,yaml]
----
...
questions:
  - order: 1
    text: What is the main technology in your application?
    explanation: Identify the main framework or technology used in your application.
    answers:
      - order: 1
        text: Quarkus
        risk: green
        applyTags:
          - category: Runtime
            tag: Quarkus
      - order: 2
        text: Spring Boot
        risk: green
        applyTags:
          - category: Runtime
            tag: Spring Boot
...
----
