// Module included in the following assemblies:
//
// * docs/release_notes/master.adoc

:_content-type: REFERENCE
[id="rn-known-issues-7-0-0_{context}"]
= Known issues

{ProductFullName} version 7.0.0 has the following issues.

.Pathfinder assessment migration fails on upgrade from {ProductShortName} 6.2.1 to {ProductShortName} 7.0.0

If {ProductShortName} 6.2.1 is installed, when attempting to switch the channel to `stable-7.0`, the operator upgrade succeeds, but a task in the operator pod fails. This failure results in existing pathfinder assessments not being migrated to {ProductShortName} 7.0.0. This bug will be resolved in {ProductShortName} 7.0.1. No assessment data will be lost, it is will simply not be visible in the UI until the release of {ProductShortName} 7.0.1. link:https://issues.redhat.com/browse/MTA-2139[MTA-2139]

.Delayed permission update and user deactivation in `RBAC`

When deleting, deactivating or degrading the role of a user, such as changing the user from `Admin` to `Migrator`, the change can take several minutes to take effect. This delay in changing the user status can pose an operational or security risk. link:https://issues.redhat.com/browse/MTA-1809[MTA-1809]

.Re-enabling Keycloak breaks {ProductShortName}

Keycloak is enabled by default. If you disable and then re-enable Keycloak, you cannot perform any actions in the {ProductShortName} web console after logging in again.

This error is caused as the `credential-mta-rhsso` secret is updated when `auth/Keycloak` is disabled and re-enabled.

The suggested workaround is to restore the old password in the `credential-mta-rhsso` secret, after re-enabling `auth`. link:https://issues.redhat.com/browse/MTA-1152[MTA-1152]


.org.apache.derby.derby dependency not analyzed

The `org.apache.derby.derby` dependency is not analyzed. link:https://issues.redhat.com/browse/MTA-1817[MTA-1817]

.Redundant warning on reassessment of applications with inherited assessments

The system repeatedly shows a warning message about overriding an inherited assessment when reassessing an application.

This warning, appropriate for the first assessment, incorrectly reappears on subsequent reassessments, suggesting that the application is still inheriting its assessment, even after it has been overridden. link:https://issues.redhat.com/browse/MTA-1825[MTA-1825]

.Custom rule for javax.* package import is not triggered when uploaded as an XML file

In {ProductShortName} 7.0.0, some XML custom rule files are converted to the new YAML format during analysis. The root cause of this issue is that Java search patterns, which use `IMPORT` or `PACKAGE` as `location`, should not end in `.{*}` but just `{*}`. 

To resolve this issue, whenever a custom rule has a pattern ending in `.{*}` and location one of `IMPORT` or `PACKAGE`, the pattern `.{*}` can be changed to `{*}`.

In the following example XML rule, note that the `when` condition is `javaclass references` ="javax.{*}"`. 


If you amend this to `javaclass references="javax{*}"`, the rule converts correctly.


.To view the javax-package-custom-target.windup.xml, click here.
[%collapsible%closed]
====
[source,xml]
----
<?xml version="1.0"?>
<ruleset xmlns="http://windup.jboss.org/schema/jboss-ruleset" id="javax-package"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://windup.jboss.org/schema/jboss-ruleset http://windup.jboss.org/schema/jboss-ruleset/windup-jboss-ruleset.xsd">
    <metadata>
        <description>
            This ruleset evaluates whether a custom target can be used within a custom rule
        </description>
        <dependencies>
            <addon id="org.jboss.windup.rules,windup-rules-javaee,3.0.0.Final" />
            <addon id="org.jboss.windup.rules,windup-rules-java,3.0.0.Final" />
        </dependencies>
        <targetTechnology id="phil" versionRange="[7,8)" />
    </metadata>
    <rules>
        <rule id="javax-package-custom-target-00001">
            <when>
                <javaclass references="javax.{*}">
                    <location>IMPORT</location>
                </javaclass>
            </when>
            <perform>
                <hint title="CUSTOM RULE for javax.* package import" effort="1" category-id="potential">
                    <message>`javax.*` packages must be renamed to `jakarta.*` for Jakarta EE9 compatibility.</message>
                    <link title="Renamed Packages" href="https://github.com/wildfly-extras/batavia/blob/master/impl/ecl/src/main/resources/org/wildfly/extras/transformer/eclipse/jakarta-renames.properties"/>
                </hint>
            </perform>
        </rule>
    </rules>
</ruleset>
----
====

The suggested workaround is to use the following YAML file instead. The YAML file is the result of a conversion from XML. 

In this example, use the following YAML file instead.

.To view the 01-javax-package-custom-target.windup.yaml, click here.
[%collapsible%closed]
====
[source,yaml]
----
- category: potential
  customVariables: []
  description: CUSTOM RULE for javax.* package import
  effort: 1
  labels:
  - konveyor.io/target=phil7
  - konveyor.io/target=phil
  - konveyor.io/source
  links:
  - title: Renamed Packages
    url: https://github.com/wildfly-extras/batavia/blob/master/impl/ecl/src/main/resources/org/wildfly/extras/transformer/eclipse/jakarta-renames.properties
  message: '`javax.*` packages must be renamed to `jakarta.*` for Jakarta EE9 compatibility.'
  ruleID: javax-package-custom-target-00001
  when:
    java.referenced:
      location: package
      pattern: javax*
----
====

The file is the conversion result from XML to YAML format, with the line `location: IMPORT` was changed to `location: package`.


For a complete list of all known issues in this release, see the list of link:https://issues.redhat.com/browse/MTA-2060?filter=12428334[Known Issues in Jira].

// using filter - project in (MTA) AND type = Bug AND createdDate >= 2021-01-01 AND createdDate <= 2024-01-30 AND (resolutiondate > 2024-01-30 OR resolutiondate is EMPTY) AND Priority in (Blocker, Critical, Major) ORDER BY priority DESC, key DESC
