// Module included in the following assemblies:
//
// * docs/release_notes/master.adoc

:_content-type: REFERENCE
[id="rn-known-issues-7-0-0_{context}"]
= Known issues

MTA version 7.0.0 has the following issues.

.Lack of Unique IDs and Aria-Labels on Sections/categories Hindering Automation

Lack of unique IDs applied to sections and catergories hinders migration automation. link:https://issues.redhat.com/browse/MTA-1203[MTA-1203]

.Support downstream disconnected installs

MTA does not support downstream disconnected installs. link:https://issues.redhat.com/browse/MTA-17[MTA-17]

.Can't remove Jira connection to removed Wave after it was added to Wave 

Can't remove Jira connection after it was added to Wave even after Wave was removed. link:https://issues.redhat.com/browse/MTA-1014[MTA-1014]

.Binary analysis takes 3h then fails

Binary analysis takes 3h then fails. link:https://issues.redhat.com/browse/MTA-1183[MTA-1183]

.Allow architects to review an application without an assessment

Allow architects to review an application without an assessment. link:https://issues.redhat.com/browse/MTA-115[MTA-115]




For a complete list of all known issues in this release, see the list of link:https://issues.redhat.com/issues/?filter=12420808[Known Issues in Jira].

////
project in (MTA, WINDUP) AND status not in (Verified, "Release Pending", Closed) AND priority in (Blocker, Critical, Major) AND component not in (documentation, QE-Task) AND fixVersion <= "MTA 7.0.0" ORDER BY priority DESC
////
