// Module included in the following assemblies:
//
// * docs/web-console-guide/master.adoc
// * topics/mta-assessment-module.adoc

:_content-type: CONCEPT
[id="mta-archetypes_{context}"]
= Working with archetypes

An *archetype* is a group of applications with common characteristics. You can use archetypes to assess multiple applications at once. By using archetypes, the {ProductName} ({ProductShortName}) can apply questionnaires populated with questions that apply to common application characteristics.

Application archetypes are defined by criteria tags and the application taxonomy. Each archetype defines how the _assessment module_ assesses the application according to the characteristics defined in that archetype. If the tags of an application match the criteria tags of an archetype, the application is associated with the archetype.

Creation of an archetype is defined by a series of *tags*, *stakeholders*, and *stakeholder groups*. The tags include the following types:

* *Criteria tags* are tags that the archetype requires to include an application as a member.
+
NOTE: If the archetype criteria tags match an application only partially, this application cannot be a member of the archetype. For example, if the application _a_ only has tag _a_, but the archetype _a_ criteria tags include tags _a_ AND _b_, the application _a_ will not be a member of the archetype _a_.

* *Archetype tags* are tags that are applied to the archetype entity.

NOTE: All applications associated with the archetype inherit the _assessment_ and _review_ from the archetype groups to which these applications belong. This is the default setting. You can override inheritance for the application by completing an individual assessment and review.
