// Module included in the following assemblies:
//
// * docs/web-console-guide/master.adoc

:_content-type: PROCEDURE
[id="mta-web-creating-custom-migration-targets_{context}"]
= Creating custom migration targets

Architects or users with `admin` permissions can create and maintain custom rulesets associated with custom migration targets. Architects can upload custom rule files and assign them to various custom migration targets. The custom migration targets can then be selected in the analysis configuration wizard.

By using ready-made custom migration targets, you can avoid configuring custom rules for each analysis run. This simplifies analysis configuration and execution for non-admin users or third-party developers.

.Prerequisites

* You are logged in as a user with `admin` permissions.

.Procedure

. In the *Administration* view, click *Custom migration targets*.
. Click *Create new*.
. Enter the name and description of the target.
. In the *Image* section, upload an image file for the target's icon. The file can be in either the PNG or JPEG format, up to 1 MB. If you do not upload any file, a default icon is used.
. In the *Custom rules* section, select either *Upload manually* or *Retrieve from a repository*:
** If you selected *Upload manually*, upload or drag and drop the required rule files from your local drive.
** If you selected *Retrieve from a repository*, complete the following steps:
... Choose *Git* or *Subversion*.
... Enter the *Source repository*, *Branch*, and *Root path* fields.
... If the repository requires credentials, enter these credentials in the *Associated credentials* field.
. Click *Create*.
+
The new migration target appears on the *Custom migration targets* page. It can now be used by non-admin users in the *Migration* view.
