// Module included in the following assemblies:
//
// * docs/release_notes/master.adoc

:_content-type: CONCEPT
[id="rn-new-features-6-2-0_{context}"]
= New features


This section describes the new features of the Migration Toolkit for Applications (MTA) 6.2.0.

.Integration with JIRA

The integration of {ProductName} with Jira allows you to track and manage the whole migration process. To introduce changes to the applications in the portfolio, you can create issues in Jira and assign them to developers.

For more information, see link:https://access.redhat.com/documentation/en-us/migration_toolkit_for_applications/6.2/html/user_interface_guide/creating-configuring-jira-connection#mta-web-create-config-jira-connection_user-interface-guide[Creating and configuring a Jira connection].

.Migration Waves management

A migration wave is a small collection of workloads that deliver business value. {ProductShortName}'s _Migration Wave_ groups applications to be migrated on a specified schedule.

In addition, a migration wave enables you to export a list of the wave's applications to the Jira issue management system. This automatically creates a separate Jira issue for each application of the migration wave for tracking.

For more information, see link:https://access.redhat.com/documentation/en-us/migration_toolkit_for_applications/6.2/html/user_interface_guide/working-with-applications-in-the-ui#mta-web-creating-migration-waves_user-interface-guide[Creating migration waves] and link:https://access.redhat.com/documentation/en-us/migration_toolkit_for_applications/6.2/html/user_interface_guide/working-with-applications-in-the-ui#mta-web-creating-jira-issues-for-migration-wave_user-interface-guide[Creating Jira issues for a migration wave].

.OpenShift Monitoring integration

{ProductShortName} integrates with OpenShift Monitoring, which allows users to consume metrics from their {ProductShortName} installation.
