// Module included in the following assemblies:
//
// * docs/web-console-guide/master.adoc
// * topics/mta-assessment-module.adoc

:_content-type: REFERENCE
[id="mta-assessment-module_{context}"]
= Assessment Module

The assessment process for applications that are to be migrated in Red Hat Migration Toolbox for Applications (MTA) has been separated from other tool features and enhanced in version 7.0.0.

* A separate new Assessment hub includes the Assessment module, replacing the older _Pathfinder_ feature.
* Assessment supports multiple questionnaires, relevant to each assessed application.
* Default quetionnaires can be cutomized and saved.
* User can design and version custom questionnaires and questions using YAML syntax.
* Assessed applications are grouped into *archetypes* with similar application characteristics.
* Assessment module integrates tightly with the application inventory.
* Assessment questionnaires can be imported and exported.
* Enhanced questionnaire capabilities:
** Conditional questions
** Application auto-tagging according to answers
** Automated answers from tags in application archetypes

In the MTA user interface, the Assessment Module appears in a separate menu item. Selecting the item shows the currently saved default and custom questionnaires.
