// Module included in the following assemblies:
//
// * docs/release_notes-6.2/master.adoc

:_content-type: REFERENCE
[id="mta-rn-resolved-issues-6-2-3_{context}"]
= Resolved issues

The following highlighted issues have been resolved in {ProductFullName} version 6.2.3.


.CVE-2024-30255: `mta-hub-container` envoy: HTTP/2 CPU exhaustion due to CONTINUATION frame flood

A flaw was found in how the `Envoy` proxy implements the `HTTP/2` codec, which impacts earlier versions of {ProductShortName}. There are insufficient limitations placed on the number of `CONTINUATION` frames that can be sent within a single stream. This issue could be resolved. If an unauthenticated remote attacker sends messages to vulnerable servers, this could cause issues by using up resources and causing a denial of service (DoS). Users are recommended to upgrade to {ProductShortName} 6.2.3, which resolves this issue.

For more details, see link:https://access.redhat.com/security/cve/cve-2024-30255[(CVE-2024-30255)].

.CVE-2024-29180: `webpack-dev-middleware` lack of URL validation may lead to file leak

A flaw was found in the `webpack-dev-middleware` package, which impacts earlier versions of {ProductShortName}, where it failed to validate the supplied URL address sufficiently before returning local files. This flaw allows an attacker to craft URLs to return arbitrary local files from the developer's machine. The lack of normalization before calling the middleware also allows the attacker to perform path traversal attacks on the target environment. Users are recommended to upgrade to {ProductShortName} 6.2.3, which resolves this issue.

For more details, see link:https://access.redhat.com/security/cve/CVE-2024-29180[(CVE-2024-29180)]


.CVE-2024-28849: `follow-redirects` package clears authorization headers

A flaw was discovered in the `follow-redirects` package that clears authorization headers, but it fails to clear the `proxy-authentication` headers. This flaw impacts earlier versions of {ProductShortName}. It could lead to credential leakage, which could have a high impact on data confidentiality. Users are recommended to upgrade to {ProductShortName} 6.2.3, which resolves this issue.

For more details, see link:https://access.redhat.com/security/cve/CVE-2024-28849[(CVE-2024-28849)]

.CVE-2024-27316: `HTTP-2`: httpd: CONTINUATION frames

A flaw was found in how Apache `httpd` implements the `HTTP/2` protocol, which impacts earlier versions of {ProductShortName}. This flaw means that there are insufficient limitations placed on the amount of `CONTINUATION` frames that can be sent within a single stream. This issue could allow an unauthenticated remote attacker to send packets to vulnerable servers, which could use up memory resources and cause a denial of service (DoS). Users are recommended to upgrade to {ProductShortName} 6.2.3, which resolves this issue.

.CVE-2023-45288: Golang `net/http, x/net/http2`: unlimited number of `CONTINUATION` frames can cause a denial-of-service (DoS) attack

A flaw was discovered with the implementation of the `HTTP/2` protocol in the Go programming language, which impacts previous versions of {ProductShortName}. There were insufficient limitations on the number of `CONTINUATION` frames sent within a single stream. An attacker could potentially exploit this to cause a denial-of-service (DoS) attack. Users are recommended to upgrade to {ProductShortName} 6.2.3, which resolves this issue.

For more details, see link:https://access.redhat.com/security/cve/cve-2023-45288[(CVE-2023-45288)].

For more details, see link:https://access.redhat.com/security/cve/CVE-2024-27316[(CVE-2024-27316)]

For a complete list of all issues resolved in this release, see the list of link:https://issues.redhat.com/issues/?filter=12435655[Resolved Issues in Jira].
// project = MTA AND issuetype = Bug AND status in (Verified, "Release Pending", Closed) AND priority in (Blocker, Critical, Major) AND fixVersion = "MTA 6.2.3" AND component not in (Documentation, QE-Task) ORDER BY priority DESC

