// Module included in the following assemblies:
//
// * docs/web-console-guide/master.adoc
// * topics/mta-assessment-module.adoc

[id="mta-web-application-archetypes_{context}"]
= Application archetypes

{ProductName}({ProductShortName}) enables assessing and analyzing an entire group of applications or *archetypes*, according to common charateristics. 

Application *archetypes* are dfined according to criteria tags and application taxonomy. Each archetype selects how the applications are assessed according to its characterstics.

:_content-type: PROCEDURE

[id="creating-archetype_{context}"]
== Creating an application Archetype

You can create an Archetype that defines the charateristics of a group of applications, which you can assess as a group.

.Procedure

. In *Migration* view, click *Aarchetypes*.
. Click *Create new archetype*, opening a dialog.
. Enter the following information into the fields.
* Name
* Description (optional)
* Criteria Tags 
* Archetype Tags 
* Stakeholders (optional)
* Stakeholder Groups(s) (optional)
* Comments (optional)
. Click *Create*.
