// Module included in the following assemblies:
//
// * docs/web-console-guide/master.adoc

:_content-type: PROCEDURE
[id="mta-web-assessing-apps_{context}"]
= Assessing an application by using the MTA assessment questionnaire

You can use the default Legacy Pathfinder {ProductFullName} questionnaire to determine the risks involved in containerizing an application before reviewing the application. For more information, see xref:mta-default-questionnaire_user-interface-guide[The default assessment questionnaire].

NOTE: To assess risks involved in containerizing applications, you can also create and use custom questionnaires. In this case, use the `Skipping assessment` option during the assessment. For more information, see xref:mta-custom-questionnaire_user-interface-guide[The custom assessment questionnaire].

IMPORTANT: You can assess only one application at a time.

.Prerequisites

* You are logged in to an {ProductShortName} server.

.Procedure

. In the {ProductShortName} user interface, select the *Migration* view.
. Click *Application inventory* in the left menu bar. A list of the available applications appears in the main pane. 
. Select the application you want to assess.
. Click the *Options* menu ({kebab}) at the right end of the row and select *Assess* from the drop-down menu. 
. From the list of available questionnaires, click *Take* for the desired questionnaire.
. Select *Stakeholders* and *Stakeholder groups* from the lists to track who contributed to the assessment for future reference.
+
NOTE: You can also add *Stakeholder Groups* or *Stakeholders* in the *Controls* pane of the *Migration* view. For more information, see xref:mta-web-seeding-instances_user-interface-guide[Seeding an instance].

. Click *Next*.
. Answer each *Application assessment* question and click *Next*.
. Click *Save and Review* to review the assessment:
.. In the *Review* pane, click *Proposed action* to select the action to perform on the application.
.. Click *Effort estimate* to select the estimated effort to migrate the application.
.. Enter values for *Business criticality* and *Work priority* on a scale of 1 to 10.
.. Enter *Comments* of the assessment.
.. Scroll down to view the *Assessment summary*.
.. Click *Submit review* to save the assessment review.
+
The applications list appears to confirm the status of the application assessment:

* The *In-progess* icon under the *Assessment* column for the application shows that {ProductShortName} is assessing the application.
* The *Completed* icon under the *Assessment* column for the application shows that {ProductShortName} has completed assessing the application.

