// Module included in the following assemblies:
//
// * docs/release_notes/master.adoc

:_content-type: CONCEPT
[id="mta-rn-new-features_{context}"]
= New features and improvements

This section describes the new features and improvements of the {ProductName} ({ProductShortName}) 6.0.0.

.Application inventory module
New application portfolio driven UI that enables organizations to manage and classify their applications using an extensible tagging model.

.Application assessment module
A questionnaire based tool that assesses the suitability of applications for deployment in containers within an enterprise Kubernetes platform, highlighting potential risks that should be considered when deciding which migration strategy to follow.

.Administrator perspective
Dedicated perspective to manage tool-wide configuration, it has a similar approach and design to the OpenShift Administrator Perspective.

.Enhanced RBAC
Three new differentiated personas with different permissions — Administrator, Architect and Migrator.

.Integration with repositories
Full integration with source code (Git, Subversion) and binaries (Maven) repositories to automate the retrieval of applications for analysis.

.Credentials management
Secure store for multiple credential types (source control, Maven settings files, proxy). Credentials are managed by Administrators and assigned by Architects to applications.

.Proxy integration
HTTP and HTTPS proxy configuration can be managed in the {ProductShortName} UI.

.Enhanced analysis modes
Aside from source and binary analysis modes, now {ProductShortName} includes the Source + Dependencies mode that parses the POM file available in the source repository to gather dependencies from corporate or public artifact repositories, adding them to the scope of the analysis.

.Analysis scope selection
Simplified user experience to configure the analysis scope, with the possibility to force the analysis of known Open Source libraries.

.Authless deployment
{ProductShortName} can now be optionally deployed without Keycloak, allowing full unauthenticated admin access to the tool. This is especially useful when deploying the tool in resource constrained environments like local instances of Minikube, where only a single user would have access to it.

.Additional migration paths
New transformation targets have been added to {ProductShortName}:

* OpenJDK 11 to OpenJDK 17
* EAP and Spring Boot applications to Azure App Service

.Seamless upgrades
{ProductShortName} lifecycle is now managed by a new operator with Capability Level II, allowing seamless upgrades between GA versions.

.Transaction report
A new transaction report is now available in the application analysis reports. This new option analyzes the application data layer and provides detailed information about  how transactions propagate across different layers, expressing it as a sequence of service entries, call graphs and SQL statements.

[IMPORTANT]
====
Transaction report is provided as Technology Preview only. Technology Preview features are not supported with Red Hat production service level agreements (SLAs), might not be functionally complete, and Red Hat does not recommend to use them for production. These features provide early access to upcoming product features, enabling customers to test functionality and provide feedback during the development process.

See link:{KBArticleTechnologyPreview}[Technology Preview features support scope] on the Red&nbsp;Hat Customer Portal for information about the support scope for Technology Preview features.
====
