// Module included in the following assemblies:
//
// * docs/release_notes/master.adoc

:_content-type: CONCEPT
[id="rn-new-features-7-0-0_{context}"]
= New features


This section describes the new features of the Migration Toolkit for Applications (MTA) 7.0.0.

.Red Hat Single Sign On (RHSSO) configuration

MTA supports Red Hat Single Sign-On (RHSSO) configuration, so that users' roles can be added using `keycloak`to control Konveyor and MTA authorization mechanisms. See link:https://access.redhat.com/documentation/en-us/migration_toolkit_for_applications/6.0/html/user_interface_guide/mta-6-installing-web-console-on-openshift_user-interface-guide#red_hat_single_sign_on[Red Hat Single Sign-On]. 


.YAML syntax for new rules

New rules using YAML syntax support metadata, `message` and `tag` actions, rule conditions, provider conditions for `java` and `go` providers, and other file tagging and characteristics.


.Filename of downloaded report file matches application name

Downloaded files are now named according to the migrated application.


.Tag Category menu shows only categories relevant to the source

The *Tag Category* drop-down list now shows only tag categories that are relevant to the source.


.Multi-language analysis

MTA 7.0.0 supports migrating applications written in languages implemented in _Language Server Protocol_ (LSP).


.Dynamic reports

MTA 7.0.0 produces dynamic analysis reports that collect aggregated issues and dependencies across the application portfolio, identify portfolio-wide trends, drill down to specific lines in source code, and fully integrate with MTA UI.