// Module included in the following assemblies:
//
// * docs/release_notes/master.adoc

:_content-type: REFERENCE
[id="rn-known-issues-7-0-3_{context}"]
= Known issues

This part provides known issues present in {ProductFullName} version 7.0.3:

.IntelliJ IDE plugin Keymap actions do not work
// Scheduled to be fixed in 7.0.3. Move this to resolved issues once fixed?

The IntelliJ IDE plugin Keymap actions do not work which prevents the {ProductShortName} automation. Currently, there is no workaround available. link:https://issues.redhat.com/browse/MTA-2460[(MTA-2460)]

.Eclipse IDE cannot run the {ProductShortName} analysis

// Get more information
Eclipse IDE cannot run the {ProductShortName} plugin and perform application analysis. Currently, there is no workaround available. link:https://issues.redhat.com/browse/MTA-2563[(MTA-2563)]

.Analysis fails on MacOS
// Moved to resolved issues once fixed?

Running the `analyze` command on a MacOS machine does not work when Podman does not have enough memory. The analysis fails with timeout, without returning an error. 

To workaround this problem, set the Podman memory to at least 4GB. Podman on MacOS sets default memory to 2GB, which is not enough to run {ProductShortName}. link:https://issues.redhat.com/browse/MTA-2518[(MTA-2518)]

.Custom rules do not work during application analysis
// Need more information. I don't really understand what is happening.

Running an application analysis by using a custom rule does not work. Currently, there is no workaround available. link:https://issues.redhat.com/browse/MTA-2015[(MTA-2015)]

.The `Applications` page loads slowly when there are many applications
// Any more information?

When the Application Inventory has to list many applications, the page loads slowly. Currently, there is no workaround available. link:https://issues.redhat.com/browse/MTA-2497[(MTA-2497)]

.Tests fail when the `output.yaml` file is saved to a different directory than the default
// Copied to Resolved issues.

When running a CLI command to analyze an application, the analysis requires saving the `output.yaml` file only in the default directory. Setting the analysis to save `output.yaml` to a different directory causes the analysis to fail and return an error. Currently, there is no workaround available. list:https://issues.redhat.com/browse/MTA-2654[(MTA-2654)] 

For a complete list of all known issues in this release, see the list of link:https://issues.redhat.com/issues/?filter=12434259[Known Issues in Jira].

