// Module included in the following assemblies:
//
// * docs/getting-started-guide/master.adoc
// * docs/cli-guide/master.adoc
// * docs/maven-guide/master.adoc
// * docs/eclipse-code-ready-studio-guide/master.adoc
// * docs/vs-code-extension-guide/master.adoc
// * docs/web-console-guide/master.adoc

[[about_mta]]
:_content-type: CONCEPT
[id="mta-what-is-the-toolkit_{context}"]
= About the {ProductName}

[discrete]
== What is the {ProductName}?

{ProductName} ({ProductShortName}) accelerates large-scale application modernization efforts across hybrid cloud environments on Red Hat OpenShift. This solution provides insight throughout the adoption process, at both the portfolio and application levels: inventory, assess, analyze, and manage applications for faster migration to OpenShift via the user interface.

{ProductShortName} uses an extensive default questionnaire as the basis for assessing your applications, or you can create your own custom questionnaire, enabling you to estimate the difficulty, time, and other resources needed to prepare an application for containerization. You can use the results of an assessment as the basis for discussions between stakeholders to determine which applications are good candidates for containerization, which require significant work first, and which are not suitable for containerization.

{ProductShortName} analyzes applications by applying one or more rulesets to each application considered to determine which specific lines of that application must be modified before it can be modernized.

{ProductShortName} examines application artifacts, including project source directories and application archives, and then produces an HTML report highlighting areas needing changes.


[discrete]
== How does the {ProductName} simplify migration?

The {ProductName} looks for common resources and known trouble spots when migrating applications. It provides a high-level view of the technologies used by the application.

{ProductShortName} generates a detailed report evaluating a migration or modernization path. This report can help you to estimate the effort required for large-scale projects and to reduce the work involved.
