// Module included in the following assemblies:
//
// * docs/release_notes/master-6-1-0.adoc

:_content-type: CONCEPT
[id="mta-rn-new-features-6-1-0_{context}"]
= New features and improvements

This section describes the new features and improvements of the {ProductName} ({ProductShortName}) {ProductVersion}.

.Creating custom migration targets
Administrators and architects can create and maintain custom migration targets and populate them with custom rules from a repository. Such custom migration targets are available for use by non-admin users. This simplifies the process of  analysis configuration for applications with similar technologies that are common across the entire application portfolio of an organization.

.Automated tagging of resources
MTA uses the technology stack information that the analysis module collects during an analysis to generate tags and to attach them automatically to applications.

.Downloading HTML and CSV analysis reports
Users can download HTML and CSV reports generated by application analysis. By default, this option is disabled; it can be enabled in the new *General* menu in *Administration* view.

.Reviewing an application without an assessment
Architects can review applications without running assessments first. By default, this option is disabled; it can be enabled in the new *General* menu in *Administration* view.

.Support for disconnected installation
{ProductShortName} fully supports disconnected installation in air-gapped {ocp-short} environments.

.Changes in naming
Some entities and menu entries of the {ProductShortName} {WebName} have been renamed for clarity. The *Administrator* and *Developer* views have been renamed to *Administration* and *Migration*, respectively. *Tag Types* are now named *Tag Categories*.



