// Module included in the following assemblies:
//
// * docs/web-console-guide/master.adoc

:_content-type: PROCEDURE
[id="mta-6-installing-web-console-on-openshift_{context}"]

= Installing the {ProductName} {WebName}

You install the {ProductName} ({ProductShortName}) {WebName} as part of the process of installing the {ProductShortName} Operator on the OpenShift Container Platform.

The {ProductShortName} Operator is a structural layer that manages resources deployed on Kubernetes (database, front end, back end) to automatically create an {ProductShortName} instance instead of you doing it manually.

== Persistent volume requirements

The {ProductShortName} Operator requires a total of 5 persistent volumes (PVs) used by different components to successfully deploy, 3 RWO volumes and 2 RWX volumes that are requested via PVCs. The 5 PVs are described in the table below:

.Required persistent volumes
[cols="25%,25%,25%,25%", options="header"]
|====
|Name
|Default size
|Access mode
|Description

|`hub database`
|5 GiB
|RWO
|Hub database

|`hub bucket`
|100 GiB
|RWX
|Hub file storage

|`keycloak postgresql`
|1 GiB
|RWO
|Keycloak back end database

|`pathfinder postgresql`
|1 GiB
|RWO
|Pathfinder back end database

|`maven`
|100 GiB
|RWX
|Maven m2 repository
|====

== Installing the {ProductName} Operator and the {WebName}

You can install the {ProductName} ({ProductShortName}) and the {WebName} on OpenShift Container Platform versions 4.9-4.11 when you install the {ProductName} Operator.

.Prerequisites

* 4 vCPUs, 8 GB RAM, and 40 GB persistent storage.
* OpenShift Container Platform 4.9-4.11 installed.
* You must be logged in as a user with `cluster-admin` permissions.

.Procedure

. In the OpenShift Container Platform web console, click *Operators → OperatorHub*.
. Use the *Filter by keyword* field to search for *MTA*.
. Click the *Migration Toolkit for Applications* Operator and then click *Install*.
. On the *Install Operator* page, click *Install*.
. Click *Operators → Installed Operators* to verify that the {ProductShortName} Operator appears in the `openshift-mta` project with the status `Succeeded`.
. Click the *{ProductShortName}* Operator.
. Under *Provided APIs*, locate *Tackle*, and click *Create Instance*.
+
The *Create Tackle* window opens in *Form* view.
. Review the CR settings. The default choices should be acceptable, but make sure to check the system requirements for storage, memory, and cores.
. If you prefer to work directly with the YAML file, click *YAML* view and review the CR settings that are listed in the `spec` section of the YAML file.
+
The most commonly used CR settings are listed in this table:
+
.Tackle CR settings
[cols="40%,15%,55%", options="header"]
|====
|Name
|Default
|Description

|`feature_auth_required`
|True
|Flag to indicate whether keycloak authorization is required (single user/"`noauth`")

|`feature_isolate_namespace`
|True
|Flag to indicate whether namespace isolation using network policies is enabled

|`hub_database_volume_size`
|5 GiB
|Size requested for the Hub database volume

|`hub_bucket_volume_size`
|100 GiB
|Size requested for the Hub bucket volume

|`keycloak_database_data_volume_size`
|1 GiB
|Size requested for the Keycloak database volume

|`pathfinder_database_data_volume_size`
|1 GiB
|Size requested for the Pathfinder database volume

|`maven_data_volume_size`
|100 GiB
|Size requested for the Maven m2 repository volume

|`rwx_storage_class`
|NA
|Storage class requested for the Tackle RWX volumes

|`rwo_storage_class`
|NA
|Storage class requested for the Tackle RW0 volumes
|====

. Edit the CR settings if needed, and then click *Create*.
. In *Administrator* view, click *Workloads -> Pods* to verify that the MTA pods are running.
. Access the {WebName} from your browser by using the route exposed by the `{LC_PSN}-web-console` application within OpenShift.
. Use the following credentials to log in:
** *User name*: admin
** *Password*: Passw0rd!
. When prompted, create a new password.

== Memory requirements for running {ProductShortName} on Red Hat OpenShift Local

When installed on https://developers.redhat.com/products/openshift-local/overview[Red Hat OpenShift Local], {ProductShortName} requires a minimum amount of memory to complete its analysis. Adding memory above the required minimum makes the analysis process run faster. The table below describes the {ProductShortName} performance with varying amounts of memory.

.OpenShift Local {ProductShortName} memory requirements
[cols="25%,75%", options="header"]
|====
|Memory (GB)
|Description


|`10`
|{ProductShortName} cannot run the analysis due to insufficient memory

|`11`
|{ProductShortName} cannot run the analysis due to insufficient memory

|`12`
|*{ProductShortName} works and the analysis is completed in approximately 3 minutes*

|`15`
|{ProductShortName} works and the analysis is completed in less than 2 minutes

|`20`
|{ProductShortName} works quickly and the analysis is completed in less than 1 minute
|====

The test results indicate that the minimum amount of memory for running {ProductShortName} on OpenShift Local is *12 GB*.

[NOTE]
====
** The tests were performed by running the {ProductShortName} binary analysis through the {WebName}.
** All the analyses used the `tackle-testapp` binary.
** All the tests were conducted on an OpenShift Local cluster without the monitoring tools installed.
** Installing the cluster monitoring tools requires an additional 5 GB of memory.
====

== Eviction Threshold

A node running applications requires enough reserve memomory. An application can trigger an out-of-memory event when it uses more than its reserved memory.

The `--eviction-hard` flag directs the node to evict applications when available memory drops below an absolute value or percentage. Set `--eviction-hard` along with memory reserves for the node.

The following example illustrates node memory allocation settings:
* Node capacity: `32 Gi`
* `--system-reserved` setting: `3 Gi`
* `--eviction-hard` setting: `100 Mi`

This node has 28.9 Gi of effective memory available (32 Gi - 3 Gi - 0.1 Gi) before the `--eviction-hard` setting starts to evict applications that are using too much memory.