// Module included in the following assemblies:
//
// * docs/release_notes-7.0/master.adoc

:_content-type: REFERENCE
[id="mta-rn-upgrade-notes-7-0-0_{context}"]
= Upgrade notes

The following are upgrade notes for {ProductFullName}

.Hub database volume size

In version 7.0.0 of {ProductShortName}, the default size of the hub database volume has been increased to 10GiB.

If your storage class does not support volume expansion, then an upgrade from 6.2.1 to 7.0.0 will result in a failure due to the operator trying to change the volume size from 5GiB to 10GiB.

To avoid this issue, you can directly set the volume size by setting:

[source,yaml]
----
...
hub_database_volume_size: 5Gi
...
----

By doing this, you will avoid the operator trying to resize the volume.

If this value was set when the previous version was deployed, there is no need to take any action, as it will work as expected.


.Existing data

When upgrading to {ProductShortName} 7.0.0, all existing data will be retained, except for individual analysis reports for applications.

As both the analysis and reporting engines have been replaced with this version, you will be required to conduct a re-run of the analysis in order to obtain data on issues and dependencies.


.Version upgrade

You can upgrade to {ProductShortName} 7.0.0 from 6.2.1. It is not recommended to pursue any alternative upgrade route. If you wish to upgrade from a previous version, it is recommended to proceed in a sequential manner until you finally upgrade from {ProductShortName} version 6.2.1 to 7.0.0.
