// Module included in the following assemblies:
//
// * docs/web-console-guide/master.adoc

:_content-type: PROCEDURE
[id="mta-web-assessing-apps_{context}"]
= Assessing an application

You can estimate the risks and costs involved in preparing applications for containerization by performing application assessment. You can assess an application and display the currently saved assessments by using the Assessment module.

The {ProductFullName} assesses applications according to a set of questions relevant to the application, such as dependencies.

To assess the application, you can use the default xref:mta-default-questionnaire_user-interface-guide[Legacy Pathfinder] {ProductShortName} questionnaire or import your xref:mta-custom-questionnaire_user-interface-guide[custom] questionnaires.

IMPORTANT: You can assess only one application at a time.

.Prerequisites

* You are logged in to an {ProductShortName} server.

.Procedure

. In the {ProductShortName} user interface, select the *Migration* view.
. Click *Application inventory* in the left menu bar. A list of the available applications appears in the main pane. 
. Select the application you want to assess.
. Click the *Options* menu ({kebab}) at the right end of the row and select *Assess* from the drop-down menu. 
. From the list of available questionnaires, click *Take* for the desired questionnaire.
. Select *Stakeholders* and *Stakeholder groups* from the lists to track who contributed to the assessment for future reference.
+
NOTE: You can also add *Stakeholder Groups* or *Stakeholders* in the *Controls* pane of the *Migration* view. For more information, see xref:mta-web-seeding-instances_user-interface-guide[Seeding an instance].

. Click *Next*.
. Answer each *Application assessment* question and click *Next*.
. Click *Save* to review the assessment and proceed with the steps in xref:mta-web-reviewing-apps_user-interface-guide[Reviewing an application].

[role="_additional-resources"]
.Additional resources
* xref:mta-default-questionnaire_user-interface-guide[The default assessment questionnaire]
* xref:mta-custom-questionnaire_user-interface-guide[The custom assessment questionnaire]
* xref:managing-mta-questionnaires_user-interface-guide[Managing assessment questionnaires]

