// Module included in the following assemblies:
//
// * docs/release_notes/master.adoc

:_content-type: CONCEPT
[id="rn-new-features-1-2-0_{context}"]
= New features

This section describes the new features of the {ProductName} ({ProductShortName}) 1.2.0.

. Decompile and analyze Java 17 based applications
. Rules Override enhancement: introduced a further degree of selectivity so that a rule will only be overridden if `rulesetId` and `ruleId` match and the target of the override ruleset matches the target provided for the analysis
. Eclipse Plugin Java 17 compatibility
. Upgrade of the Windup Operator: it adopted `Quarkus 2.13.7.Final` and the `Quarkus Operator SDK 4.0.8`

[id="rn-new-rulesets-targets-1-2-0"]
== New rulesets and targets

. Java/Jakarta EE to Quarkus: New rules and recipes to support this migration path to Quarkus 3
. More migration rules to support Red Hat JBoss EAP 8, Hibernate 6, and Red Hat JBoss EAP XP5
. Red Hat Java Web Server 6: support the upgrade of JWS / Tomcat applications to JWS 6 / Tomcat 10
. Camel 4: Comprehensive rulesets supporting upgrade to all Y stream releases of Camel 3 and to Camel 4