// Module included in the following assemblies:
//
// * docs/release-notes-mtr/mtr_release_notes-1.0/master.adoc

:_content-type: REFERENCE
[id="mtr-rn-resolved-issues-1-2-5_{context}"]
= Resolved issues

{ProductName} ({ProductShortName}) 1.2.5 resolves the following issues:

.CVE-2024-25710 commons-compress: Denial of service caused by an infinite loop

A loop with an unreachable exit condition, meaning an Infinite Loop, vulnerability, was found in Apache Common Compress. This issue could have led to a denial of service. This issue affects Apache Commons Compress: from 1.3 through 1.25.0. Users are recommended to upgrade to {ProductShortName} 1.2.5, which resolves this issue.

For more details, see link:https://access.redhat.com/security/cve/CVE-2024-25710[(CVE-2024-25710)].

.CVE-2024-26308 commons-compress: OutOfMemoryError

An allocation of resources without limits or throttling vulnerability was found in Apache Commons Compress. This issue could lead to an out-of-memory error (OOM). This issue affects Apache Commons Compress, from 1.21 to 1.26. Users are recommended to upgrade to {ProductShortName} 1.2.5, which resolves this issue.

For more details, see link:https://access.redhat.com/security/cve/CVE-2024-26308[(CVE-2024-26308)].

.CVE-2024-1300: A vulnerability in the Eclipse Vert.x toolkit causes a memory leak in TCP servers configured with TLS and SNI support

A vulnerability in the Eclipse Vert.x toolkit causes a memory leak in Transmission Control Protocol (TCP) servers configured with TLS and SNI support. When processing an unknown Server Name Indication (SNI) server name assigned the default certificate instead of a mapped certificate, the Secure Sockets Layer (SSL) context is erroneously cached in the server name map, leading to memory exhaustion. This affects only TLS servers with SNI enabled. Users are recommended to upgrade to {ProductShortName} 1.2.5, which resolves this issue.

For more details, see link:https://access.redhat.com/security/cve/CVE-2024-1300[(CVE-2024-1300)].


// filter changed to:
// project in (WINDUP, WINDUPRULE) AND issuetype = Bug AND fixVersion = MTR-1.2.5 ORDER BY  id

For a complete list of all issues resolved in this release, see the list of link:https://issues.redhat.com/issues/?filter=12434315[MTR 1.2.5 resolved issues] in Jira.
