// Module included in the following assemblies:
//
// * docs/rules-development-guide/master.adoc

:_content-type: PROCEDURE
[id="validation-report-understanding_{context}"]
= Creating a validation report

You can create a validation report for your custom rules.

.Prerequisites

* You must fork and clone the {ProductShortName} XML rules.
* You must have one or more test XML rules to validate.

.Procedure

. Navigate to the local `windup-rulesets` repository.

. Create a directory for your custom rules and tests: `windup-rulesets/rules-reviewed/myTests`.

. Copy your custom rules and tests to the `windup-rulesets/rules-reviewed/<myTests>` directory.

. Run the following command from the root directory of the `windup-rulesets` repository:
+
----
$ mvn -Dtest=WindupRulesMultipleTests -DrunTestsMatching=<myTests> clean <myReport>:report <1> <2>
----
<1> Specify the directory containing your custom rules and tests. If you omit the `-DrunTestsMatching` argument, the validation report will include all the tests and take much longer to generate.
<2> Specify your report name.
+
The validation report is created in the `windup-rulesets/target/site/` repository.
