// Module included in the following assemblies:
//
// * docs/release-notes-mtr/master.adoc

:_content-type: REFERENCE
[id="mtr-rn-known-issues-1-2-5_{context}"]

= Known issues

The following are major known issues:

.NPE in MTR when application is submitted for anlysis

The package discovery fails due to a Null Pointer Exception (MPE). link:https://issues.redhat.com/browse/WINDUP-4116[(WINDUP-4116)]

.Triggering analysis gets stuck when the target is OpenJDK21

When triggering an anlysis on OpenJDK11 to OpenJDK21, the analysis gets stuck. link:https://issues.redhat.com/browse/WINDUP-4097[(WINDUP-4097)]

.Broken links in Integration test

Links are broken when running the Integration test.link:https://issues.redhat.com/browse/WINDUPRULE-1039[(WINDUPRULE-1039)]

.Generated report cannot open in Eclipse IDE

Eclipse IDE cannot open reports generated from {ProductShortName} 6.3.0, {ProductShortName} CLI 1.2.0, and Eclipse 2023-06. link:https://issues.redhat.com/browse/WINDUP-4043[(WINDUP-4043)]

.`--legacyReports` option is always on in VSCode

`--legacyReports` option is always on in VScode when running {ProductShortName} 6.2.0. This prevents viewing the `PatternFly 4` style pattern reports. link:https://issues.redhat.com/browse/WINDUP-3962[(WINDUP-3962)]

// Is this MTA or MTR?
.Spawn ENOENT error when MTA runs VSCode plugin

When running MTA on a Java project, a Spawn ENOENT error is reported. link:https://issues.redhat.com/browse/WINDUP-3887[(WINDUP-3887)]

.PF4 analysis report is empty

The generated `PF4` analysis report is empty when using `mtr-vdcode-extension-1.1.0-556.vsix` plugin on Eclipse Che. link:https://issues.redhat.com/browse/WINDUP-3885[(WINDUP-3885)]

.link:[()]

For a complete list of all known issues, see the list of link:https://issues.redhat.com/issues/?filter=12432747[MTR 1.2.5 known issues] in Jira.


