// Module included in the following assemblies:
//
// * docs/release-notes-mtr/mtr_release_notes-1.2/master.adoc

:_content-type: REFERENCE
[id="mtr-rn-resolved-issues-1-2-6_{context}"]
= Resolved issues

{ProductName} ({ProductShortName}) 1.2.6 resolves the following issues:

.CVE-2023-45857: Axios 1.5 exposes confidential data stored in cookies

A flaw was discovered in Axios 1.5.1 that accidentally revealed the confidential `XSRF-TOKEN` stored in cookies by including it in the HTTP header `X-XSRF-TOKEN` for every request made to any host, thereby allowing attackers to view sensitive information. Users are recommended to upgrade to {ProductShortName} 1.2.6, which resolves this issue.

For more details, see link:https://access.redhat.com/security/cve/CVE-2023-45857[(CVE-2023-45857)].


.CVE-2024-28849: `follow-redirects` package clears authorization headers

A flaw was discovered in the `follow-redirects` package, which clears authorization headers, but it fails to clear the `proxy-authentication` headers. This flaw could lead to credential leakage, which could have a high impact on data confidentiality.
Users are recommended to upgrade to {ProductShortName} 1.2.6, which resolves this issue.

For more details, see link:https://access.redhat.com/security/cve/CVE-2024-28849[(CVE-2024-28849)]


For a complete list of all issues resolved in this release, see the list of link:https://issues.redhat.com/issues/?filter=12435317[MTR 1.2.6 resolved issues] in Jira.
