// Module included in the following assemblies:
//
// * docs/getting-started-guide/master.adoc

:_content-type: CONCEPT
[id="new-mta-features_{context}"]
= {ProductShortName} Features

{ProductName} ({ProductShortName}) is an integrated assembly of tools that  lets you better assess, prioritize and modernize your applications across hybrid cloud environments on Red Hat OpenShift, the industry’s leading Kubernetes platform.

Now designed for easier upgrades with more migration paths, {ProductShortName} includes:

* *New application inventory and assessment modules* that assist organizations in managing, classifying and tagging their applications while assessing application suitability for deployment in containers, including flagging potential risks for migration strategies.

* *Full integration with source code and binary repositories* to automate the retrieval of applications for analysis along with proxy integration including HTTP and HTTPS proxy configuration managed in the user interface.

* *Improved analysis capabilities* with new analysis modes, including source and dependency modes that parse repositories to gather dependencies and add them to the overall scope of the analysis. There is also a simplified user experience to configure the analysis scope, including open source libraries.

* *Enhanced Role-Based Access Control (RBAC)* powered by link:https://access.redhat.com/products/red-hat-single-sign-on[Red Hat Single Sign-On], defining three new differentiated personas with different permissions to suit the needs of each user (administrator, architect and migrator) including credentials management for multiple credential types.

* *Administration perspective* to provide tool-wide configuration management for administrators.
