// Module included in the following assemblies:
//
// * docs/getting-started-guide/master.adoc

:_content-type: CONCEPT
[id="new-mta-features_{context}"]
= The {ProductShortName} features

{ProductFullName} provides the following features to simplify upgrades with more migration paths:

* *New application inventory and assessment modules* to assist organizations in managing, classifying, and tagging their applications while assessing application suitability for deployment in containers, including flagging potential risks for migration strategies.

* *Full integration with source code and binary repositories* to automate the retrieval of applications for analysis along with proxy integration, including HTTP and HTTPS proxy configuration managed in the user interface.

* *Improved analysis capabilities* with new analysis modes, including source and dependency modes that parse repositories to gather dependencies and add these dependencies to the overall scope of the analysis. You can also use a simplified user experience to configure the analysis scope, including open source libraries.

* *Enhanced Role-Based Access Control (RBAC)* powered by link:https://access.redhat.com/products/red-hat-single-sign-on[Red Hat Single Sign-On] to define new differentiated personas (administrator, architect, and migrator) with different permissions to suit the needs of each user, including credentials management for multiple credential types.

* *Administration perspective* to provide tool-wide configuration management for administrators.

* *Support for Red Hat OpenShift on AWS (ROSA)* is introduced in {ProductShortName} 7.0.0.

* *Support added for Azure Red Hat OpenShift (ARO)* is introduced in {ProductShortName} 7.0.0.
