[[install_plugin]]
= Install the {PluginNameTitle}

Review the xref:supported_configs[supported configurations] to make sure that you are using a development environment that is compatible with the {PluginName}.

NOTE: If you are running macOS, it is recommended to set the maximum number of user processes, `maxproc`, to at least `2048`, and the maximum number of open files, `maxfiles`, to `100000`.

If you do not already have an existing installation, download link:http://www.eclipse.org/downloads/[Eclipse] or link:https://developers.redhat.com/products/codeready-studio/download/[Red Hat CodeReady Studio] and install it.

[NOTE]
--
This guide uses _IDE_ to refer to an installation of Eclipse or Red Hat Red Hat CodeReady Studio.

A Minimum Viable Product release of a {ProductShortName} extension for Visual Studio Code and Eclipse Che is available in this release.
The extension contains all of the core features required to perform a {ProductShortName} analysis in your development environment.
For more information about link:https://marketplace.visualstudio.com/items?itemName=redhat.rhamt-vscode-extension[the extension], visit the Visual Studio Markteplace.
Note, that this release of the {ProductShortName} extension for Visual Studio Code and Eclipse Che is a Minimum Viable Product release, and is still in development.
--


.Prerequisites

* If you are using Eclipse, and not Red Hat CodeReady Studio, then you must xref:install_jboss_tools[install JBoss Tools] before installing the {PluginNameTitle}.

.Install the Plugin

. Launch Eclipse.
. From the menu bar, select *Help* -> *Install New Software*.
. Add the {ProductShortName} update site.
.. Next to the *Work with* field, click *Add*.
.. In the *Name* field, enter `{ProductShortName}`.
.. In the *Location* field, enter [x-]`http://download.jboss.org/jbosstools/photon/stable/updates/rhamt/` and press *OK*.
.. Select all of the checkboxes under *JBoss Tools - RHAMT* and press *Next*.
. Review the installation details and press *Next*.
. Accept the terms of the license agreement and press *Finish* to install the plugin.
. Restart your IDE for the changes to take effect.

.Install the Plugin for an Offline Environment

. Download the link:{ProductDownloadURL}{IDEPluginFilename}-{ProductVersion}.zip[IDE Plugin Repository].
. Launch your IDE.
. From the menu bar, select *Help* -> *Install New Software*.
. Add the {ProductShortName} update site.
.. Next to the *Work with* field, click *Add*.
.. In the *Name* field, enter `{ProductShortName} - Offline`.
.. Next to the *Location* field, click *Archive*.
.. Select the file downloaded in the first step and click *OK*.
.. Select all of the checkboxes under *JBoss Tools - RHAMT* and press *Next*.
. Review the installation details and press *Next*.
. Accept the terms of the license agreement and press *Finish* to install the plugin.
. Restart your IDE for the changes to take effect.
