// Module included in the following assemblies:
//
// * docs/web-console-guide/master.adoc

[id="proc_reporting-issues_{context}"]
= Reporting issues

[role="_abstract"]
You can report an issue in the Jira Red Hat Issue Tracker.

[NOTE]
====
You must sign up for a Jira account in order to create an issue.
====

.Procedure

. Open a browser and navigate to the Jira link:https://issues.jboss.org/secure/CreateIssue!default.jspa[Create Issue] page.
. Click *Log In* on the upper right of the page and enter your credentials.
. Select the following options and click *Next*.

* *Project*: `{ProductName} (WINDUP)`
* *Issue Type*: `Bug`

. On the next screen complete the following fields:

* *Summary*: Enter a brief description of the problem or issue.
* *Environment*: Indicate that this is an OpenShift Container Platform installation of the {WebName}, and include any environment variables in use with the image.
* *Description*: Provide a detailed description of the issue. Be sure to include any errors encountered and exception traces.
* *Attachment*: Include the logs. At a minimum this should include the logs from each pod.
+
If the application or archive causing the issue does not contain sensitive information and you are comfortable sharing it with the {ProductShortName} development team, attach it to the issue using the *Browse* button.

. Click *Create* to create the Jira issue.
