// Module included in the following assemblies:
//
// * docs/rules-development-guide/master.adoc

:_content-type: PROCEDURE
[id="review-existing-rules_{context}"]
= Reviewing existing {ProductShortName} XML rules

{ProductShortName} XML-based rules are located on GitHub at the following location: link:https://github.com/windup/windup-rulesets/tree/master/rules/rules-reviewed[https://github.com/windup/windup-rulesets/tree/master/rules/rules-reviewed].

You can fork and clone the {ProductShortName} XML rules on your local machine.

Rules are grouped by target platform and function. When you create a new rule, it is helpful to find a rule that is similar to the one you need and use it as a starting template.

{ProductShortName} YAML rules are replacing the XML rules. See  are being replaced occasionally added, so it is a good idea to check back frequently to review the updates.

[NOTE]
====
.Existing {ProductShortName} rules YAML rule files

YAML-base rules are in the process of replacing the XML-based. 

Comparable `.yaml` rule files are available for most `.xml` rules. 

A GitHub repository stores these YAML-based rules at the following location: link:https://github.com/konveyor/rulesets/tree/main/default/generated[https://github.com/konveyor/rulesets/tree/main/default/generated].

The numbered YAML rule files are grouped according to target platform. When you create a new rule, it is helpful to find a rule that is similar to the one you need and use it as a starting template. 

The repository may show newly added YAML rule files, so it is a good idea to check back occasionally to review the updates.
====