[[Review-the-Quickstarts]]
= Review the {ProductName} Quickstarts

The {ProductName} quickstarts provide working examples of how to create custom Java-based rule add-ons and XML rules. You can use them as a starting point for creating your own custom rules. 

You can download a ZIP file of the latest released version of the quickstarts. Or, if you prefer to play around with the source code, you can fork and clone the windup-quickstarts project repository.

== Download the Latest Quickstart ZIP

. Open a browser and navigate to https://github.com/windup/windup-quickstarts/releases.
. Click on the most recent release to download the ZIP file to your local file system.

== Fork and Clone the Quickstart GitHub Project

If you do not have the GitHub client (`git`), download it from link:http://git-scm.com/[] and install it.

. Click the `Fork` link on the https://github.com/windup/windup-quickstarts/[{ProductName} quickstart] GitHub page to create the project in your own Git. The forked GitHub repository URL created by the fork should look like this: https://github.com/YOUR_USER_NAME/windup-quickstarts.git
. Clone your {ProductName} quickstart repository to your local file system:
+
[options="nowrap"]
----
$ git clone https://github.com/YOUR_USER_NAME/windup-quickstarts.git
----
. This creates and populates a `windup-quickstarts` directory on your local file system. Navigate to the newly created directory, for example 
+
[options="nowrap"]
----
$ cd windup-quickstarts/
----
. If you want to be able to retrieve the lates code updates, add the remote `upstream` repository so you can fetch any changes to the original forked repository.
+
[options="nowrap"]
----
$ git remote add upstream https://github.com/windup/windup-quickstarts.git
----
. To get the latest files from the `upstream` repository.
+
[options="nowrap"]
----
$ git reset --hard upstream/master
----

