// Module included in the following assemblies:
//
// * docs/rules-development-guide/master.adoc

:_content-type: PROCEDURE
[id="review-existing-rules_{context}"]
= Reviewing existing {ProductShortName} XML rules

{ProductShortName} XML-based rules are located on GitHub at the following location: link:https://github.com/windup/windup-rulesets/tree/master/rules/rules-reviewed[https://github.com/windup/windup-rulesets/tree/master/rules/rules-reviewed].

You can fork and clone the {ProductShortName} XML rules on your local machine.

Rules are grouped by target platform and function. When you create a new rule, it is helpful to find a rule that is similar to the one you need and use it as a starting template.

New XML rules are occasionally added, so it is a good idea to check back frequently to review the updates.

[NOTE]
====
.Existing {ProductShortName} rules `.yaml` files

XML rules are in the process of being replaced with newer YAML rules. 

Most of the `.xml` rules files have been converted to comparable `.yaml` rule files. 

These YAML-based rules are located on GitHub at the following location: link:https://github.com/konveyor/rulesets/tree/main/default/generated[https://github.com/konveyor/rulesets/tree/main/default/generated].

The rules are numbered and grouped according to target platform. When you create a new rule, it is helpful to find a rule that is similar to the one you need and use it as a starting template. 

New YAML rules are continuously added, so it is a good idea to check back frequently to review the updates.
====