// Module included in the following assemblies:
//
// * docs/release_notes-5.0/master.adoc

[id='rn-new-features_{context}']
= New features

This section describes the new features of the {ProductName} ({ProductShortName}) {ProductVersion}.

.MTA plugin for IntelliJ IDEA

The current release supports the {ProductName} plugin for IntelliJ IDEA. The plugin provides assistance directly in IntelliJ IDEA for developers making changes for a migration or modernization effort.

The plugin is available through the link:https://plugins.jetbrains.com[IntelliJ marketplace].

.Rules for migrating from JBoss EAP 7.3 to 7.4

The current release contains rules for migrating from JBoss EAP 7.3 to 7.4. The target of these rules is `eap:7`.

.Rules for migrating from JBoss EAP XP 2 to 3

The current release contains rules for migrating from JBoss EAP XP 2 to 3 The target of these rules is `eapxp:3`.

[NOTE]
====
Rules for migrating from Thorntail to JBoss EAP XP 2 have been included since version 5.1.4. The target of these rules is `eapxp:2`.
====
