// Module included in the following assemblies:
//
// * docs/release_notes/master.adoc

:_content-type: CONCEPT
[id="rn-new-features_{context}"]
= New features

This section describes the new features of the {ProductName} ({ProductShortName}) {ProductVersion}.

[IMPORTANT]
====
Rules for migrating from Java EE8 to Jakarta EE9 and OpenRewrite support are both provided as Technology Preview only. Technology Preview features are not supported with Red Hat production service level agreements (SLAs), might not be functionally complete, and Red Hat does not recommend to use them for production. These features provide early access to upcoming product features, enabling customers to test functionality and provide feedback during the development process.

See link:{KBArticleTechnologyPreview}[Technology Preview features support scope] on the Red&nbsp;Hat Customer Portal for information about the support scope for Technology Preview features.
====

.Rules for migrating from Java EE8 to Jakarta EE9
{ProductShortName} rules replace Java EE8 artifact dependencies and package import statements and rename XML schema namespaces, prefixed properties, and bootstrapping files for Jakarta EE9. You run these rules by specifying the `jakarta-ee` target.

.OpenRewrite recipe support

link:https://docs.openrewrite.org/[OpenRewrite] automates large-scale, distributed source code refactoring. You can run OpenRewrite recipes by using the link:{ProductDocUserGuideURL}[{ProductShortName} CLI].

The recipe `org.jboss.windup.JavaxToJakarta` renames imported `javax` packages to their `jakarta` equivalents.

.MTA extension for Visual Studio Code compatible with Codespaces

The {ProductShortName} extension for Microsoft Visual Studio Code is now compatible with Microsoft Visual Studio Codespaces.

.Rules for the Springboot-to-Quarkus migration path

Rulesets identify Quarkus-supported technologies by detecting a POM dependency, embedded JAR file, or a partial file path within an Apache Maven Shade uber JAR.

The rules identify the following technologies:

* Apicurio Studio
* Flyway
* Liquibase
* Liquibase for MongoDB
* OpenTelemetry
* Picocli
