[[Rules-XML-Rule-When-Condition-Syntax]]
= When Condition Syntax

Conditions allowed in the `when` portion of a rule must extend http://windup.github.io/windup/docs/latest/javadoc/org/jboss/windup/config/operation/GraphOperation.html[GraphOperation] and currently include evaluation of Java classes, XML files, projects, and file content. Because XML rules are modeled after the Java-based rule add-ons, links to JavaDocs for the related Java classes are provided for a better understanding of how they behave. 

The complete XML rule schema is located here: http://windup.jboss.org/schema/windup-jboss-ruleset.xsd

The following sections describe the more common XML `when` rule conditions. 

* xref:javaclass-syntax[<javaclass> condition syntax]
* xref:xmlfile-syntax[<xmlfile> condition syntax]
* xref:project-syntax[<project> condition syntax]
* xref:filecontent-syntax[<filecontent> condition syntax]
* xref:file-syntax[<file> condition syntax]

[[javaclass-syntax]]
== <javaclass> Syntax

=== Summary 

Use the `<javaclass>` element to find imports, methods, variable declarations, annotations, class implementations, and other items related to Java classes. For a better understanding of the `<javaclass>` condition, see the JavaDoc for the http://windup.github.io/windup/docs/latest/javadoc/org/jboss/windup/rules/apps/java/condition/JavaClass.html[JavaClass] class.

The following is an example of a rule that tests for WebLogic-specific Apache XML packages.
[source,xml,options="nowrap"]
----
<rule id="weblogic-03000">
    <when>
        <javaclass references="weblogic.apache.xml.{*}" />
    </when>
    <perform>
        <hint title="WebLogic Specific Apache XML Package" effort="1" severity="mandatory">
            <message>
                Code using this package should be replaced with code using the org.apache.xml package from [Apache
                Xerces](http://xerces.apache.org/).
            </message>
        </hint>
    </perform>
</rule>
----

=== Construct a <javaclass> Element

==== <javaclass> Element Attributes

[cols="1,1,3", options="header"] 
|====
|Attribute Name
|Type
|Description

|references
|CLASS_NAME
a|The package or class name to match on. Wildcard characters can be used.

TIP: For performance reasons, you should not start the reference with wildcard characters. For example, use [x-]`weblogic.apache.xml.{*}` instead of [x-]`{web}.apache.xml.{*}`.  

_Example:_
[options="nowrap"]
----
references="weblogic.apache.xml.{*}"
----
|matchesSource
|STRING
a|An exact regex to match. This is useful to distinguish hard-coded strings.

_Example:_

[options="nowrap"]
----
matchesSource="log4j.logger"
----

|as
|VARIABLE_NAME
a|A variable name assigned to the rule so that it can be used as a reference in later processing. See the `from` attribute below. (Optional)

_Example:_

[options="nowrap"]
----
as="MyEjbRule"
----

|from
|VARIABLE_NAME
a|Begin the search query with the filtered result from a previous search identified by its `as` VARIABLE_NAME. (Optional)

_Example:_

[options="nowrap"]
----
from="MyEjbRule"
----

|in
|PATH_FILTER
a|Used to filter input files matching this regex (regular expression) naming pattern. Wildcard characters can be used. (Optional)

_Example:_
[options="nowrap"]

----
in="{*}File1"
----

|====

==== <javaclass> Child Elements

[cols="1,4", options="header"] 
|====
|Child Element
|Description

|<location>
a|The location where the reference was found in a Java class. Location can refer to annotations, field and variable declarations, imports, and methods. For the complete list of valid values, see the JavaDoc for http://windup.github.io/windup/docs/latest/javadoc/org/jboss/windup/ast/java/data/TypeReferenceLocation.html[TypeReferenceLocation].

_Example:_

[source,xml,options="nowrap"]
----
<location>IMPORT</location>
----

|<annotation-literal>
a|Match on literal values inside of annotations.

The below example would match on `@MyAnnotation(myvalue="test")`.

[source,xml,options="nowrap"]
----
<javaclass references="org.package.MyAnnotation">
    <location>ANNOTATION</location>
    <annotation-literal name="myvalue" pattern="test"/>
</javaclass>
----

Note that in this case, the `<javaclass>` refers to an annotation (`@MyAnnotation`), so the top-level annotation filter, `<annotation-literal>` must specify the `name` attribute. If the `<javaclass>` referred to a class that is annotated, then the top-level annotation filter used would be `<annotation-type>`.

|<annotation-type>
a|Match on a particular annotation type. You can supply subconditions to be matched against the annotation elements.

The below example would match on a `Calendar` field declaration annotated with `@MyAnnotation(myvalue="test")`.

[source,xml,options="nowrap"]
----
<javaclass references="java.util.Calendar">
    <location>FIELD_DECLARATION</location>
    <annotation-type pattern="org.package.MyAnnotation">
        <annotation-literal name="myvalue" pattern="test"/>
    </annotation-type>
</javaclass>
----

|<annotation-list>
a|Match on an item in an array within an annotation. If an array index is not specified, the condition will be matched if it applies to any item in the array. You can supply subconditions to be matched against this element. 

The below example would match on `@MyAnnotation(mylist={"one","two"})`.

[source,xml,options="nowrap"]
----
<javaclass references="org.package.MyAnnotation" >
    <location>ANNOTATION</location>
    <annotation-list name="mylist">
        <annotation-literal pattern="two"/>
    </annotation-list>
</javaclass>
----

Note that in this case, the `<javaclass>` refers to an annotation (`@MyAnnotation`), so the top-level annotation filter, `<annotation-list>` must specify the `name` attribute. If the `<javaclass>` referred to a class that is annotated, then the top-level annotation filter used would be `<annotation-type>`.

|====

[[xmlfile-syntax]]
== <xmlfile> Syntax

=== Summary 

Use the `<xmlfile>` element to find information in XML files. For a better understanding of the `<xmlfile>` condition, see the http://windup.github.io/windup/docs/latest/javadoc/org/jboss/windup/rules/apps/xml/condition/XmlFile.html[XmlFile] JavaDoc.

The following is an example of a rule that tests for an XML file.
[source,xml,options="nowrap"]
----
<rule id="UNIQUE_RULE_ID">
    <when>
        <xmlfile matches="/w:web-app/w:resource-ref/w:res-auth[text() = 'Container']">
            <namespace prefix="w" uri="http://java.sun.com/xml/ns/javaee"/>
        </xmlfile>
    </when>
    <perform>
        <hint title="Title for Hint from XML">
            <message>Container Auth</message>
        </hint>
        <xslt description="Example XSLT Conversion" extension="-converted-example.xml" 
              template="/exampleconversion.xsl"/>
    </perform>
</rule>
----

=== Construct an <xmlfile> Element

==== <xmlfile> Element Attributes

[cols="1,1,3", options="header"] 
|====
|Attribute Name
|Type
|Description

|matches
|XPATH
a|Match on an XML file condition. (Optional)

_Example:_

[options="nowrap"]
----
matches="/w:web-app/w:resource-ref/w:res-auth[text() = 'Container']"
----
   
|xpathResultMatch
|XPATH_RESULT_STRING
a|Return results that match the given regex. (Optional)

_Example:_

[options="nowrap"]
----
<xmlfile matches="//foo/text()"
  xpathResultMatch="Text from foo."/>
----

|as
|VARIABLE_NAME
a|A variable name assigned to the rule so that it can be used as a reference in later processing. See the `from` attribute below. (Optional)

_Example:_

[options="nowrap"]
----
as="MyEjbRule"
----

|in
|PATH_FILTER
a|Used to filter input files matching this regex (regular expression) naming pattern. Wildcard characters can be used. (Optional)

_Example:_

[options="nowrap"]
----
in="{*}File1"
----

|from
|VARIABLE_NAME
a|Begin the search query with the filtered result from a previous search identified by its `as` VARIABLE_NAME. (Optional)

_Example:_

[options="nowrap"]
----
from="MyEjbRule"
----

|public-id
|PUBLIC_ID
a|The DTD public-id regex. (Optional)

_Example:_

[options="nowrap"]
----
public-id="public"
----

|====


==== <xmlfile> Element: `matches` - Advanced usage: Custom Windup XPath functions

The `matches` attribute may use several built-in custom XPath functions,
which may have useful side effects, like setting the matched value on the rule variables stack.

[cols="1,1", options="header"] 
|====
|Function
|Description

|`windup:matches()`
a|Match a XPath expression against a string, possibly containing Windup parameterization placeholders.

_Example:_

[options="nowrap"]
----
matches="windup:matches(//foo/@class, '{javaclassname}'"
----
This will match all `<foo/>` elements with a `class` attribute and store their value into `javaclassname` parameter for each iteration.


|====

==== <xmlfile> Child Elements

[cols="1,4", options="header"] 
|====
|Child Element
|Description

|<namespace>
a|The namespace referenced in XML files. This element contains 2 optional attributes: The `prefix` and the `uri`.

_Example:_

[source,xml,options="nowrap"]
----
<namespace prefix="abc" uri="http://maven.apache.org/POM/4.0.0"/>
----

|====

[[project-syntax]]
== <project> Syntax

=== Summary 

Use the `<project>` element to query the Maven POM file for the project characteristics. For a better understanding of the `<project>` condition, see the JavaDoc for the http://windup.github.io/windup/docs/latest/javadoc/org/jboss/windup/project/condition/Project.html[Project] class.

The following is an example of a rule that checks for a JUnit dependency version between 2.0.0.Final and 2.2.0.Final.
[source,xml,options="nowrap"]
----
<rule id="UNIQUE_RULE_ID">
    <when>
        <project>
            <artifact groupId="junit" artifactId="junit" from="2.0.0.Final" to="2.2.0.Final"/>
        </project>
    </when>
    <perform>
        <lineitem message="The project uses junit with the version between 2.0.0.Final and 2.2.0.Final"/>
    </perform>
</rule>
----

=== Construct a <project> Element

==== <project> Element Attributes

The `<project>` element is used to match against the project's Maven POM file. You can use this condition to query for dependencies of the project. It does not have any attributes itself.

==== <project> Child Elements

[cols="1,4", options="header"] 
|====
|Child Element
|Description

|<artifact>
a|Subcondition used within `<project>` to query against project dependencies. The `<artifact>` element attributes are described below.
|====

==== <artifact> Element Attributes

[cols="1,1,3", options="header"] 
|====
|Attribute Name
|Type
|Description

|groupId
|PROJECT_GROUP_ID
|Match on the project `<groupId>` of the dependency.

|artifactId
|PROJECT_ARTIFACT_ID
|Match on the project `<artifactId>` of the dependency.

|fromVersion
|FROM_VERSION
|Specify the lower version bound of the artifact. For example `2.0.0.Final`.

|toVersion
|TO_VERSION
|Specify the upper version bound of the artifact. For example `2.2.0.Final`.
|====

[[filecontent-syntax]]
== <filecontent> Syntax

=== Summary

Use the `<filecontent>` element to find strings or text within files, for example, a line in a Properties file. For a better understanding of the `<filecontent>` condition, see the JavaDoc for the http://windup.github.io/windup/docs/latest/javadoc/org/jboss/windup/rules/files/condition/FileContent.html[FileContent] class.

=== Construct a <filecontent> Element

==== <filecontent> Element Attributes

[cols="1,1,3", options="header"] 
|====
|Attribute Name
|Type
|Description

|pattern
|String
|Match the file contents against the provided parameterized string.

|filename
|String
|Match the file names against the provided parameterized string.

|as
|VARIABLE_NAME
a|A variable name assigned to the rule so that it can be used as a reference in later processing. See the `from` attribute below.

_Example:_

[options="nowrap"]
----
as="MyEjbRule"
----

|from
|VARIABLE_NAME
a|Begin the search query with the filtered result from a previous search identified by its `as` VARIABLE_NAME. (Optional)

_Example:_

[options="nowrap"]
----
from="MyEjbRule"
----

|====


[[file-syntax]]
== <file> Syntax

=== Summary

Use the `<file>` element to find the existence of files with a specific name, for example, an `ibm-webservices-ext.xmi` file. For a better understanding of the `<file>` condition, see the JavaDoc for the http://windup.github.io/windup/docs/latest/javadoc/org/jboss/windup/rules/files/condition/File.html[File] class.

=== Construct a <file> Element

==== <file> Element Attributes

[cols="1,1,3", options="header"] 
|====
|Attribute Name
|Type
|Description

|filename
|String
|Match the file names against the provided parameterized string.

|as
|VARIABLE_NAME
a|A variable name assigned to the rule so that it can be used as a reference in later processing. See the `from` attribute below.

_Example:_

[options="nowrap"]
----
as="MyEjbRule"
----

|from
|VARIABLE_NAME
a|Begin the search query with the filtered result from a previous search identified by its `as` VARIABLE_NAME. (Optional)
 
_Example:_

[options="nowrap"]
----
from="MyEjbRule"
----

|====
