[[target_runtime_labels]]
= Target Runtime Labels (including custom Target Runtime Labels)

The Target Runtime feature assesses all of the Technology Tags identified for each application for compatibility with specific runtimes.
EAP and JWS are the two Target Runtime definitions that are included in the {ProductShortName} distribution.
Target Runtime definitions are extensible enabling you to use custom Target Runtimes in analysis executions.

////
[IMPORTANT]
====
Technology Preview features are not supported with Red Hat production
service level agreements (SLAs), might not be functionally complete, and
Red Hat does not recommend to use them for production. These features
provide early access to upcoming product features, enabling customers to
test functionality and provide feedback during the development process.

See link:{KBArticleTechnologyPreview}[Technology Preview Features Support
Scope] on the Red Hat Customer Portal for information about the
support scope for Technology Preview features.
====
////
