[[test_xml_rule]]
= Testing XML Rules

[[add_the_rule_to_windup]]
== Add the Rule to {ProductName}

A {ProductName} rule is installed by copying the rule to the appropriate {ProductShortName} folder. {ProductShortName} scans for rules, which are files that end with `.windup.xml`, in the following locations.

* The directory specified by the `--userRulesDirectory` argument on the {ProductShortName} command line.

* The `__RHAMT_HOME__/rules/` directory. xref:about_home_var[`__RHAMT_HOME__`] is the directory where you install and run the {ProductName} executable.

* The `${user.home}/.rhamt/rules/` directory. This directory is created by {ProductShortName} the first time it is executed and contains rules, add-ons, and the {ProductShortName} log.
+
NOTE: For Windows, this directory would be `\Documents and Settings&#x5c;__USER_NAME__\.rhamt\rules\` or `\Users&#x5c;__USER_NAME__\.rhamt\rules\`.

== Test the XML Rule

Test the XML rule against your application file by running {ProductShortName} in a terminal.

[options="nowrap",subs="+quotes"]
----
$ __RHAMT_HOME__/bin/rhamt-cli [--sourceMode] --input __INPUT_ARCHIVE_OR_FOLDER__ --output __OUTPUT_REPORT_DIRECTORY__ --target __TARGET_TECHNOLOGY__ --packages __PACKAGE_1__ __PACKAGE_2__ __PACKAGE_N__
----

You should see the following result:

[options="nowrap",subs="+quotes"]
----
Report created: __OUTPUT_REPORT_DIRECTORY__/index.html
              Access it at this URL: file:///__OUTPUT_REPORT_DIRECTORY__/index.html
----

More examples of how to run {ProductShortName} are located in the {ProductDocUserGuideURL}[_{ProductName} User Guide_].
