// Module included in the following assemblies:
//
// * docs/vsc-extension-guide/master.adoc


[id="vs-code-extension-interface_{context}"]
= {ProductName} extension interface

The following components are displayed in the interface of the {ProductName} extension:

* *Issue Explorer* displays the applications and files analyzed by MTA and any issues uncovered by the analysis. *Issue Explorer* also includes a folder icon named *Report*, which opens the *MTA Report* in your browser. Each issue is marked in the *Issue Explorer* with an icon indicating its severity and ability to be remedied by a "quick fix."

* The *MTA CLI* executes the MTA analysis, flags the migration issues, and generates the *MTA Report*.

* The *Command window* displays your configuration settings, such as source, target, and advanced options.

* The *Progress window* displays progress of an analysis and provides additional information about it. When the analysis is over, the *Open Report* button becomes visible and active.

* The *MTA Report* is an HTML report generated by the MTA plugin that opens in your browser. From the report landing page you can navigate to detailed reports, such as Application Details, Issues, and Dependencies. The report is described in detail in link:{ProductDocUserGuideURL}/index#review_reports_cli-guide[{ProductShortName} Report].
