// Module included in the following assemblies:
//
// * docs/web-console-guide/master.adoc

:_content-type: PROCEDURE
[id="web-add-user_{context}"]
= Adding a {WebName} user

When authentication is enabled for the {WebName}, administrators will need to add users so that they can access the {WebName}.

Follow these steps to add a new {WebName} user.

. Make sure that the {WebName} is running.
. Open the Red Hat Single Sign-On administration console.
* For a `.zip` installation:
.. Navigate to `\http://localhost:8080/auth/` in a browser.
.. Select *Administration Console* to access the Red Hat Single Sign-On administration console.
* For an OpenShift installation:
.. Navigate to `<OPENSHIFT_URL>/console/project/{LC_PSN}/overview` in a browser.
+
NOTE: If you renamed the OpenShift project when deploying, replace `{LC_PSN}` with the name of your project.
.. Click the link in the *SSO HTTPS* application and add "/auth" to the end of the URL.
.. Select *Administration Console* to access the Red Hat Single Sign-On administration console.
. Log in with an administrative user's credentials. The default credentials are `admin` and `password`.
. In the upper left corner, select the *{LC_PSN}* realm from the drop down.
. From the left-side navigation menu, select *Users* and then click *Add user*.
. Enter the *Username*, *First Name*, *Last Name*, and any other required fields and click *Save*.
. Once the user has been added, select the *Credentials* tab.
. Enter a temporary password in the *New Password* and *Password Confirmation* fields, and leave the *Temporary* field set to *ON*.
. Click *Reset Password* and then click *Change password* in the confirmation popup.

The user is enabled by default and will be required to set a new password when they log in to the {WebName} with this temporary password.
