[[deploy_rhamt_app_openshift]]
= Deploy the {ProductShortName} Application

. Download the {WebName} from the link:https://developers.redhat.com/products/rhamt/download[{ProductShortName} Download page].
. Extract the ZIP file to a directory of your choice.
+
The path to the directory created by unzipping this file is referred to as `_RHAMT_HOME_` throughout this guide.

. Use the `oc login` command to connect to your OpenShift instance.
+
[options="nowrap",subs="+quotes"]
----
$ oc login --username __USERNAME__ --password __PASSWORD__
----
+
Provide any arguments that your instance requires, such as `--username` and `--password`, `--token`, or `--server`.

. Review and adjust default values for the installation.
+
The `__RHAMT_HOME__/openshift/deployment.properties` file defines default values, such as `rhamt` as the project name, 10GB as the persistent storage volume size, and 2GB as the requested memory. Review and change any default settings to your needs before running the `deploy.sh` script.

. Execute the `deploy.sh` script to deploy the {WebName} to OpenShift.
+
[options="nowrap",subs="+quotes"]
----
$ __RHAMT_HOME__/openshift/deploy.sh
----

. Wait for the `deploy.sh` script to complete. This may take several minutes.

Once the script completes, you can xref:access_console_openshift[access the web console] from a browser.
