// Module included in the following assemblies:
// * docs/web-console-guide/master.adoc
[id='troubleshoot_web_console_openshift_install_{context}']
= Troubleshooting a {WebName} installation on OpenShift

The following steps discuss common techniques for troubleshooting the {WebName} installation in an OpenShift environment. These instructions are focused on issues specific to the {WebName}.

== Reporting issues

The {ProductName} uses Jira as its issue tracking system. If you encounter any issues while using the {WebName}, please file a Jira issue by following the instructions below:

NOTE: If you do not already have a Jira account, you must sign up for one in order to create a Jira issue.

. Open a browser and navigate to the Jira link:https://issues.redhat.com/projects/WINDUP[Create Issue] page.
+
If you have not yet logged in, click *Log In* on the upper right of the page and enter your credentials.

. Select the following options and click *Next*.

* *Project*: Choose `{ProductName} (WINDUP)`
* *Issue Type*: `Bug`

. On the next screen complete the following fields:

* *Summary*: Enter a brief description of the problem or issue.
* *Environment*: Indicate that this is an OpenShift installation of the {WebName}, and include any environment variables in use with the image.
* *Description*: Provide a detailed description of the issue. Be sure to include any errors encountered and exception traces.
* *Attachment*: Include the logs. At a minimum this should include the logs from each pod.
+
If the application or archive causing the issue does not contain sensitive information and you are comfortable sharing it with the {ProductShortName} development team, attach it to the issue using the *Browse* button.

. Click *Create* to create the Jira issue.
