// Module included in the following assemblies:
//
// * docs/web-console-guide/master.adoc

:_content-type: PROCEDURE
[id="web-openshift-insufficient-resources_{context}"]
= Resolving insufficient resources

The following conditions indicate insufficient resources:

 * The `{LC_PSN}-web-console` pod is not running and the following error is displayed on the *Events* tab of the *Pod Details* screen in the OpenShift console:
+
[source,terminal,subs="attributes+"]
----
0/9 nodes are available: 4 Insufficient cpu, 4 MatchNodeSelector, 9 Insufficient memory.
----

* The `{LC_PSN}-web-console-deploy`, `{LC_PSN}-web-console-executor-deploy`, and `{LC_PSN}-web-console-postgresql-deploy` pods time out and the following error is displayed in the logs:
+
[source,terminal,subs="attributes+"]
----
error: update acceptor rejected {LC_PSN}-web-console-executor-1: Pods for rc '{LC_PSN}/{LC_PSN}-web-console-executor-1' took longer than 600 seconds to become available
----

.Procedure

. Install and run the link:{OpenShiftDocsURL}/nodes/clusters/nodes-cluster-resource-levels.html[cluster capacity tool] to determine how many pods you can schedule.

. Change the load on the cluster resources by performing one of the following actions:

* Increase the link:{OpenShiftDocsURL}/nodes/clusters/nodes-cluster-limit-ranges.html[limit ranges] or the link:{OpenShiftDocsURL}/applications/quotas/quotas-setting-per-project.html[resource quotas] of your project.
* Reduce the requested resources of your project. The {WebName} requires a minimum of 4 vCPUs and 8 GB RAM.
* Run fewer jobs.

. Redeploy the {WebName}.
