// Module included in the following assemblies:
//
// * docs/web-console-guide/master.adoc

:_content-type: PROCEDURE
[id="web-change-admin-user_{context}"]
= Changing the administrative user's credentials

When you enable authentication for the {WebName}, a default administrative user is provided with the username `admin` and password `password`. You should change this password so that only those that are authorized can make further changes to {WebName} users.

Follow these steps to change the default administrative user's password.

. Make sure that the {WebName} is running.
. Open the Red Hat Single Sign-On administration console.
* For a `.zip` installation:
.. Navigate to `\http://localhost:8080/auth/` in a browser.
.. Select *Administration Console* to access the Red Hat Single Sign-On administration console.
* For an OpenShift installation:
.. Navigate to `<OPENSHIFT_URL>/console/project/{LC_PSN}/overview` in a browser.
+
NOTE: If you renamed the OpenShift project when deploying, replace `mtr` with the name of your project.
.. Click the link in the *SSO HTTPS* application and add "/auth" to the end of the URL.
.. Select *Administration Console* to access the Red Hat Single Sign-On administration console.
. Log in with the default credentials of `admin` and `password`.
. In the upper left corner, select the *Master* realm from the drop down.
. In the left-side navigation menu, select *Users* and then click *View all users*.
. From the *admin* user's row, click *Edit*.
. Select the *Credentials* tab.
. Enter the new password in the *New Password* and *Password Confirmation* fields.
. Change the *Temporary* field to *OFF* to not require the user to change the password upon next login.
. Click *Reset Password* and then click *Change password* in the popup.

You can also remove this default administrative user completely and create your own administrative users. However, be sure to add the new users before removing the default user.
