[[add_user]]
= Add a New {WebNameTitle} User

When xref:enable_auth[authentication is enabled] for the {WebName}, administrators will need to add users so that they can access the {WebName}.

Follow these steps to add a new {WebName} user.

. Make sure that the {WebName} is xref:starting_console[running].
. Open the Red Hat Single Sign-On administration console.
* For a ZIP installation:
.. Navigate to `http://localhost:8080/auth/` in a browser.
.. Select *Administration Console* to access the Red Hat Single Sign-On administration console.
* For an OpenShift installation:
.. Navigate to `__OPENSHIFT_URL__/console/project/rhamt/overview` in a browser.
+
NOTE: If you renamed the OpenShift project when xref:deploy_rhamt_app_openshift[deploying], replace `rhamt` with the name of your project.
.. Click the link in the *SSO HTTPS* application and add "/auth" to the end of the URL.
.. Select *Administration Console* to access the Red Hat Single Sign-On administration console.
. Log in with an administrative user's credentials. The default credentials are `admin` and `password`.
. In the upper left corner, select the *Rhamt* realm from the drop down.
. From the left-side navigation menu, select *Users* and then click *Add user*.
. Enter the *Username*, *First Name*, *Last Name*, and any other required fields and click *Save*.
. Once the user has been added, select the *Credentials* tab.
. Enter a temporary password in the *New Password* and *Password Confirmation* fields, and leave the *Temporary* field set to *ON*.
. Click *Reset Password* and then click *Change password* in the confirmation popup.

The user is enabled by default and will be required to set a new password when they log in to the {WebName} with this temporary password.
