// Module included in the following assemblies:
//
// * docs/getting-started-guide-mtr/master.adoc
// * docs/cli-guide-mtr/master.adoc
// * docs/intellij-idea-plugin-guide-mtr/master.adoc
// * docs/maven-guide-mtr/master.adoc
// * docs/eclipse-code-ready-studio-guide-mtr/master.adoc
// * docs/web-console-guide-mtr/master.adoc
// * docs/plugin-guide-mtr/master.adoc

[[about_mta]]
:_content-type: CONCEPT
[id="what-is-the-toolkit_{context}"]
= About the {ProductName}

[discrete]
== What is the {ProductName}?

The {ProductName} ({ProductShortName}) is an extensible and customizable rule-based tool that simplifies the migration and modernization of Java applications.

{ProductShortName} examines application artifacts, including project source directories and application archives, and then produces an HTML report highlighting areas needing changes. {ProductShortName} supports many migration paths, including the following examples:

* Upgrading to the latest release of Red Hat JBoss Enterprise Application Platform
* Migrating from Oracle WebLogic or IBM WebSphere Application Server to Red Hat JBoss Enterprise Application Platform
* Containerizing applications and making them cloud-ready
* Migrating from Java Spring Boot to Quarkus
* Updating from Oracle JDK to OpenJDK
* Upgrading from OpenJDK 8 to OpenJDK 11
* Upgrading from OpenJDK 11 to OpenJDK 17
* Upgrading from OpenJDK 17 to OpenJDK 21
* Migrating EAP Java applications to Azure
* Migrating Spring Boot Java applications to Azure

For more information about use cases and migration paths, see the link:https://developers.redhat.com/products/{LC_PSN}/use-cases[{ProductShortName} for developers] web page.

[discrete]
== How does the {ProductName} simplify migration?

The {ProductName} looks for common resources and known trouble spots when migrating applications. It provides a high-level view of the technologies used by the application.

{ProductShortName} generates a detailed report evaluating a migration or modernization path. This report can help you to estimate the effort required for large-scale projects and to reduce the work involved.

ifndef::getting-started-guide[]
[discrete]
== How do I learn more?

See the link:{ProductDocIntroToMTAGuideURL}[Introduction to the {DocInfoProductName}] to learn more about the features, supported configurations, system requirements, and available tools in the {ProductName}.
endif::getting-started-guide[]
