// Module included in the following assemblies:
//
// * docs/getting-started-guide/master.adoc
// * docs/cli-guide/master.adoc
// * docs/maven-guide/master.adoc
// * docs/eclipse-code-ready-studio-guide/master.adoc
// * docs/web-console-guide/master.adoc

[[about_mta]]
:_content-type: CONCEPT
[id="what-is-the-toolkit_{context}"]
= About the {ProductName}

[discrete]
== What is the {ProductName}?

The {ProductName} ({ProductShortName}) is an extensible and customizable rule-based tool that simplifies migrating and modernizing Java applications.

{ProductShortName} examines application artifacts, including project source directories and application archives. It then produces an HTML report highlighting areas that need changes. {ProductShortName} supports many migration paths including the following examples:

* Upgrade to the latest release of Red Hat JBoss Enterprise Application Platform
* Migrate from Oracle WebLogic or IBM WebSphere Application Server to Red Hat JBoss Enterprise Application Platform
* Containerize applications and making them cloud-ready
* Migrate from Java Spring Boot to Quarkus
* Update from Oracle JDK to OpenJDK
* Upgrade from OpenJDK 8 to OpenJDK 11
* Upgrade from OpenJDK11 to OpenJDK 17
* Migrate EAP Java applications to Azure
* Migrate Spring Boot Java applications to Azure

For more information about use cases and migration paths, see the link:https://developers.redhat.com/products/mtr/use-cases[{ProductShortName} for developers] web page.

[discrete]
== How does the {ProductName} simplify migration?

The {ProductName} looks for common resources and known trouble spots when migrating applications. It provides a high-level view of the technologies used by the application.

{ProductShortName} generates a detailed report evaluating a migration or modernization path. This report can help you to estimate the effort required for large-scale projects and to reduce the work involved.

ifndef::getting-started-guide[]
[discrete]
== How do I learn more?

See the link:{ProductDocIntroToMTAGuideURL}[Introduction to the {DocInfoProductName}] to learn more about the features, supported configurations, system requirements, and available tools in the {ProductName}.
endif::getting-started-guide[]
