// Module included in the following assemblies:
// * docs/cli-guide_5/master.adoc
// * docs/maven-guide_5/master.adoc
// * docs/web-console-guide_5/master.adoc
[[about_mta]]
[id='about_mta_{context}']
= About the {ProductName}

[discrete]
== What is the {ProductName}?

The {ProductName} ({ProductShortName}) is an extensible and customizable rule-based tool that simplifies the migration of Java applications.

The {ProductShortName} examines application artifacts, including project source directories and application archives, then produces an HTML report that highlights areas needing changes. {ProductShortName} can migrate Java applications from earlier versions of Red Hat JBoss Enterprise Application Platform or from other application servers, such as Oracle WebLogic Server or IBM WebSphere Application Server.

[discrete]
== How does the {ProductName} simplify migration?

The {ProductName} looks for common resources and highlights technologies and known trouble spots when migrating applications. The goal is to provide a high-level view into the technologies used by the application and provide a detailed report organizations can use to estimate, document, and migrate enterprise applications to Java EE and Red Hat JBoss Enterprise Application Platform.

ifndef::getting-started-guide[]
[discrete]
== How do I learn more?

See the link:{ProductDocGettingStartedGuideURL}[_{GettingStartedBookName}_] to learn more about the features, supported configurations, system requirements, and available tools in the {ProductName}.
endif::getting-started-guide[]
