// Module included in the following assemblies:
//
// * docs/getting-started-guide/master.adoc
// * docs/cli-guide/master.adoc
// * docs/maven-guide/master.adoc
// * docs/plugin-guide/master.adoc
// * docs/web-console-guide/master.adoc

[[about_mta]]
[id='what-is-the-toolkit_{context}']
= About the {ProductName}

[discrete]
== What is the {ProductName}?

The {ProductName} ({ProductShortName}) is an extensible and customizable rule-based tool that simplifies the migration and modernization of Java applications.

{ProductShortName} examines application artifacts, including project source directories and application archives, then produces an HTML report that highlights areas needing changes. {ProductShortName} supports many migration paths including:

* Application servers to Red Hat JBoss Enterprise Application Platform
* Application containerization and cloud readiness
* Spring Boot to Quarkus
* Updates to OpenJDK

For more information see, link:https://developers.redhat.com/products/mta/use-cases[Migration Toolkit for Applications use cases and migration paths].

[discrete]
== How does the {ProductName} simplify migration?

The {ProductName} looks for common resources and highlights technologies and known trouble spots when migrating applications. It provides a high-level view of the technologies used by the application as well as a detailed report evaluating a proposed migration or modernization. Using this report, an organization can estimate the efforts required for large-scale modernization and migration projects and take specific steps to reduce the work involved.

ifndef::getting-started-guide[]
[discrete]
== How do I learn more?

See the link:{ProductDocIntroToMTAGuideURL}[_{IntroToMTABookName}_] to learn more about the features, supported configurations, system requirements, and available tools in the {ProductName}.
endif::getting-started-guide[]
