// Module included in the following assemblies:
//
// * docs/getting-started-guide/master.adoc
// * docs/cli-guide/master.adoc
// * docs/maven-guide/master.adoc
// * docs/eclipse-code-ready-studio-guide/master.adoc
// * docs/web-console-guide/master.adoc

:_content-type: CONCEPT
[[about_mta]]
[id="what-is-the-toolkit_{context}"]
= About the {ProductName}

[discrete]
== What is the {ProductName}?

The {ProductName} ({ProductShortName}) is an extensible and customizable rule-based tool that simplifies the migration and modernization of Java applications.

{ProductShortName} examines application artifacts, including project source directories and application archives, and then produces an HTML report highlighting areas needing changes. {ProductShortName} supports many migration paths including the following examples:

* Upgrading to the latest release of Red Hat JBoss Enterprise Application Platform
* Migrating from Oracle WebLogic or IBM WebSphere Application Server to Red Hat JBoss Enterprise Application Platform
* Containerizing applications and making them cloud-ready
* Migrating from Java Spring Boot to Quarkus
* Updating from Oracle JDK to OpenJDK

For more information about use cases and migration paths, see the link:https://developers.redhat.com/products/mta/use-cases[MTA for developers] web page.

[discrete]
== How does the {ProductName} simplify migration?

The {ProductName} looks for common resources and known trouble spots when migrating applications. It provides a high-level view of the technologies used by the application.

{ProductShortName} generates a detailed report evaluating a migration or modernization path. This report can help you to estimate the effort required for large-scale projects and to reduce the work involved.

ifndef::getting-started-guide[]
[discrete]
== How do I learn more?

See the link:{ProductDocIntroToMTAGuideURL}[_{IntroToMTABookName}_] to learn more about the features, supported configurations, system requirements, and available tools in the {ProductName}.
endif::getting-started-guide[]
