// Module included in the following assemblies:
//
// * docs/getting-started-guide/master.adoc
// * docs/cli-guide/master.adoc
// * docs/maven-guide/master.adoc
// * docs/plugin-guide/master.adoc
// * docs/web-console-guide/master.adoc

[[about_mta]]
[id='what-is-the-toolkit_{context}']
= About the {ProductName}

[discrete]
== What is the {ProductName}?

The {ProductName} ({ProductShortName}) is an extensible and customizable rule-based tool that simplifies the migration and modernization of Java applications.

The {ProductShortName} examines application artifacts, including project source directories and application archives, then produces an HTML report that highlights areas needing changes. {ProductShortName} supports many migration paths such as different application servers to Red Hat JBoss Enterprise Application Platform, application containerization and cloud readiness, Spring Boot to Quarkus, updates to OpenJDK, and others. For more information about the available migration paths, link:https://developers.redhat.com/products/mta/use-cases[visit the use cases and migration paths page] of the official {ProductShortName} website.

[discrete]
== How does the {ProductName} simplify migration?

The {ProductName} looks for common resources and highlights technologies and known trouble spots when migrating applications. The goal is to provide a high-level view into the technologies used by the application and provide a detailed report organizations can use to estimate, document, and provide technical guidance for large-scale modernization and migration projects.

ifndef::getting-started-guide[]
[discrete]
== How do I learn more?

See the link:{ProductDocIntroToMTAGuideURL}[_{IntroToMTABookName}_] to learn more about the features, supported configurations, system requirements, and available tools in the {ProductName}.
endif::getting-started-guide[]
