== Introduction

This guide is for developers who plan to contribute to the {ProductName} source code base or provide Java-based rule add-ons. 

If you are new to {ProductShortName}, it is recommended that you start with the {ProductDocUserGuideURL}[{ProductName} User Guide]. It provides detailed information about system requirements and detailed instructions on how to install and execute {ProductShortName}. It also contains tips to optimize performance and provides links to other sources of information about {ProductShortName}.

If you would like to create custom XML-based rules for {ProductShortName}, see the {ProductDocRulesGuideURL}[{ProductName} Rules Development Guide].

== Get Started 

After you configure Maven, you are ready to create, install, and test your first {ProductShortName} Java-based rule add-on.

include::Install-and-Configure-Maven.adoc[tabsize=4]

include::Dev-Create-Your-First-Java-based-Rule-Add-on.adoc[tabsize=4]

== Prepare Your Development Environment

If you only plan to create custom {ProductShortName} Java-based rule add-ons, you can skip this chapter. However, if plan to contribute back to the core code base, the following sections describe how to access and build the {ProductShortName} source code.

include::Dev-Get-the-Source-Code.adoc[tabsize=4]

include::Dev-Build-from-Source.adoc[tabsize=4]

// include::Dev-Execute-Built-from-Source.adoc[tabsize=4]

== Understand the {ProductName} Architecture and Structure

include::Architectural-Components.adoc[tabsize=4]

include::Dev-Project-Structure.adoc[tabsize=4]


== Rules and Rulesets

include::Processing-Overview.adoc[tabsize=4]

include::Rules-Rule-Execution-Lifecycle.adoc[tabsize=4]

include::Rule-Phases.adoc[tabsize=4]

include::Rules-Available-Rules-Utilities.adoc[tabsize=4]

include::Rules-Rule-Story-Points.adoc[tabsize=4]

include::Rules-Difference-Between-XML-based-and-Java-based-Rules.adoc[tabsize=4]

== Create and Test Java Rule Add-ons

This guide focuses on how to create Java-based rule add-ons. For instructions on how to create XML-based rules, see the {ProductDocRulesGuideURL}[{ProductName} Rules Development Guide].

include::Rules-Java-based-Rule-Structure.adoc[tabsize=4]

include::Rules-Basic-Rule-Execution-Flow-Patterns.adoc[tabsize=4]

include::Rules-Create-a-Basic-Java-based-Rule-Add-on.adoc[tabsize=4]

==== Debugging, Profiling, and Logging

include::Dev-Debugging-and-Profiling.adoc[tabsize=4]

==== Developer Contributing Information

include::Dev-Development-Guidelines-and-Conventions.adoc[tabsize=4]

include::Dev-Submit-Code-Updates-to-the-Project.adoc[tabsize=4]



// == Additional Resources

// include::Review-the-Quickstarts.adoc[tabsize=4]

// include::Get-Involved.adoc[tabsize=4]

// include::Important-Links.adoc[tabsize=4]

// include::Known-Issues.adoc[tabsize=4] 

// include::Report-Issues.adoc[tabsize=4]

== Appendix

// include::Glossary.adoc[tabsize=4]

include::About-the-HOME-Variable.adoc[tabsize=4]

include::Dev-Project-Information.adoc[tabsize=4]



