// Module included in the following assemblies:
//
// * docs/release_notes/master.adoc

[id="rn-new-features_{context}"]
= New features

This section describes the new features of the {ProductName} ({ProductShortName}) {ProductVersion}.

.Rules for migrating from Java EE8 to Jakarta EE9
{ProductShortName} rules replace Java EE8 artifact dependencies and package import statements and rename XML schema namespaces, prefixed properties, and bootstrapping files for Jakarta EE9.

Most rules contain quick fixes to automate source code changes when using an {ProductShortName} IDE plugin or extension for Eclipse, Eclipse Che, IntelliJ IDEA, Microsoft Visual Studio Code, or Red Hat CodeReady Studio.

To execute the rules, use the target `jakarta-ee`.

.OpenRewrite recipe support

link:https://docs.openrewrite.org/[OpenRewrite] automates large-scale, distributed source code refactoring. You can execute OpenRewrite recipes by using the link:{ProductDocUserGuideURL}/getting_started#execute_cli-guide[{ProductShortName} CLI].

The first OpenRewrite recipe, which is shipped with {ProductShortName} 5.2.1, renames imported `javax` packages to their `jakarta` equivalents.

[IMPORTANT]
====
OpenRewrite recipe support is provided as Technology Preview only. Technology Preview features are not supported with Red Hat production service level agreements (SLAs), might not be functionally complete, and Red Hat does not recommend to use them for production. These features provide early access to upcoming product features, enabling customers to test functionality and provide feedback during the development process.

See link:{KBArticleTechnologyPreview}[Technology Preview features support scope] on the Red&nbsp;Hat Customer Portal for information about the support scope for Technology Preview features.
====

.{ProductShortName} extension for Visual Studio Code compatible with Codespaces

The {ProductShortName} extension for Microsoft Visual Studio Code is now compatible with Microsoft Visual Studio Codespaces.

.Rules for the Springboot-to-Quarkus migration path

Rulesets identify Quarkus-supported technologies by detecting a POM dependency, embedded JAR file, or a partial file path within an Apache Maven Shade uber JAR.

The rules identify the following technologies:

* Apicurio Studio
* Flyway
* Liquibase
* Liquibase for MongoDB
* OpenTelemetry
* Picocli
