[[Dev-Windup-Configuration]]
=== Windup Configuration

This section describes the how Windup processes configuration arguments. Windup configuration handles of the following types of arguments.

* Forge related arguments
* Windup Core arguments
* Windup Rules arguments

== Forge related arguments

Forge related arguments are those that process add-ons and affect Forge execution mode.

* --install
* --remove
* --list
* --addonDir
* --immutableAddonDir
* --batchMode
* --evaluate
* --debug
* --version

These arguments are handled in the Windup `Bootstrap` class.

TO_DO: Link (to some Forge page?)

== Windup Core arguments

The following are Windup core arguments:

* `--input` - `InputPathOption`
* `--output` - `OutputPathOption`
* `--offline` - `OfflineModeOption`
* `--userRules` - `UserRulesDirectoryOption`
* `--userIgnoreFiles` - `UserIgnoreFilesOption`

==== Getting the arguments value
You can either get a specific option

-------
WindupConfiguration.getOptionValue(OfflineModeOption.NAME)
-------

or iterate over all options:

-------
WindupConfiguration.getWindupConfigurationOptions()
-------

== Custom Arguments for Rules

Additional arguments are made available to Windup rules using a special API. For more information about  Windup rules arguments, see xref:Rules-Rule-Configuration[Rule Configuration].

Each option is an implementation of http://windup.github.io/windup/docs/javadoc/latest/org/jboss/windup/config/WindupConfigurationOption.html[WindupConfigurationOption].
  
Examples:

* `org.jboss.windup.rules.apps.java.config.ScanPackagesOption`
* `org.jboss.windup.rules.apps.java.config.ExcludePackagesOption`
* `org.jboss.windup.rules.apps.java.config.SourceModeOption`

===== Processing Argument Sequence

When the user runs ./windup, the `Bootstrap` class intercepts the Forge arguments and processes them. The other arguments are passed to Windup, which processes them and then distributes them to the right place. During rule execution, the Windup rule arguments are accessed and evaluated.



