[[Dev-Rule-Metadata-and-API-Discrepancies]]
=== Rule Metadata and API Discrepancies

.DRAFT

These are notes about technical debt, which will probably never be removed.

==== API

    public void perform(GraphRewrite event, EvaluationContext evCtx)

Why do we need both event and evaluation context? I think we don't, they could be merged.
What is an "event"? The name doesn't fit.

    GraphContext#setOptions()

What is this? Is it really related to graph?


==== Metadata

    Object cat = event.getRewriteContext().get(RuleMetadata.CATEGORY);

What does it do in `RewriteContext`? That should be bound to `Rule(Provider)`, not a context.
More, this metadata needs the executor to run, wheares other like `getExecuteAfter()` don't.

Data stored to `RewriteContext` e.g. in `enhanceMetadatadata()` go to rules, not to `RuleProvider`s.
This leads to every rule having a `contextMap` where identical values are referenced.

They are under:

    context.map[WindupRuleMetadata].providersToRules[?RuleProvider][?].contextMap
      [CATEGORY] = "java,security"
      [RULE_PROVIDER] = ...
      [ORIGIN] = ...

Why does `enhanceMetadata(Context rewriteCtx)` get a `rewrite.Context`? Why not some `RuleProvider`-related object?

==== GraphRewrite event

The event object is actually not an event. It does not bear any aspects of any event. It is a context. As such, it would be practical to have it injected by CDI, from appropriate scope - in this case, application scope.

[source,java]
------------------
@Override
public void beforeExecution(GraphRewrite event)
{
    LOG.info("Registered " + ArchiveIdentificationGraphChangedListener.class.getSimpleName()
                + "- Archives will be identified automatically.");
    event.getGraphContext().getGraph().addListener(new ArchiveIdentificationGraphChangedListener(event));
}
------------------
