


 

[[Dev-Project-Information]]
=== {ProductName} Project Information

==== Github Repository

The {ProductName} project github repository is located at https://github.com/windup/windup/.

See the _Core-Developer-Guide_ for details on how to contribute to the {ProductName} project source code. 

==== Documentation

The {ProductName} documentation is currently located here in the {ProductName} project https://github.com/windup/windup/wiki/[Wiki].

For additional information, refer to the {ProductName} http://windup.github.io/windup/docs/javadoc/latest/index.html[Javadoc].

==== Website

There is currently no website for {ProductName}.

The windup.jboss.org website currently provides information primarily for legacy Windup 1.x (legacy).

==== IRC chat

Server: irc.freenode.net +
Channel: #windup

==== Mailing lists

Subscribe to the JBoss mailing lists at
https://lists.jboss.org/mailman/listinfo/windup-dev.

* Core development discussion: windup-dev@redhat.com
* Rules development discussion, usage: windup-users@redhat.com

==== Core development team (and IRC nicks)

Lead: Lincoln Baxter (lincolnthree) +
Members: Jess Sightler (jsightler), Matej Briskar (mbriskar), Ondrej
Zizka (ozizka)


==== IRC meeting bot commands (hint for the moderator)

----------------
#startmeeting
#chair lincolnthree, ozizka, jsightler, mbriskar
#addtopic Status Reports
#addtopic Next steps
#nexttopic
#info ...
#endmeeting
Useful Commands: #action #agreed #help #info #idea #link #topic.
----------------
