:ProductName: Windup
:ProductVersion: 2.2.0-Final
:ProductDistribution: windup-distribution-2.2.0-Final
:ProductHomeVar: WINDUP_HOME 

[[Dev-Decompiling]]
=== Decompiling

.DRAFT

==== The *Decompiler* API

* The 3 main use cases for the decompiler API are to process: 

. Directories
. JARS or Archives
. Class files

* The  `DecompilerConfig` should also contain `Filter<String>` (or maybe `Filter<TypeReference>`) to decide whether to decompile the class or not.
* `windup.ProcyonConfiguration` should extend abstract windup.DecompilerConfig<T>, which would contain the configurables common to all decompilers. In case of Procyon, `outputDir` would be delegated to `procyon.DecompilerSettings`.

==== Procyon

===== Config

* `windup.ProcyonConfiguration` contains `procyon.DecompilerSettings`.
* `procyon.DecompilerSettings` contains `outputDir` (the others are not much important). 
TO_DO: Make that a parameter to method call?

===== TypeReference
TO_DO: Check how we get info about Java files; perhaps cache the `TypeReference` results - if worth it?

===== ITypeLoader

* `JarTypeLoader` - iterates a `JarFile`, expects a .jar `File` as input.
* `ClasspathTypeLoader` - loads classes from a list of classes.
    * `ClasspathTypeLoader("some/path:other/path")`
    * `ClasspathTypeLoader()` -> sysprop("java.class.path") : sysprop("sun.boot.class.path")
* `InputTypeLoader`
* `CompoundTypeLoader` - 2 typeloaders, queried in succession

TO_DO: Create a simple `FileSystemTypeLoader`.
