[[Dev-Windup-Project-Structure]]
=== Windup Project Structure

The Windup 2.0 project consists of the following subprojects.

config/::

This project is for the engine that runs the rules and abstracts the graph operations.

decompiler/::

This subproject contains an API that wraps calls to the decompiler. 
Windup currently uses only one decompiler: _Procyon_

exec/::

This subproject contains the bootstrap code to run the Windup application.

ext/::

This subproject is for code extensions. It currently only contains the
Groovy rules syntax. Eventually it will contain any code that is not
related to the rules or the core code base.

graph/::

This subproject contains the datastore and Frames extensions.

logging/::

This is the logging subproject. This subproject may be removed, depending on the outcome of this JIRA: https://issues.jboss.org/browse/WINDUP-49[WINDUP-49].

reporting/::

This subproject contains code that does reporting.

rules/::

This subproject contains all the rules.

test-files/::

This subproject contains the demo applications that are used for test input.

tests/::

This subproject contains the integration test suite.

tinkerpop/::

This subproject contains a code fix for Titan NPE issues.

ui/::

This subproject contains experimental Forge UI code.

utils/:: 

This subproject contains all utility code.