


[Dev-Web-Instructions]
=== {ProductShortName} Web Instructions

The http://windup.jboss.org[windup.jboss.org] web site is hosted by Red Hat / JBoss.org

==== Get the Source Code

The source code for http://windup.jboss.org[windup.jboss.org] is currently located at https://github.com/windup/windup.jboss.org.

. https://github.com/windup/windup.jboss.org./fork[Fork] the windup.jboss.org project. This creates the `windup.jboss.org` project in your own Git with the default remote name 'origin'.
. Clone your fork. This creates and populates a `windup.jboss.org` directory in your local file system.
+
-------------------------------------------------------
git clone https://github.com/<your-username>/windup.git
-------------------------------------------------------
. Navigate to the `windup.jboss.org` directory, then add and fetch the `upstream` repository so you can update your git with any changes.
+
--------------------------------------------------------
git remote add -f upstream git@github.com:windup/windup.jboss.org.git
--------------------------------------------------------

==== Request Write Access to the Web Site Remote Server 

The http://windup.jboss.org[windup.jboss.org] web site is hosted on the `filemgmt.jboss.org` remote server. Follow these steps to request write access.

. Send an email to eng-ops@redhat.com requesting write access to `filemgmt.jboss.org` for `windup.jboss.org`.
. Attach your ssh public key to the email request.
. When you receive confirmation, you can test access in a terminal with the following command. If you are prompted for a password, you do not have proper access.
+
--------
sftp windup@filemgmt.jboss.org
--------

==== Push Updates to the Web Site Remote Server

. Log into the remote server and navigate to www_htdocs/windup/
+
----
$ sftp windup@filemgmt.jboss.org
sftp> cd www_htdocs/windup 
----
. Use the `lcd` command to navigate to the directory on your local machine that contains your updates. You can verify the path on the local machine using the `lpwd` command. For example:
+
----
sftp> lcd ~/windup.jboss.org/assets/js
sftp> lpwd 
Local working directory: /home/username/windup.jboss.org/assets/js
----
. Use the `cd` command to navigate to the corresponding directory on the remote server. You can verify the path on the remote machine using the `pwd` command.
+
----
sftp> cd www_htdocs/windup/assets/js/
sftp> pwd
Remote working directory: /www_htdocs/windup/assets/js
----
. Upload the modified file to the remote server.
+
----
sftp> put windup.js 
Uploading windup.js to /www_htdocs/windup/assets/js/windup.js
windup.js                                        100% 1316     1.3KB/s   00:00    
----
. Test the change on http://windup.jboss.org[windup.jboss.org].

==== Push the Rule Schema to the Web Site Remote Server 

*_Upload Schema Example_* 

----
### Navigate to your local cloned windup.jboss.org directory
cd ~/windup.jboss.org/

### Fetch the latest and check out a branch to work in
git fetch upstream
git checkout -b update-schema upstream/master

### sftp into the remote repository
sftp windup@filemgmt.jboss.org

### Navidate to the remote schema directory
sftp> cd www_htdocs/windup/schema/

### Navigate to the local directory containing the schema
sftp> lcd /home/username/windup/config-xml/

### Push the schema to the remote repository
sftp> put rule-schema.xsd

### You should see "Uploading rule-schema.xsd to /www_htdocs/windup/schema/rule-schema.xsd" rule-schema.xsd  100%   10KB   9.9KB/s   00:00    

### Exit sftp
sftp> exit
----

Use your favorite browser to browse to http://windup.jboss.org/schema/rule-schema.xsd

==== Additional Help

* Type `man sftp` for a list of commands.
* https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html-single/Deployment_Guide/index.html#s2-ssh-clients-sftp
* http://www.tecmint.com/sftp-command-examples/
* https://docs.oracle.com/cd/E26502_01/html/E29001/remotehowtoaccess-14.html

