[[Dev-Submit-Code-Updates-to-the-Windup-Project]]
=== Submit Code Updates to the Windup Project

To get the Windup Source Code, see link:Dev-Get-the-Windup-Source-Code[Get the Windup Source Code] for instructions.

. Open a command terminal and navigate to the root of the Windup project directory.

. Create a new topic branch to contain your features, changes, or fixes using the `git checkout` command:
+
-----------------------------------------------------
 git checkout -b  <topic-branch-name> upstream/master
-----------------------------------------------------

+
If you are fixing a JIRA, it is a good practice to use the number in the
branch name. For example:
+
----------------------------------------------
git checkout -b WINDUP-225 upstream/master
----------------------------------------------

. Make changes or updates to the source files. Be sure to test the changes thoroughly!

. When you are sure your updates are ready and working, use the `git add` command to add new or changed file contents to the
staging area.
+
----------------------
git add <folder-name>/
git add <file-name>
----------------------

. Use the `git status` command to view the status of the files in the
directory and in the staging area and ensure that all modified files are
properly staged:
+
------------------
git status        
------------------

. Commit your changes to your local topic branch. For example:
+
---------------------------------------------------------
git commit -m 'WINDUP-225: Description of change...'     
---------------------------------------------------------

. Push your local topic branch to your GitHub forked repository. This
will create a branch on your GitHub fork repository with the same name as
your local topic branch name.
+
--------------------------------
git push origin HEAD            
--------------------------------
+
_Note: The above command assumes your remote repository is named
'origin'. You can verify your forked remote repository name using the
command `git remote -v`_.

. Browse to the newly created branch on your forked GitHub repository.
+
--------------------------------------------------------------------
https://github.com/<your-username>/windup/tree/<topic-branch-name> 
--------------------------------------------------------------------

. Open a Pull Request. For details, see
https://help.github.com/articles/using-pull-requests[Using Pull
Requests].

* Give the pull request a clear title and description.
* Review the modifications that are to be submitted in the pull to be sure it contains
only the changes you expect.

. The pull request will be reviewed and merged by a Windup project administrator.