:ProductName: Windup
:ProductVersion: 2.2.0-Final
:ProductDistribution: windup-distribution-2.2.0-Final
:ProductHomeVar: WINDUP_HOME 

[[Dev-Troubleshoot-Issues]]
=== Troubleshoot {ProductName} Issues

==== Logging

Logging is currently broken and will not be fixed any time soon. 

See xref:Known-Issues[Known Issues] and https://issues.jboss.org/browse/WINDUP-73[WINDUP-73] for the current status.

==== Debugging Exceptions

Exceptions in Surefire reports are broken due to the way Forge wraps
exceptions and the way Surefire handles them. You need to
debug or rewrap exceptions using `TestUtil.rewrap(ex)`. 

See xref:Known-Issues[Known Issues] and https://issues.jboss.org/browse/WINDUP-197[WINDUP-197] for the current status..

==== Classloading Problems

Configuring dependencies in a Forge-based project can be a little tricky.
// See xref:Dev-Dependencies[Dependencies] for some hints.

-----
Caused by: java.lang.IllegalArgumentException: Type value for model 'org.jboss.windup.rules.files.model.FileReferenceModel' is already registered with model org.jboss.windup.rules.files.model.FileReferenceModel
-----

This means that the model class is loaded twice. I.e. the module containing it is loaded twice. Or, in tests, you may be (accidentally) adding the class to the deployment.
This may especially happen after Maven coordinates of some module are changed.
