[[Execute-Windup]]
=== Execute Windup

==== Prerequisites

Before you begin, you must gather the following information.

. Windup requires that you specify the fully qualified path of the application archive or folder you plan to migrate. This is passed using the `--input` argument on the command line.

. You also specify the fully qualified path to a folder that will contain the resulting report information. This path is passed using the `--output` argument on the command line.
* If the folder does not exist, it is created by Windup. 
* If the folder exists, you are prompted with the message:

       Overwrite all contents of <OUTPUT_DIRECTORY> (anything already in the directory will be deleted)? [y/N] 
+
Choose "y" if you want Windup to delete and recreate the directory. 
* If you are confident you want to overwrite the output directory, you can specify `--overwrite` on the command line to automatically delete and recreate the directory. 
+
NOTE: Be careful not to specify a directory that contains important information!

. You must also provide a list of the application packages to be evaluated. 

* In most cases, you are interested only in evaluating the custom application class packages and not the standard Java EE or 3rd party packages. For example, if the _MyCustomApp_ application uses the package `com.mycustomapp`, you provide that package using the `--packages` argument on the command line. It is not necessary to provide the standard Java EE packages, like `java.util` or `javax.ejb`. 
* While you can provide package names for standard Java EE 3rd party software like `org.apache`, it is usually best not to include them as they should not impact the migration effort.
* If you omit the `--packages` argument, every package in the application is scanned, resulting in very slow performance. It is best to provide the argument with one or more packages.

==== Start Windup

For information about the use of WINDUP_HOME in the instructions below, see xref:About-the-WINDUP_HOME-Variable[About the WINDUP_HOME Variable].

. Open a terminal and navigate to the `WINDUP_HOME/bin` directory

. Type the following command to start Windup:
+
---------------------------------------------------------------------------
For Linux:    WINDUP_HOME/bin $ ./windup
For Windows:  C:\WINDUP_HOME\bin> windup
---------------------------------------------------------------------------

. You are presented with the following prompt.
+
---------------------------------------------------------------------------
Using Windup at WINDUP_HOME

 _       ___           __          
| |     / (_)___  ____/ /_  ______ 
| | /| / / / __ \/ __  / / / / __ \
| |/ |/ / / / / / /_/ / /_/ / /_/ /
|__/|__/_/_/ /_/\__,_/\__,_/ .___/ 
                          /_/      

JBoss Windup, version [ 2.0.0-VERSION ] - JBoss, by Red Hat, Inc. [ http://windup.jboss.org ]

[windup-distribution-2.0.0-VERSION]$ 
---------------------------------------------------------------------------

==== Run the `windup-migrate-app` Command

. The syntax to evaluate an application using the Windup tool requires that you specify the location of the input archive or source code folder, the location of a folder to contain the output reporting information, and the application packages to evaluate. To evaluate an application archive, use the following syntax:
+
---------------------------------------------------------------------------
windup-migrate-app --input INPUT_ARCHIVE_OR_FOLDER --output OUTPUT_REPORT_DIRECTORY --packages PACKAGE_1 PACKAGE_2 PACKAGE_N 
---------------------------------------------------------------------------
+
To run Windup against application source code, you must add the `--sourceMode true` argument:
+
---------------------------------------------------------------------------
windup-migrate-app --sourceMode true --input INPUT_ARCHIVE_OR_FOLDER --output OUTPUT_REPORT_DIRECTORY --packages PACKAGE_1 PACKAGE_2 PACKAGE_N 
---------------------------------------------------------------------------
+
Where:

+
*INPUT_ARCHIVE_OR_FOLDER* is the fully qualified application archive or source path
+
*OUTPUT_REPORT_DIRECTORY* is the fully qualified path to the folder that will contain the the report information produced by Windup.
+
NOTE: If the *OUTPUT_REPORT_DIRECTORY* directory exists, your are prompted to overwrite the contents. If you respond "y", it is deleted and recreated by Windup, so be careful not to specify an output directory that contains important information!

+
*PACKAGE_1*, *PACKAGE_2*, *PACKAGE_N* are the packages to be evaluated by Windup.

+
See xref:windup-command-examples[Windup Command Examples] below for concrete examples of Windup commands using source code directories and archives located in the Windup GitHub repository.

. You should see the following result upon completion of the command:
+
--------
***SUCCESS*** Windup execution successful!
--------

. To exit Windup, type:
+
--------
exit
--------

.  Open the `OUTPUT_REPORT_DIRECTORY/index.html` file in a browser to access the report.
The following subdirectories in the `OUTPUT_REPORT_DIRECTORY` contain the supporting information for the report:

        OUTPUT_REPORT_DIRECTORY/
            graph/
            renderedGraph/
            reports/
            stats/
            index.html

. For details on how to evaluate the report data, see xref:Review-the-Report[Review the Report].

==== Run Windup in Batch Mode 

Windup can be also executed in batch mode within a shell or batch script using the `--evaluate` argument as follows.

. Open a terminal and navigate to the WINDUP_HOME directory. 
. Type the following command to run Windup in batch mode:
+
---------------------------------------------------------------------------
For Linux:     $ bin/windup --evaluate "windup-migrate-app --input INPUT_ARCHIVE --output OUTPUT_REPORT --packages PACKAGE_1 PACKAGE_2 PACKAGE_N"
For Windows:   > bin\windup.bat --evaluate "windup-migrate-app --input INPUT_ARCHIVE --output OUTPUT_REPORT --packages PACKAGE_1 PACKAGE_2 PACKAGE_N"
---------------------------------------------------------------------------

==== Windup Help

To see the list of available parameters for the `windup-migrate-app` command, execute the following command in the Windup prompt:

    man windup-migrate-app

[[windup-command-examples]]
==== Windup Command Examples

The following Windup command examples report against applications located in the Windup source https://github.com/windup/windup/tree/master/test-files[test-files] directory.

===== Source Code Example

The following command runs against the https://github.com/windup/windup/tree/master/test-files/seam-booking-5.2[seam-booking-5.2] application source code. It evaluates all `org.jboss.seam` packages and creates a folder named 'seam-booking-report' in the `/home/username/windup-reports/` directory to contain the reporting output.

   windup-migrate-app --sourceMode true --input /home/username/windup-source/test-files/seam-booking-5.2/ --output /home/username/windup-reports/seam-booking-report --packages org.jboss.seam

===== Archive Example

The following command runs against the https://github.com/windup/windup/blob/master/test-files/jee-example-app-1.0.0.ear[jee-example-app-1.0.0.ear] EAR archive. It evaluates all `com.acme` and `org.apache` packages and creates a folder named 'jee-example-app-1.0.0.ear-report' in the `/home/username/windup-reports/` directory to contain the reporting output.

    windup-migrate-app --input /home/username/windup-source/test-files/jee-example-app-1.0.0.ear/ --output /home/username/windup-reports/jee-example-app-1.0.0.ear-report --packages com.acme org.apache

===== Windup Batch Example

The following Windup batch command runs against the https://github.com/windup/windup/blob/master/test-files/jee-example-app-1.0.0.ear[jee-example-app-1.0.0.ear] EAR archive. It evaluates all `com.acme` and `org.apache` packages and creates a folder named 'jee-example-app-1.0.0.ear-report' in the `/home/username/windup-reports/` directory to contain the reporting output.

----
For Linux: $ bin/windup --evaluate "windup-migrate-app --input /home/username/windup-source/test-files/jee-example-app-1.0.0.ear/ --output /home/username/windup-reports/jee-example-app-1.0.0.ear-report --packages com.acme org.apache"
For Windows: > bin\windup.bat --evaluate "windup-migrate-app --input \windup-source\test-files\jee-example-app-1.0.0.ear --output \windup-reports\jee-example-app-1.0.0.ear-report --packages com.acme org.apache
----

===== Windup Quickstart Examples

For more concrete examples, see the Windup quickstarts located on GitHub here: https://github.com/windup/windup-quickstarts. If you prefer, you can download the https://github.com/windup/windup-quickstarts/releases/tag/2.0.0.Alpha1[2.0.0.Alpha1 release] ZIP or TAR  distribution of the quickstarts.

The quickstarts provide examples of Java-based and XML-based rule addons you can run and test using Windup. The README instructions provide a step-by-step guide to run the quickstart example. You can also look through the code examples and use them as a starting point for creating your own rule addons.

