:ProductName: Windup
:ProductVersion: 2.2.0-Final
:ProductDistribution: windup-distribution-2.2.0-Final
:ProductHomeVar: WINDUP_HOME 

[[Get-Involved]]
=== Get Involved

==== How can you help?

To help us make {ProductName} cover most application constructs and server configurations, including yours, you can help with any of the following items. Many require only a few minutes of your time!

* Send an email to windup-users@lists.jboss.org and let us know what {ProductName} migration rules should cover.
* Provide example applications to test migration rules.
* Identify application components and problem areas that may be difficult to migrate.
** Write a short description of these problem migration areas.
** Write a brief overview describing how to solve the problem migration areas.
* xref:Execute[Try {ProductName}] on your application. Be sure to xref:Report-Issues[report any issues] you encounter.
* You can contribute to the {ProductName} rules repository. 
** Write a {ProductName} rule to identify or automate a migration process.
** Create a test for the new rule.
** Details are provided in the _{ProductName} Rules Development Guide_.
* You can also contribute to the project source code. 
** Create a core rule.
** Improve {ProductName} performance or efficiency.
** See the_{ProductName} Core Development Guide_ for information about how to configure your environment and set up the project.

Any level of involvement is greatly appreciated!


==== Important links

See the xref:Important-Links[list of links to {ProductName} resources].
