[[Get-Involved]]
=== Get Involved

==== How can you help?

To help us make Windup cover most application constructs and server configurations, including yours, you can help with any of the following items. Some items require only a few minutes of your time!

* mailto:windup-users@redhat.com[Let us know] what Windup migration rules should cover.
* Provide example applications to test migration rules.
* Identify application components and problem areas that may be difficult to migrate.
** Write a short description of these problem migration areas.
** Write a brief guide describing how to solve the problem migration areas.
* xref:Execute-Windup[Try Windup] on your application. Be sure to xref:Report-Issues-with-Windup[report any issues] you encounter.
* Write an Windup rule to automate the migration process.
** Create a test for the new rule.
* You can contribute Windup rules. For details, see the _Windup Rules Development Guide_.
* You can also contribute to the project source code. See the _Windup Core Development Guide_ for information about how to configure your environment and set up the project.

Any level of involvement is greatly appreciated!




