:ProductName: Windup
:ProductShortName: Windup
:ProductVersion: 2.2.0-Final
:ProductDistribution: windup-distribution-2.2.0-Final
:ProductHomeVar: WINDUP_HOME 

[[Install]]
=== Install {ProductName}

==== Minimum System Requirements

* Java Platform, Enterprise Edition 7
* A minimum of 4 GB RAM. For better performance, a 4-core processor with 8 GB RAM is recommended. This allows 3 - 4 GB RAM for use by the JVM.
* A minimum of 4 GB of free disk space. A fast disk, especially a Solid State Drive (SSD), will improve performance.
* {ProductName} is tested on Linux, Mac OS X, and Windows. Other Operating Systems with Java 7 support should work equally well.

==== Download and Install {ProductName}

. Download the latest https://repository.jboss.org/nexus/service/local/artifact/maven/redirect?r=releases&g=org.jboss.windup&a=windup-distribution&v=LATEST&e=zip&c=offline[{ProductName} ZIP distribution].
. Extract the ZIP file in to a directory of your choice. 

NOTE: If you used previous versions of {ProductName}, delete the `${user.home}/.windup/` directory. Otherwise you may see errors like the following when you execute {ProductName}:  
           _Command: windup-migrate-app was not found_
