[[Install-Windup]]
=== Install Windup

==== Minimum System Requirements

* Java Platform, Enterprise Edition 7
* A minimum of 4 GB RAM. For better performance, a 4-core processor with 8 GB RAM is recommended. This allows 3 - 4 GB RAM for use by the JVM.
* A minimum of 4 GB of free disk space. A fast disk, especially a Solid State Drive (SSD), will improve performance.
* Windup is tested on Linux, Mac OS X, and Windows. Other Operating Systems with Java 7 support should work equally well.

==== Download and Install Windup

. Download the latest https://repository.jboss.org/nexus/service/local/artifact/maven/redirect?r=releases&g=org.jboss.windup&a=windup-distribution&v=LATEST&e=zip&c=offline[Windup ZIP distribution].
. Extract the ZIP file in to a directory of your choice. 

NOTE: If you used previous versions of Windup, delete the `${user.home}/.windup/` directory. Otherwise you may see errors like the following when you execute Windup:  
           _Command: windup-migrate-app was not found_
