


[[Rules-Create-a-Basic-XML-Rule]]
=== Create a Basic XML Rule

You can create a {ProductName} rule using Java, XML, or Groovy. This topic describes how to create a rule using XML.

==== Prerequisites

* You should have already xref:Install[installed {ProductShortName}]. 
* Before you begin, you may also want to be familiar with the following documentation:
** {ProductShortName} rules are based on the ocpsoft *rewrite* project. You can find more information about ocpsoft *rewrite* here: http://ocpsoft.org/rewrite/
** The JavaDoc for the {ProductShortName} API is located here: http://windup.github.io/windup/docs/javadoc/latest/
** The XML rule schema is located here: http://windup.jboss.org/schema/rule-schema_1_0.xsd

==== File Naming Convention for XML Rules

You must name the file containing an XML rule with the `.windup.xml` extension. {ProductShortName} identifies files with this extension as XML-base rules, so be sure to use this naming convention, otherwise the rule will not be evaluated!

==== Basic XML Rule Template

XML rules consist of _conditions_ and _actions_ and follow the familiar "if/then/else" construct:

    when(condition)
        perform(action)
    otherwise(action)

The following is the basic syntax for XML rules.

    <?xml version="1.0"?>
    <ruleset xmlns="http://windup.jboss.org/v1/xml" id="<unique-rule-identifier">
        <metadata>
            <!-- Metadata about the rule including a description, 
                 source technology, target technology, and any
                 add-on dependencies -->
        </metadata>
        <rules>
            <rule>
                <when>
                    <!-- Test a condition... -->
                </when>
                <perform>
                    <!-- Perform this action when condition is satisfied -->
                </perform>
                <otherwise>
                    <!-- Perform this action when condition is not satisfied -->
                </otherwise>
            </rule>
          <rules>
        </ruleset>

==== Create the Ruleset Metadata

The XML ruleset `metadata` element provides additional information about the ruleset such as a description, the source and target technologies, and add-on dependencies. The metadata also allows for specification of tags, which allow you to provide additional information about a ruleset.

_Example:_
[source,xml]
--------
<ruleset id=”ruleset-id”>
<metadata>
        <description>
                This is the description.
        </description>
        <dependencies>
                <addon id="org.jboss.windup.rules,windup-rules-javaee,2.0.1.Final"/>    
                <addon id="org.jboss.windup.rules,windup-rules-java,2.0.0.Final"/>
        </dependencies>
        <sourceTechnology id="weblogic" versionRange="(10,12]"/>
        <sourceTechnology id="ejb" versionRange="(2,3]"/>
        <targetTechnology id="eap" versionRange="(5,6]"/>
        <targetTechnology id="ejb" versionRange="(2,3]"/>
        <tags>
                <tag>require-stateless</tag>
                <tag>require-nofilesystem-io</tag>
        </tags>
        <executeAfter>AfterId</executeAfter>
        <executeBefore>BeforeId</executeBefore>
    </metadata>
    <rules>
    </rules>
</ruleset>
--------

==== Create the Rule When Condition

The syntax is dependent on whether you are creating a rule to evaluate Java class, an XML file, a project, or file content and is described in more detail here: xref:Rules-XML-Rule-When-Condition-Syntax[XML Rule - When Condition Syntax]

==== Create the Rule Perform Action

Operations allowed in the `perform` section of the rule include the classification of application resources, in-line hints for migration steps, links to migration information, and project lineitem reporting. The syntax is described in detail here: xref:Rules-XML-Rule-Perform-Action-Syntax[XML Rule - Perform Action Syntax].



