[[Rules-Rule-Story-Points]]
=== Rule Story Points
.DRAFT


==== What are Story Points?

Story points are an abstract metric used in Scrum methodology to estimate the level of effort for various tasks. They are based on a http://scrummethodology.com/scrum-effort-estimation-and-story-points/[modified Fibonacci sequence]. In a similar manner, Windup uses story points to express the level of effort needed to migrate particular application constructs, and in a sum, the application as a whole.

==== How to Estimate Story Points in a Rule

Estimating story points for a rule can be tricky. The following are general guidelines or suggestions to use when estimating the level of effort required for a rule.

[cols="3*", options="header"] 
|===
|Level of Effort
|Story Points
|Description

|Lift and Shift
|0
|The code or file is standards-based and requires no effort.

|Mapped
| 1- 2 per file
|There is a standard mapping algorithm to port the code or file. The number of story points required is small, but dependent on the number of files to port.

|Custom
|5 - 20 per change or component
a| The number of story points required to modify and rewrite code depends on the complexity of the change, the number of unknown imports, the size of the files, and the number of components. The following are examples of how to estimate story points.

* Port MyBatis to JPA: '20' story points per query.
* Port a web page from one web framework to another depends on the complexity and the number of components involved in the migration. You could estimate '20' story points per component.
|===

