[[Rules-Test-an-XML-Rule-In-Windup]]
=== Test an XML Rule in Windup

==== Add the Rule to Windup

A Windup rule is installed simply by copying the rule to the appropriate Windup folder. Windup scans for rules in the following locations:

* The `WINDUP_HOME/rules/` folder. 
+
This is the folder where you run the Windup executable. See xref:About-the-WINDUP_HOME-Variable[About the WINDUP_HOME Variable] for details.

* The `${user.home}/.windup/rules/` folder. 
+
This folder is created by Windup the first time you execute Windup. It used to track rules and add-ons and to contains the Windup log.
+
--------
For Linux or Mac:   ~/.windup/rules/
For Windows: "\Documents and Settings\USER_NAME\.windup\rules\"  -or-  "\Users\USER_NAME\.windup\rules\"
--------

==== Test the XML Rule

. If you have not started Windup, follow the instructions to xref:Execute-Windup[Execute Windup].

. Test the XML rule against your application file by running the `windup-migrate-app` command in the Windup console prompt. 
+
The command uses this syntax:
+
--------
windup-migrate-app [--sourceMode true] --input INPUT_ARCHIVE_OR_FOLDER --output OUTPUT_REPORT_DIRECTORY --packages PACKAGE_1 PACKAGE_2 PACKAGE_N
--------
+
You should see the following result:
+
--------
***SUCCESS*** Windup report created: OUTPUT_REPORT_DIRECTORY/index.html
--------

==== Additional Resources

* For more information and examples of how to run Windup, see: xref:Execute-Windup[Execute Windup] 
* Working examples of XML-based rules can be found on GitHub in the https://github.com/windup/windup/[Windup source code] GitHub repository and the Windup quickstarts https://github.com/windup/windup-quickstarts/[GitHub repository] or https://github.com/windup/windup-quickstarts/releases[latest release ZIP download].
 
