


[[Rules-Rule-Story-Points]]
=== Rule Story Points

==== What are Story Points?

_Story Points_ are an abstract metric commonly used in Scrum Agile software development methodology to estimate the _level of effort_ needed to implement a feature or change. They are based on a http://scrummethodology.com/scrum-effort-estimation-and-story-points/[modified Fibonacci sequence]. 

In a similar manner, {ProductName} uses _story points_ to express the _level of effort_ needed to migrate particular application constructs, and in a sum, the application as a whole. It does not necessarily translate to man-hours, but the value should be consistent across tasks.

==== How Story Points are Estimated in Rules

Estimating the _level of effort_ for the _story points_ for a rule can be tricky. The following are the general guidelines {ProductShortName} uses when estimating the _level of effort_ required for a rule.

[cols="1,1,3", options="header"] 
|===
|Level of Effort
|Story Points
|Description

|Trivial
|1
|The migration is a trivial change or a simple library swap with no or minimal API changes.

|Complex
| 3
|The changes required for the migration task are complex, but have a documented solution.

|Redesign
|5
|The migration task requires a redesign or a complete library change, with significant API changes.

|Rearchitecture
|7
|The migration requires a complete rearchitecture of the component or subsystem.

|Unknown
|13
|The migration solution is not known and may need a complete rewrite.
|===

==== Task Severity

In addition to the _level of effort_, migration tasks can be assigned a _severity_ that indicates whether the task must be completed or can be postponed.

Mandatory:: The task must be completed for a successful migration. If the changes are not made, the resulting application will not build or run successfully. Examples include replacement of proprietary APIs that are not supported in the target platform. 
Optional:: If the migration task is not completed, the application will work, but the results may not be the optimal. If the change is not made at the time of migration, it is recommended to put it on the schedule soon after migration is completed. An example of this would be the upgrade of EJB 2.x code to EJB 3.

