[[Rules-XML-Rule-Action-XSLT-Syntax]]
=== XML Rule Action - XSLT Syntax

==== Summary 

The `xslt` element specifies how to transform an XML file.

The following is an example of rule that defines an XSLT action.

_Example:_

    <rule id="XmlWebLogicRules_6bcvk">
        <when>
            <xmlfile as="default" matches="/weblogic-ejb-jar"/>
        </when>
        <perform>
            <iteration>
                <classification classification="Weblogic EJB XML" effort="3"/>
                <xslt description="JBoss EJB Descriptor (Windup-Generated)" template="transformations/xslt/weblogic-ejb-to-jboss.xsl" extension="-jboss.xml"/>
            </iteration>
        </perform>
    </rule>

NOTE: The XML rule schema is located here: https://github.com/windup/windup/blob/master/config-xml/rule-schema.xsd.

==== Construct an XSLT Element

===== XSLT Element:  Attributes

of="STRING":: Create a new transformation for the given reference.
+
_Example:_

    of="testVariable_instance"
    
description="String":: Sets the description of this XSLTTransformation.
+
_Example:_

    description="XSLT Transformed Output"

extension="String":: Sets the extension for this XSLTTransformation.
+
_Example:_

    extension="-result.html"


template=String:: Sets the XSL template.
+
_Example:_

    template="simpleXSLT.xsl"

===== XSLT Element: Child Elements

xslt-parameter=Map<String,String> :: Specify XSLTTransformation parameters as property value pairs 
+
_Example:_

    <xslt-parameter property="title" value="EJB Transformation"/>
