:ProductName: Windup
:ProductVersion: 2.2.0-Final
:ProductDistribution: windup-distribution-2.2.0-Final
:ProductHomeVar: WINDUP_HOME 

[[Rules-Rule-Story-Points]]
=== Rule Story Points

==== What are Story Points?

Story points are an abstract metric commonly used in Scrum Agile software development methodology to estimate the level of effort needed to implement a feature or change. They are based on a http://scrummethodology.com/scrum-effort-estimation-and-story-points/[modified Fibonacci sequence]. 

In a similar manner, {ProductName} uses story points to express the level of effort needed to migrate particular application constructs, and in a sum, the application as a whole. It does not necessarily translate to man-hours, but the value should be consistent across tasks.

==== How Story Points are Estimated in Rules

Estimating story points for a rule can be tricky. The following are the general guidelines {ProductName} uses when estimating the level of effort required for a rule.

[cols="3*", options="header"] 
|===
|Level of Effort
|Story Points
|Description

|Lift and Shift
|0
|The code or file is standards-based and requires no effort.

|Mapped
| 1- 2 per file
|There is a standard mapping algorithm to port the code or file. The number of story points required is small, but is dependent on the number of files to port.

|Custom
|5 - 20 per change or component
a| The number of story points required to modify and rewrite code depends on the complexity of the change, the number of unknown imports, the size of the files, and the number of components. The following are examples of how to estimate story points.

* Port MyBatis to JPA: '20' story points per query.
* Port a web page from one web framework to another depends on the complexity and the number of components involved in the migration. You could estimate '20' story points per component.
|===

