[[Rules-XML-Rule-Condition-Java-Class-Syntax]]
=== XML Rule Condition - Java Class Syntax

==== Summary 

Use the `javaclass` element to find imports, methods, variable declarations, annotations, class implementations, and other items related to Java classes. The following is an example of a rule that tests for a `javaclass`.

    <rule>
        <when>
            <javaclass references="org.jboss.ws.api.annotation.WebContext" in="org/jboss/{*}" as="webcontextclasses">
                <location>IMPORT</location>
                <location>TYPE</location>
            </javaclass>
        </when>
        <perform>
            <hint message="WebContext is deprecated." effort="0"/>
        </perform>
    </rule>

==== Construct a JavaClass Element

The XML rule schema is located here: https://github.com/windup/windup/blob/master/config-xml/rule-schema.xsd.

===== JavaClass Element Attributes

references="CLASS_NAME":: The package or class name to match on. Wildcard characters can be used.

    Example: references="org.apache.commons.{*}"
    
as="VARIABLE_NAME":: A variable name assigned to the rule so that it can be used as a reference in later processing. See the `from` attribute below.

    Example: as="MyEjbRule"

in="PATH_FILTER":: Used to filter input files matching this regex (regular expression) naming pattern. Wildcard characters can be used.

    Example: in="{*}File1"

from="VARIABLE_NAME":: Begin the search query with the filtered result from a previous search identified by its `as` VARIABLE_NAME. 

    Example: from="MyEjbRule"

===== JavaClass Element Child Elements

location:: The location where the reference was found in a Java class. Location can refer to annotations, field and variable declarations, imports, and methods. For the complete list of valid values, see the JavaDoc for http://windup.github.io/windup/docs/javadoc/latest/org/jboss/windup/rules/apps/java/scan/ast/TypeReferenceLocation.html[TypeReferenceLocation].

    Example: <location>IMPORT</location>
