


 

[[Rules-Rules-Overview]]
=== Rules Overview

.DRAFT

_This page is under construction_

Ruleset:: A ruleset is a Forge add-on that contains one or more RuleProviders. The following {ProductName} projects are rulesets.

* rules-java-ee
* rules-xml

RuleProvider:: A RuleProvider is a class that implements one or more rules using the `.addRule()` method. The following are examples of legacy Java rules that are defined in `rules-java-ee` ruleset.

* EjbConfig
* JDKConfig
* SeamToCDI

Rule:: A piece of code that performs a single unit of work during the migration process. Depending on the complexity of the rule, it may or may not include configuration data. Extensive configuration information may be externalized into external configuration, for example, a custom XML file. The following is an example of a Java-based rule added to the `JDKConfig` RuleProvider class.

[source,java]
----
.addRule()
    .when(JavaClass.references("java.lang.ClassLoader$").at(TypeReferenceLocation.TYPE))
    .perform(Classification.as("Java Classloader, must be migrated.")
    .with(Link.to("Red Hat Customer Portal: How to get resources via the ClassLoader in a JavaEE application in JBoss EAP",  "https://access.redhat.com/knowledge/solutions/239033"))
     .withEffort(1))
----

Rules Metadata:: Information about whether a particular ruleset applies to a given situation. The metadata can include information about the source and target platform and frameworks.

Rules Pipeline:: A collection of rules that feed information into the knowledge graph

