:ProductName: Windup
:ProductVersion: 2.2.0-Final
:ProductDistribution: windup-distribution-2.2.0-Final
:ProductHomeVar: WINDUP_HOME 

[[Rules-Create-a-Groovy-Rule-Add-on]]
=== Create a Groovy Rule Add-on

You can create a rule add-on using Java or a rule using XML or Groovy. This topic describes how to create a rule add-on using Groovy.

==== Prerequisites

* You should have already xref:Install[installed {ProductName}]. 
* Before you begin, you may also want to be familiar with the following documentation:
** {ProductName} rules are based on the ocpsoft *rewrite* project. You can find more information about ocpsoft *rewrite* here: http://ocpsoft.org/rewrite/
** The JavaDoc for the {ProductName} API is located here: http://windup.github.io/windup/docs/javadoc/latest/

NOTE:  Working examples of Groovy-based rules can be found in the {ProductName} quickstarts GitHub repository located here: https://github.com/windup/windup-quickstarts

==== Groovy Rule Add-on Example

The following is an example of a Groovy rule add-on.

--------
ruleSet("ExampleBlacklistRule").setPhase(RulePhase.MIGRATION_RULES)

    .addRule()
    .when(
        Query.find(JavaClassModel.class).as("javaClasses")
    )
    .perform(
        Iteration.over("javaClasses").perform(
            new GraphOperation  () {
                public void perform(GraphRewrite event, EvaluationContext context) {
                    // System.out.println("Performing rewrite operation")
                }
            }
        )
    )
    .withMetadata(RuleMetadata.CATEGORY, "Java")
--------    

NOTE: {ProductName} only analyzes Groovy rule files with names ending in `.windup.groovy`. Be sure to name Groovy-based rules using this naming convention!

