:ProductName: Windup
:ProductVersion: 2.2.0-Final
:ProductDistribution: windup-distribution-2.2.0-Final
:ProductHomeVar: WINDUP_HOME 

[[Rules-Create-a-Basic-XML-Rule]]
=== Create a Basic XML Rule

You can create a {ProductName} rule using Java, XML, or Groovy. This topic describes how to create a rule using XML.

==== Prerequisites

* You should have already xref:Install[installed {ProductName}]. 
* Before you begin, you may also want to be familiar with the following documentation:
** {ProductName} rules are based on the ocpsoft *rewrite* project. You can find more information about ocpsoft *rewrite* here: http://ocpsoft.org/rewrite/
** The JavaDoc for the {ProductName} API is located here: http://windup.github.io/windup/docs/javadoc/latest/
** The XML rule schema is located here: https://github.com/windup/windup/blob/master/config-xml/rule-schema.xsd.

==== File Naming Convention for XML Rules

You must name the file containing an XML rule with the `.windup.xml` extension. {ProductName} identifies files with this extension as XML-base rules, so be sure to use this naming convention, otherwise the rule will not be evaluated!

==== Basic XML Rule Template

XML rules consist of _conditions_ and _actions_ and follow the familiar "if/then/else" construct:

    when(condition)
        perform(action)
    otherwise
        perform(action)

The following is the basic syntax for XML rules.

    <?xml version="1.0"?>
    <ruleset xmlns="http://windup.jboss.org/v1/xml" id="XmlFileMappings">
        <phase>
            <!-- The phase in which to run the rules -->
        </phase>
        <rules>
            <rule>
                <when>
                    <!-- Test a condition... -->
                </when>
                <perform>
                    <!-- Perform this action when condition is satisfied -->
                </perform>
                <otherwise>
                    <!-- Perform this action when condition is not satisfied -->
                </otherwise>
            </rule>
          <rules>
        </ruleset>

==== Create the Rule When Condition

The syntax is dependent on whether you are creating a rule to evaluate Java class, an XML file, a project, or file content and is described in more detail here: xref:Rules-XML-Rule-When-Condition-Syntax[XML Rule - When Condition Syntax]

==== Create the Rule Perform Action

Operations allowed in the `perform` section of the rule include the classification of application resources, in-line hints for migration steps, links to migration information, and project lineitem reporting. The syntax is described in detail here: xref:Rules-XML-Rule-Perform-Action-Syntax[XML Rule - Perform Action Syntax].


