:ProductName: Windup
:ProductVersion: 2.2.0-Final
:ProductDistribution: windup-distribution-2.2.0-Final
:ProductHomeVar: WINDUP_HOME 

[[Ruleset-XML-Ruleset-Element-Reference]]
=== XML Ruleset Element Reference

ruleset:: Defines this as a {ProductName} rule.
phase:: Specifies when the ruleset should execute. See xref:Rules-Rule-Execution-Lifecycle[Rule Execution Lifecyle] for more information about rule phases.
rules:: Encapsulates all the the individual rules for this ruleset.
rule:: Child of the the `rules` element. One or more rules can be defined for a ruleset.
when:: Child of `rule`. Defines the condition to match on.
javaclass:: Child of `when`. Match on Java class condition.
location:: Child of `javaclass`. The location where the reference was found in a Java source file. See the http://windup.github.io/windup/docs/javadoc/latest/org/jboss/windup/rules/apps/java/scan/ast/TypeReferenceLocation.html[Enum TypeReferenceLocation] Javadoc for valid values.
xmlfile:: Match on XML file condition.
xslt:: This specifies how to transform the the specified XML file
perform:: This element is invoked when the condition is met.
hint:: Child element of `perform`. Used to create a provide a message.
message:: 
xref:
log:: This child element of `perform` is used to log a message. It takes the attribute `message` to define the text message.
otherwise:: Invoked when the condition is not met.
