


[[Export-the-Report-to-a-File]]
=== Export report in a CSV file

{ProductShortName} provides the ability to export the report data, including the *Classifications* and *Hitns*, to a flat file on your local file system.  The export function currently supports the CSV file format, which presents the report data as fields delimited by a comma separator. The CSV format can then be imported and manipulated by spreadsheet software such as Microsoft Excel and OpenOffice or LibreOffice Calc. Spreadsheet software provide the ability to sort, analyze, evaluate, and manage the result data from a Windup report.  

==== Enable the Export Functionality

To enable export of the report into CSV file, run {ProductShortName} with `--exportCSV` argument. The CSV file will be created in the directory specified by the `--output` argument.

====  Overview of the CSV data structure

The CSV output file contains the following data fields:
+
Rule Id:: The ID of the rule that generated the given item.
Problem type:: "Hint" or "Classification"
Title:: The title of the _Classification_ or _Hint_. This field summarizes the issue for the given item.
Description:: The detailed description of the issue for the given item.
Links:: URLs that provide additional information about the issue. A link consists of two attributes:
* The link
* A description of the link
Application:: The name of the application for which this item was generated.
File Name:: The name of the file for the given item.
File Path:: The file path of the file for the given item.
Line:: The line number on the file for the given item.
Story points:: The number of story points, which represent the level of effort, assigned to the given item. 


