:ProductName: JBoss Migration Toolkit
:ProductShortName: JMT
:ProductVersion: 2.2.0-Final
:ProductDistribution: windup-distribution-2.2.0-Final
:ProductHomeVar: WINDUP_HOME 


[[Dev-Build-{ProductName}-from-Source]]
=== Build {ProductName} from Source

This information is provided for new developers who plan to contribute code
to the {ProductName} open source project. This section describes how to build {ProductName} from source and how to extract the {ProductName} distribution that is created during the build process.

If you use Linux and are an experienced {ProductName} developer looking for a quick refresher, jump to: xref:quick-build-review-for-experienced-windup-developers[Quick Build Review for Experienced Windup Developers].

==== System Requirements to Build {ProductName}

. Java 1.7.
+
You can choose from the following:
+
--------------
OpenJDK
Oracle Java SE
--------------
. Maven 3.1.1 or newer
+
If you have not yet installed or configured Maven, see
xref:Install-and-Configure-Maven[Install and Configure Maven] for details.
+
If you have installed Maven, you can check the version by typing the
following in a command prompt:
+
--------------
mvn --version 
--------------
. IDE requirements
+
If you prefer, you can work within an IDE. The following IDEs are recommended.

* http://www.jboss.org/products/devstudio/download/[Red Hat JBoss
Developer Studio 7.1.1] or newer
* https://www.eclipse.org/downloads/[Eclipse 4.3 (Kepler)] or newer

+
You must also make sure the IDE embeds Maven 3.1.1 or later. See
xref:Install-and-Configure-Maven[Install and Configure Maven] for details.

==== Prerequisites

* Make sure you have configured Maven as described here: xref:Install-and-Configure-Maven[Install and Configure Maven].

* {ProductName} source code is located in 3 GitHub projects. Follow the instructions to xref:Dev-Get-the-Windup-Source-Code[Get the Windup Source Code].


==== Build Windup Using Maven Command Line

{ProductName} source code consists of 3 projects: 

* https://github.com/windup/windup-rulesets[windup-ruleset]
* https://github.com/windup/windup[windup]
* https://github.com/windup/windup-distribution[windup-distribution]

The `windup-distribution` project has dependencies on the other 2 projects, so you must build the `windup-ruleset` and `windup` projects first. Use the following steps to build the {ProductName} distribution.

. Build the https://github.com/windup/windup-rulesets[windup-ruleset] project.
+
* Open a command terminal and navigate to the root of the windup-ruleset project directory. 
+
--------------
    cd windup-ruleset/
--------------
+ 
* Build the project.
+
-----------------
mvn clean install
-----------------
. Build the https://github.com/windup/windup[windup] project.
+
* Open a command terminal and navigate to the root of the {ProductName} project directory. 
+
--------------
    cd windup/
--------------
+ 
* Build the project.
+
-----------------
mvn clean install
-----------------

+
* You can also build the project without the tests.
+
---------------------------------
mvn clean install -DskipTests
---------------------------------
. Build the https://github.com/windup/windup-distribution[windup-distribution] project.
+
* Open a command terminal and navigate to the root of the Windup-distribution project directory. 
+
--------------
    cd windup-distribution/
--------------
+ 
* Build the project.
+
-----------------
mvn clean install
-----------------
* The windup distribution ZIP file is located in the `windup-distribution/target/` directory.

==== Build Windup Using Red Hat JBoss Developer Studio or Eclipse

If you prefer, you can use an IDE to build {ProductName}.

. Make sure you have configured the Maven installation in your IDE as described here:
https://github.com/windup/windup/wiki/Install-and-Configure-Maven[Install and Configure Maven].
. Start JBoss Developer Studio or Eclipse.
. Import the `windup-ruleset` project.
* From the menu, select `File` → `Import`.
* In the selection list, choose `Maven` → `Existing Maven Projects`,
then click Next.
* Click `Browse` and navigate to the root of the `windup-ruleset` project directory, then click `OK`.
* After all projects are listed, click `Next`. Ignore any Maven build
or dependency errors and click `Finish`. If you get a dialog titled
_Incomplete Maven Goal Execution_, ignore it and click `OK` to continue.
* In the Project Explorer tab, right-click on the `windup-ruleset` project and choose `Run As` --> `Maven install`.
. Import the `windup` project.
* From the menu, select `File` → `Import`.
* In the selection list, choose `Maven` → `Existing Maven Projects`,
then click Next.
* Click `Browse` and navigate to the root of the `windup` project directory, then click `OK`.
* After all projects are listed, click `Next`. Ignore any Maven build
or dependency errors and click `Finish`. If you get a dialog titled
_Incomplete Maven Goal Execution_, ignore it and click `OK` to continue.
* In the Project Explorer tab, find the `windup_parent` project in the
list, right-click, and choose `Run As` --> `Maven install`.
. Import the `windup-distribution` project.
* From the menu, select `File` → `Import`.
* In the selection list, choose `Maven` → `Existing Maven Projects`,
then click Next.
* Click `Browse` and navigate to the root of the `windup-distribution` project directory, then click `OK`.
* After all projects are listed, click `Next`. Ignore any Maven build
or dependency errors and click `Finish`. If you get a dialog titled
_Incomplete Maven Goal Execution_, ignore it and click `OK` to continue.
* In the Project Explorer tab, right-click on the `windup-distribution` project and choose `Run As` --> `Maven install`.

==== Extract the Windup Distribution Source File

The build process creates a `windup-distribution-<VERSION>-offline.zip file` in the `windup-distribution/target/` directory. 

Unzip the file into a directory of your choice.


[[quick-build-review-for-experienced-windup-developers]]
==== Quick Build Review for Experienced Windup Developers

---------------
git clone git@github.com:windup/windup-ruleset.git windup
cd windup-ruleset
mvn clean install
git clone git@github.com:windup/windup.git windup
## Or if you haven't set up github account:
#git clone https://github.com/windup/windup.git
cd windup
mvn clean install -DskipTests
git clone git@github.com:windup/windup-distribution.git windup
cd windup-distribution
mvn clean install
unzip target/windup-distribution-<VERSION-offline.zip -d <WINDUP-DIRECTORY>
mv /tmp/windup-zip/windup-distribution-* /tmp/windup
---------------
