:toc:
:toclevels: 4
:numbered:

include::topics_5/templates/document-attributes.adoc[]

:imagesdir: topics_5/images
:context: release-notes
:release-notes:

= {ReleaseNotesName}

== Introduction

These release notes describe the new features and changes implemented for the {ProductName} ({ProductShortName}) {ProductVersion} release.

== New Features

Rebranding::
The Red Hat Application Migration Toolkit has been rebranded as the {ProductName} ({ProductShortName}).

New migration path for migrating to Apache{nbsp}Camel{nbsp}3::
{ProductShortName} {ProductVersion} contains a new migration path to support the migration from Apache{nbsp}Camel{nbsp}2 to Apache{nbsp}Camel{nbsp}3. The Camel{nbsp}3 rulesets contain 147 new rules.

== Known Issues

At the time of release, the following known issues are identified as major issues. For a full list of all known issues and issues that have been identified since the release, see link:https://issues.redhat.com/issues/?filter=12348397[open {ProductShortName} issues].

include::topics_5/known_issues.adoc[leveloffset=+2]

== Resolved Issues
// commenting out because only 2 resolved issues.
// At the time of the release the following resolved issues have been identified as important issues worth highlighting. For a full list of all issues resolved in this release, see the link:[{ProductVersion} resolved issues JIRA filter]. 

At the time of release, the following issues have been resolved.

include::topics_5/resolved_issues.adoc[leveloffset=+2]
